containers/crun

.travis.yml, Makefile.am, tests/oci-runtime-validation
For now, the results of the tests are printed without returning an error.
Signed-off-by: Alban Crequy <alban@kinvolk.io>
-----
This is similar to https://github.com/opencontainers/runc/pull/1758. But here I get this error:
```
writing file
'/sys/fs/cgroup/cpu,cpuacct/system.slice/libcrun-58f278ec-efa5-4587-bfb5-63b77347b69a/cgroup.procs':
No space left on device
```
I don't know what is this error but it reminds me of a [bug in the kernel](https://github.com/torvalds/linux/commit/24ee3cf89bef04e8bc23788aca4e029a3f0f06d9) fixed in Linux 4.2 and a [bug in Docker](https://github.com/docker/libcontainer/pull/642) fixed in Docker 1.8 (see also https://github.com/opencontainers/runc/issues/133 and https://github.com/rkt/rkt/issues/1210).
=> Add runtime-tools' validation tests

src/crun.c, src/libcrun/container.c
fix a small issue that prevented -t to work and also don't error out on `--log-format=`, which is just ignored for now.
=> crun: work as a runtime for containerd

src/libcrun/cgroup.c
the issue didn't occur on Fedora as both cpu and cpu,cpuacct are
linked to the same directory, while it happens if the two subsystems
are mounted separately, such as on Gentoo+openrc.
Closes: https://github.com/giuseppe/crun/issues/35
=> cgroup: initialize cpu subsystem

Makefile.am, cfg.mk, src/libcrun/chroot_realpath.c, src/libcrun/linux.c, tests/podman/Dockerfile
resolve symlinks in the target.  It solves an issue when running
Kubernetes as secrets are mounted to /var/run, but it is a symlink
to /run.
=> linux: resolve symlinks for bind mounts

src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c
only the root user can enable all the controllers for the unprivileged users.  Change it to request only the controllers we need.
In the cgroup v2 unified mode, systemd enables by default the pids and memory controllers, an unprivileged user can use them without any change to the system configuration.
=> cgroup: enable only the controllers needed

src/libcrun/cgroup.c
do not error out on the default configuration even if cgroups are not
available.
=> cgroup: ignore default devices configuration

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, tests/podman/run-tests.sh
mount the parent directory, so that the socket can be created by
"start".  "start" will then wait until it receives the notification
that the container is ready.
Closes: https://github.com/giuseppe/crun/issues/12
=> notify: support NOTIFY_SOCKET with create/start

crun.1.md, src/crun.c, src/crun.h, src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c, src/libcrun/container.h
It supports to specify what cgroup manager must be used.  The accepted values are: cgroupfs, systemd and disabled.
=> crun: add new option --cgroup-manager=MANAGER

crun.1.md, src/create.c, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/linux.c, src/libcrun/linux.h, src/run.c
This reverts commit 31d1cf1879d6a0a6b43d0399492a6d174f0c47e3.
Closes: https://github.com/giuseppe/crun/issues/56
=> Revert "crun: drop --no-pivot"

src/libcrun/cgroup.c
write_cpu_resources was not called when using cgroups2.  Also fix an
issue how "quota period" are formatted.
=> libcrun: correctly write cpu resources on cgroups2

src/libcrun/cgroup.c, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/status.c, src/libcrun/utils.c, src/libcrun/utils.h, src/spec.c, tests/tests_libcrun_utils.c
simplify logic for crun_path_exists to not check for the file mode.
It was previously checking whether the file is either writeable or
readable.
This caused an issue with /proc/sysrq-trigger when running in a user
namespace, as the file that has mode 0200 is not owned by root in the
user namespace so crun_path_exists(F_READ) would report it as not
existing and skip to create a bind mount and make it read-only.
Closes: https://github.com/containers/crun/issues/74
=> utils: fix file existence check

src/libcrun/cgroup.c
when running a systemd container or more in general containers that
modify their cgroups there are cases when the join is not possible.
The issue is caused by cgroups v2 not allowing to add processes to a
parent node, but only to the leaf nodes.
systemd creates new subdirectories and use them.
When joining the original configured cgroups v2 fails, fallback to
join $PATH/crun-exec.  Use only one directory, so crun won't leak
directories when there are multiple exec's done, but it may be an
issue if the container creates a subdirectory under ../crun-exec.
=> exec: fix join systemd containers on cgroups v2

src/libcrun/container.c, src/libcrun/seccomp.c, src/libcrun/seccomp.h
now the OCI runtime specs support to specify seccomp flags to use with the seccomp(2) syscall.
The accepted options are:
- SECCOMP_FILTER_FLAG_TSYNC
- SECCOMP_FILTER_FLAG_SPEC_ALLOW
- SECCOMP_FILTER_FLAG_LOG
If there is no selection for the flags to use (i.e. there is no seccomp->flags specified), a default configuration is used:
SECCOMP_FILTER_FLAG_LOG and SECCOMP_FILTER_FLAG_SPEC_ALLOW.
From the man page:
SECCOMP_FILTER_FLAG_LOG (since Linux 4.14)
All filter return actions except SECCOMP_RET_ALLOW should be logged.
An administrator may override this filter flag by preventing
specific actions from being logged via the
/proc/sys/kernel/seccomp/actions_logged file.
SECCOMP_FILTER_FLAG_SPEC_ALLOW (since Linux 4.17)
Disable Speculative Store Bypass mitigation.
Signed-off-by: Giuseppe …
=> seccomp: honor seccomp flags

crun.1.md, src/kill.c, src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/linux.c
with the new functions in place we can finally honor the `--all` option for kill
=> kill: use freezer control when not using a PID namespace

src/libcrun/container.c, src/libcrun/linux.c
create the new cgroup before mounting the cgroup, otherwise
/sys/fs/cgroup uses the old namespace.
=> libcrun: fix creating a new cgroup ns

configure.ac, src/libcrun/container.c, src/libcrun/utils.c, tests/oci-validation/oci-runtime-validation
if the statx(2) syscall is available, use it.
=> utils: use statx(2) when available

src/crun.c
Reporting version as "crun version x.x.x" allows Docker to parse correctly as implemented on the PR https://github.com/moby/moby/pull/39940/.
=> Report version in standard way following runc

src/libcrun/seccomp.c
seccomp_syscall_resolve_name returns a negative result to indicate a
pseudo syscall that is not present on the current architecture.
Handle correctly the return code so that the seccomp filter works well
when running on a non native arch.
Closes: https://github.com/containers/crun/issues/94
=> seccomp: fix lookup for pseudo syscalls

src/libcrun/seccomp.c
add a definition for SECCOMP_FILTER_FLAG_LOG and
SECCOMP_FILTER_FLAG_SPEC_ALLOW if they are not already defined.
Closes: https://github.com/containers/crun/issues/100
=> seccomp: add missing defines

src/libcrun/cgroup.c
on an unified hierarchy ignore cgroups errors if running in a user
namespace and the manager != systemd.  It is the same behaviour that
exists on cgroup v1.
The issue caused the default buildah configuration to fail when
running as rootless on cgroups v2.
=> cgroup: ignore rootless errors if manager != systemd

src/libcrun/container.c, src/libcrun/error.c, src/libcrun/error.h
make sure errors are always written to stderr, even in case a
different --log=FILE is specified.
Closes: https://github.com/containers/crun/issues/102
=> error: always write errors to stderr

cfg.mk, configure.ac, src/libcrun/container.c, src/libcrun/utils.c, src/libcrun/utils.h
if the HOME environment variable is not set, try to read it from the
/etc/passwd file.
=> linux: force HOME to be set

tests/tests_libcrun_utils.c
fix "ignoring return value of FUNCTION, declared with attribute
warn_unused_result" warning.
=> tests: fix compiler warning

src/libcrun/cgroup.c
/proc/self/cgroup may contain cgroupv1 entries even when cgroupv2 is
mounted on the host. When crun is in CGROUP_MODE_UNIFIED, ignore these
other entries and only enter cgroupv2
Closes: #106
=> cgroup: Ignore cgroupv1 /proc entries when cgroupv2 present

src/libcrun/linux.c
On Silverblue, the host's /usr is mounted read-only:
$ findmnt -o TARGET,OPTIONS,PROPAGATION /usr
TARGET OPTIONS              PROPAGATION
/usr   ro,relatime,seclabel shared
On such a system, this throws an EPERM when using crun as the OCI
runtime:
$ podman run \
--rm \
--volume /usr:/run/host/usr:ro \
registry.fedoraproject.org/fedora:31 \
/bin/true
Error: remount '... merged/run/host/usr': Operation not permitted: OCI
runtime permission denied error
The underlying system calls are:
mount("/usr",
"... merged/run/host/usr",
0x55d5dffb0bc0,
MS_NOSUID|MS_NODEV|MS_BIND|MS_REC|MS_SLAVE,
0x55d5dffaeef0) = 0
mount("/usr",
"... merged/run/host/usr",
0x55d5dffb0bc0,
MS_NOSUID|MS_NODEV|MS_REMOUNT|MS_BIND|MS_REC|MS_SLAVE,
NULL) = -1 EPERM (Operation not permitted)
Compare that to the system calls …
=> linux: Keep MS_RDONLY when remounting bind mount of a read-only source

src/libcrun/cgroup.c
ignore joining the cgroups if there is no cgroup configured.  This may
happen for example when running Podman rootless containers with
--cgroup-manager cgroupfs.
=> exec: fix join without cgroups configured

src/libcrun/linux.c
Partially revert "linux: Keep MS_RDONLY when remounting bind mount of
a read-only source"
Keep the MS_RDONLY flag only for bind mounts.
Prevents an issue with creating subsystems directories on cgroups v1.
=> container: drop MS_RDONLY when not creating a bind mount

src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c
when using a user namespace on cgroups v2, make sure the cgroup is owned by root in the namespace.
test case:
$ podman run --cgroupns private --uidmap=0:1:2000 --systemd \
--rm -ti fedora /usr/sbin/init
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1758546
=> cgroups: chown cgroups to root in the user namespace

tests/test_mounts.py
warnings in rootless mode will confuse the libmount parser.
=> test: hide mounts stderr

src/libcrun/container.c, src/libcrun/error.c
when a hook fails, print an error message and state the exit code.
=> container: print an error when a hook fails

contrib/static-builder-x86_64/Dockerfile, contrib/static-builder-x86_64/build.sh
reorder dependencies so that systemd can be correctly linked.
=> build: fix systemd dependency

src/libcrun/container.c, src/libcrun/utils.c, src/libcrun/utils.h
when the executable path has the form ./PATH, make sure the current
working directory is used as a prefix.
Closes: https://github.com/containers/crun/issues/133
=> utils: find_executable honors local dir paths

Makefile.am, README.md, configure.ac, src/libcrun/linux.c, src/libcrun/secure_getenv.c, src/libcrun/utils.c, src/libcrun/utils.h
provide an alternative secure_getenv implementation when it is not available on system.  The implementation is taken from gnulib.
Closes: https://github.com/containers/crun/issues/139
=> build: fix build on Alpine

src/libcrun/cgroup.c
so it garbage collects failed units.
=> systemd: set collectmode=inactive-or-failed

configure.ac
While checking configuration output and was mislead by the bpf function
checking output. So in an attempt to clean up the output, header checks
and messaging was added around the eBPF check source.
=> Clean up eBPF checking in configure.ac

.travis.yml, configure.ac, src/crun.c, src/libcrun/utils.c, tests/alpine-build/run-tests.sh
I'm in the process of adding crun to Gentoo/portage officially gentoo/gentoo#13430, and to get slightly better integration with portage use flags https://wiki.gentoo.org/wiki/Handbook:PPC/Working/USE, it would be nice to have a more granular configure step. I attempted to keep sane defaults for enabling and disabling features
=> Explicitly enable and disable dependent libraries

src/libcrun/linux.c
ignore errors if the file cannot be created as it might already
exist.  We are anyway going to create a mount on top of it and we'll
catch possible errors during the mount itself.
Closes: https://github.com/containers/crun/issues/150
=> linux: ignore errors creating /dev/console

contrib/static-builder-x86_64/Dockerfile
Closes: https://github.com/containers/crun/issues/156
=> contrib, static-x86_64: use seccomp from upstream

Makefile.am, crun.1.md, src/crun.c, src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/ps.c, src/ps.h
Differently than runc, the table output shows only the PID.
Closes: https://github.com/containers/crun/issues/157
=> crun: add ps subcommand

src/libcrun/cgroup.c, src/libcrun/linux.c
Closes: https://github.com/containers/crun/issues/160
a couple of fixes that prevented running on Linux 4.18.
=> cgroup: fix running on CentOS 8

src/libcrun/container.c
reorder the code so that the config.json file is copied after the
validation checks for -d and --console-socket.  In this way it is not
left around on errors.
Closes: https://github.com/containers/crun/issues/167
=> container: not leave config.json on errors

configure.ac, src/libcrun/cgroup.c, src/libcrun/chroot_realpath.c, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/status.c, src/libcrun/utils.c, src/libcrun/utils.h, tests/tests_libcrun_utils.c
when creating a directory, if the path already exists make sure it is a directory.
=> utils: if the path exists check if it a directory

src/libcrun/linux.c, src/libcrun/terminal.c
when running with a terminal and a user != root is specified, make
sure the ownership for the terminal is changed.
Closes: https://github.com/containers/crun/issues/174
=> tty: change owner to the specified UID

contrib/static-builder-x86_64/Dockerfile
when building the Dockerfile I get 
```
When using COPY with more than one source file, the destination must be a directory and end with a /
```
adding the trailing slashes gets me a successful build.
=> fix Dockerfile (trailing slashes)

src/libcrun/linux.c, src/libcrun/utils.c
make sure the the source path is resolved when checking the file
type.
regression introduced with b9a0f0b75e7999ecc7e0d4df90fed24b1de5ac4a
Closes: https://github.com/containers/toolbox/issues/330
=> linux: resolve source paths

src/spec.c
do not look at the euid of the user running the command but use the
specified flag.
Closes: https://github.com/containers/crun/issues/180
=> spec: honor the --rootless flag

.gitignore, GNUmakefile, Makefile.am, build-aux/git-version-gen, build-aux/release.sh, configure.ac, contrib/static-builder-x86_64/Dockerfile
add a script to simplify preparing releases.
It includes:
- tar.gz source tarball
- tar.xz source tarball
- static binary for x86_64
Closes: https://github.com/containers/crun/issues/176
=> contrib/release: new script

Makefile.am
I'm not sure if this is the right solution, but if fixed the build error mentioned in #183.
Fixes #183
=> Fix "No rule to make target '../.version'"

src/libcrun/container.c
make clearer it is the "init" process that runs in the container.
=> container: rename container_entrypoint to container_init

src/libcrun/cgroup.c, src/libcrun/utils.c
if the statx syscall is missing, Glibc may attempt to emulate it and
fails with EINVAL on options that cannot be emulated (such as
AT_STATX_DONT_SYNC).
Closes: https://github.com/containers/crun/issues/189
=> utils: statx fallbacks to stat on EINVAL

src/libcrun/utils.c
when creating a file or a directory, on errors check if the path already exists and return success if it does.
=> utils: ensure path not fail if path already exists

Dockerfile
This commit fixes a missing line-ending escape, allowing builds via invoking the Dockerfile to run.
Signed-off-by: Pete Birley <pete@port.direct>
=> Dockerfile: fix missing line-ending escape

Makefile.am, SECURITY.md, crun.1.md, src/libcrun/linux.c
- use `run.oci` for the crun specific annotations.
- suggest `security@oci.run` for security reports.
=> use oci.run domain for crun

contrib/static-builder-x86_64/Dockerfile
we use systemd only to delegate the cgroups, so the SELinux support is
not necessary.  The SELinux support in crun is not affected.
=> static: build systemd without SELinux

src/libcrun/cgroup.c
when running in cgroup 2 unified mode, make sure v1 named hierarchies
are not joined.
Closes: https://github.com/containers/crun/issues/205
=> cgroup: fix named hierarchies test

src/libcrun/container.c
if the exec process doesn't override the SELinux label and the
AppArmor profile, then use the configuration from the initial
configuration file.
Closes: https://github.com/containers/crun/issues/204
=> container: keep SELinux and AppArmor configuration

crun.1.md, src/libcrun/cgroup.c
add support for the hugetlb cgroups 2 controller.
It depends on the kernel patch:
https://www.spinics.net/lists/cgroups/msg24003.html
=> cgroup: support hugetlb on cgroups 2

python/crun_python.c, src/create.c, src/libcrun/container.c, src/libcrun/container.h
do not fork the current process on create, this prevents creating
additional processes to wait for.
It solves a race when the OCI runtime caller has SUBREAPER set, such
as Buildah.  When the initial process exited, the container process
cannot be directly waited for as there are other processes to reap
first.
Closes: https://github.com/containers/crun/issues/215
=> container: do not fork on create

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, tests/podman/Dockerfile, tests/podman/run-tests.sh
sync latest version of libocispec, it inherits some updated runtime-spec.
and add support for specifying an umask.
=> libocispec: sync from upstream

crun.1.md, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/seccomp.c, src/libcrun/seccomp.h, src/libcrun/utils.c, src/libcrun/utils.h
two separate changes I've put together on the same PR to avoid rebasing:
- The first one is to move seccomp generation out of the init process.  It improves memory usage for the init process and now containers (assuming the init process doesn't need more) can run with 250K memory max configured in the cgroup.
- The second one is to not fail on unknown syscalls specified to seccomp.  An annotation is added too keep the previous behaviour.
More details are in the commit messages.
=> seccomp: move generation out of cgroup and do not fail on unknown syscalls

src/libcrun/linux.c
if a namespace is not available in the kernel, just ignore the error
and do not try to join it.
It solves an issue when running on a kernel that doesn't have the
cgroupns.
Closes: https://github.com/containers/crun/issues/218
=> linux: fix exec if a namespace is not available

src/libcrun/linux.c
these errors do not have a related errno code.  So don't append the
errno error.
=> linux: fix errors without errno

src/libcrun/linux.c
commit afeb06543e3c4846129d2039d61dede4f82e1db0 introduced the
regression.
=> linux: fix cgroup v1 mount with relative paths

src/libcrun/cgroup.c
since crun is converting the OCI configuration from cgroup v1, handle
the memory swap limit in the same way as it would behave when running
on cgroup v1.
The memory.memsw.limit_in_bytes file on cgroup v1 accounts for
SWAP+MEMORY used, while memory.swap.max accounts only for SWAP.
=> cgroup: handle swap limit as cgroup v1

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h
when a new network namespace is created, bring the "lo" device up.
Closes: https://github.com/containers/crun/issues/237
=> linux: bring network device up

src/create.c, src/run.c
if the specified bundle directory is a relative path, use realpath(3)
on it since the rest of the code assumes it is absolute.
Closes: https://github.com/containers/crun/issues/241
=> crun: make sure the bundle directory is absolute

src/libcrun/linux.c
When using podman on s390 (and, presumably, cris), the following error
occurs:
writing file '/proc/{}/gid_map': Operation not permitted
The root cause is that the order of clone syscall arguments is wrong: on
s390 and cris they are reversed (see "C library/kernel differences"
section of `man 2 clone`), but crun uses the same order for all
architectures. The end result is that the container process is created
with stack == CLONE_NEWUSER and flags == 0, causing it to inherit its
parent's user namespace (which prevents writes to gid_map) and to almost
immediately segfault.
Fix by special-casing clone call sequence for s390 and cris.
See also: https://github.com/containers/libpod/commit/ca5114faf928
Edit: added ifdef cris and a link to the similar libpod commit.
Edit 2: fixed style.
=> linux: fix the order of clone syscall arguments on s390

NEWS, src/libcrun/cgroup.c
Closes: https://github.com/containers/crun/issues/247
=> cgroup: drop warning for rootless

src/libcrun/linux.c
do not require read permissions on the root directory.  It is enough
to use a O_PATH file descriptor.
Closes: https://github.com/containers/crun/issues/249
=> linux: do not require read permissions on /

src/libcrun/container.c
if the umask is not set in the config.json file, then default to 0022
that it is what runc uses.
Closes: https://github.com/containers/crun/issues/260
=> linux: set default umask to 0022

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/status.c
do not try to use the parent directory.
Closes: https://github.com/containers/crun/issues/262
=> linux: use the correct path for notify socket

crun.1.md, src/libcrun/cgroup.c, src/libcrun/linux.c
=> linux: add support for TIME namespace

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h
This is in preparation for the crun checkpoint/restore support.
Checkpointing a container with CRIU fails if the containers stdin,
stdout and stderr has been redirected to /dev/null, but /dev/null still
points to the device outside of the container. With this change stdin,
stdout and stderr will be pointing to /dev/null on the inside of the
container.
With this change it is possible to checkpoint a crun container.
Also see #71
=> linux: re-open /dev/null inside of the container

src/libcrun/container.c, src/libcrun/linux.c
=> libcrun: always use setsid

Makefile.am, configure.ac, src/checkpoint.c, src/checkpoint.h, src/crun.c, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/criu.c, src/libcrun/criu.h, src/libcrun/linux.c, src/libcrun/linux.h
See also #71 
As discussed in #71 this brings initial checkpoint support to crun. This does not yet support restoring of containers to be able to review code in smaller chunks.
The checkpoint sub-command is also called `_checkpoint` as Podman's checkpoint/restore support detection relies on `checkpoint` returning successfully. As long as not all feature necessary for Podman are implemented the `checkpoint` and `restore` command will not be available.
I will also add tests to this PR, but wanted to get it out for an initial review. Mainly to make sure I put the new code in the right places.
For testing I am currently running on Fedora 31 and running a RHEL 7 container on it:
```
NAME        PID       STATUS   BUNDLE PATH                            
rhel7-httpd 38124     running …
```
=> Initial checkpoint support (no restore yet)

src/libcrun/cgroup.c, src/libcrun/linux.c
fix some issues found while running the CRI-O integration tests on cgroupv2 using the cgroupfs backend.
Test PR: https://github.com/cri-o/cri-o/pull/3292
=> cgroup: fix a few issues found while running CRI-O integration tests

NEWS, src/libcrun/linux.c
cgroup v1: mount only subpath
fix a regression introduced by 0.12.2
=> tag 0.12.2.1

src/libcrun/criu.c
As mentioned in the #269 this contains a small fix for bind mount detection as well as some tab-spaces replacement for indentation and rename of a define for the upcoming container restore support.
=> Minimal fixes for checkpointing

.travis.yml, Makefile.am, src/crun.c, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/criu.c, src/libcrun/criu.h, src/libcrun/linux.c, src/libcrun/linux.h, src/restore.c, src/restore.h, tests/test_checkpoint_restore.py, tests/tests_utils.py
This is a minimal implementation of container restore. The biggest missing pieces are user namespace support and input/output handling. Besides many other missing things it does work for simple test containers as it can be seen in the included simple test for checkpoint/restore.
The test is skipped if the crun binary has not been built with CRIU support.
=> Minimal container restore implementation

src/libcrun/ebpf.c
load the full 32 bits word and take the lower 16 bits, instead of
reading just 16 bits.
=> ebpf: fix endianess issue on s390x

src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c
add support for systemd properties passed through annotations in the
form:
"annotations": {
"org.systemd.property.TimeoutStopUSec": "uint64 123456789",
"org.systemd.property.CollectMode":"'inactive-or-failed'"
}
add a basic parser for the gvariant types to avoid a dependency on
glib.  The parser doesn't support complex types but it is just enough
for the types accepted by systemd.
Similar to https://github.com/opencontainers/runc/pull/2224
=> cgroup: support systemd properties via annotations

src/libcrun/container.c, src/libcrun/linux.c
instead use the configuration file.
Closes: https://github.com/containers/crun/issues/282
=> exec: do not inherit env variables from main pid

src/libcrun/criu.c
When a path to a regular file is masked, crun will create a bind mount to `/dev/null`. The changes in this commit provide information about such external bind mounts to CRIU, which is needed for checkpoint/restore.
=> criu: Add masked paths to external mount map

src/libcrun/cgroup.c
use the struct definition from libocispec so the two don't get out of
sync.
It caused to write the wrong values to the io controller.
=> cgroup: use struct definition from libocispec

src/libcrun/cgroup.c
it can be configured via an annotation.
This reverts commit a5841de12b449d8441948cbf9af8133cac5287ee.
=> Revert "systemd: set collectmode=inactive-or-failed"

src/libcrun/linux.c, src/libcrun/linux.h
allow to set sysctl directly from the OCI runtime configuration.
=> linux: add function libcrun_set_sysctl_from_schema

src/libcrun/utils.c
Fix checking if a file is under the rootfs and allow to bind mount on
not writeable paths.  If the open(O_CREAT) fails, then attempt to open
the file in O_PATH mode.
commit 8e580bcb332a3dea7ef910ee297d1f595540b869 introduced the
regression.
Closes: https://github.com/containers/crun/issues/290
=> utils: fix mount on not writeable path

src/libcrun/linux.c
at least the linux kernel 4.18 used by RHEL/CentOS 8.1 complains when
the selinux label is specified on the remount to read only.  Drop the
label when doing a remount.
Closes: https://github.com/containers/crun/issues/291
=> linux: drop label for remount

src/libcrun/cgroup.c
the pid controller is not available on kernels older than 4.3.
Closes: https://github.com/containers/crun/issues/294
=> cgroup: use the memory controller to ready PIDs

.travis.yml, src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c
it is not part of the OCI specs but it is what users of runc expect,
so add a "paused" state that is used when the container cgroup is
freezed.
=> state: report state 'paused'

cfg.mk, src/libcrun/status.c, src/libcrun/status.h
In this PR is introduced a `process-start-time` status value for containers. This value, in addition to the PID value, is used to identify a container process.
This is analogous to the `init_process_start` state parameter used by runc.
=> status: Use process start time for identification

crun.1.md, src/create.c, src/run.c
add a new option to create/run to override the default config.json
value.
Closes: https://github.com/containers/crun/issues/308
=> crun: allow to override config file name

Makefile.am, contrib/static-builder-x86_64/Dockerfile, src/libcrun/signals.c, src/libcrun/signals.perf
upstream version of libsseccomp needs gperf as dependency.
=> contrib, static-builder: install gperf

crun.1.md, src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/status.c, src/libcrun/status.h
systemd delegation works only for sub groups, so make sure the container is created in a sub group where we have full control without stepping on systemd management.
=> cgroup: create container under subcgroup

src/checkpoint.c, src/libcrun/cgroup.c, src/libcrun/container.c, src/libcrun/criu.c, src/libcrun/linux.c, src/libcrun/seccomp.c, src/libcrun/status.c, src/restore.c
Motivated by seeing this error:
> cannot set kernel memory with cgroupv2: File exists
in which `EEXIST` is from some other operation.
This patchset:
- removes error checks after xasprintf
- removes double wrapping of errors 
- removes `errno` where it's not appropriate to use it
- adds `errno` where it's appropriate
- adds `-ret` as `errno` for calls that return `-errno`
(that is, most of `sd_*()` and `seccomp_*()` calls)
While at it, remove a few lines of unreachable code.    
:warning: All this needs a careful review.
=> libcrun: audit errno in crun_make_error calls

src/libcrun/cgroup.c
on cgroup v2, raise an error if the swap limit is set without also setting the memory limit.
Closes: https://github.com/containers/crun/issues/315
=> cgroup, v2: raise error if swap is set without memory limit

src/libcrun/linux.c
skip setting a context= option when mounting cgroup.  At least Linux
5.6 fails with EINVAL if it set.
=> linux: do not mount label cgroup

src/libcrun/linux.c, src/libcrun/utils.c, src/libcrun/utils.h
use the openat2 syscall (requires Linux >= 5.6) to perform open
relative to a dirfd.
=> libcrun: use openat2 where supported

src/libcrun/container.c, src/libcrun/criu.c, src/restore.c, tests/test_checkpoint_restore.py
The still hidden "_checkpoint" and "_restore" commands were not yet tested with Podman.
With the changes in this PR I am able to use checkpoint/restore from Podman with crun.
The restored container is not yet running in the correct network namespace, but the container is restored and Podman sees it as running. It almost seems to work now in combination with Podman.
The one thing missing for Podman using crun for checkpoint/restore is crun telling CRIU to restore the container into the network namespace created by Podman/CNI.
This continues #71 to fully support checkpoint/restore in crun.
=> Adapt crun to work with Podman's checkpoint/restore expectations

src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/linux.c
we cannot directly use the target directory as it is relative to the
rootfs.
=> cgroup: use rootfd for creating symlinks

src/libcrun/criu.c, src/libcrun/linux.c, src/libcrun/linux.h
CRIU can checkpoint and restore all namespaces. For the network namespace either special steps are needed to re-connect the network devices like veth back into the network namespace or, like when being driven by Podman, the network namespace if configured externally.
For checkpoint/restore with Podman we are telling CRIU to not checkpoint the network namespace settings and on restore we tell CRIU to use the network namespace provided by Podman/CNI by looking at config.json if the network namespace is defined by a 'path'.
With this the restored container will be running in the given network namespace.
With this Podman can checkpoint and restore a container on Fedora 31 using crun.
stdin and stdout are not yet correctly reconnected after restore, so a few more, hopefully small, changes are …
=> criu: tell CRIU to not touch the network namespace

src/libcrun/utils.c
otherwise it's hard to see what exactly is failing
Signed-off-by: Peter Hunt <pehunt@redhat.com>
=> utils: differentiate errors for write_file{,at}

src/libcrun/cgroup.c, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/status.c, src/libcrun/utils.c, src/libcrun/utils.h
commit 95b6f8ac8eefeb8145e7e9163f267f18b596555e introduced a
regression where symlinks inside of the path resolution are not
resolved.
=> libcrun: fix path resolution with symlinks

src/libcrun/cgroup.c
if the write to the memory limit fails with EINVAL, try to reverse the
order the two files are written.
Closes: https://github.com/containers/crun/issues/326
=> cgroup: reverse write to swap/memory on EINVAL

contrib/terminal-receiver/terminal-receiver.c, src/exec.c, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/seccomp.c, src/libcrun/utils.c, src/libcrun/utils.h, tests/init.c
1. Use C99-style zero init (` = {};`) instead of memset where appropriate.
2. Introduce and use `xmalloc0` which is xmalloc + bzero
=> memset nits

src/libcrun/cgroup.c
While playing with Fedora 31 host with old/broken selinux packages,
I found out that systemd fails to create a transient unit. Here is
an except from journalctl:
> audit[1]: AVC avc:  denied  { setsched } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0
> systemd[1]: crun-555.scope: Failed to add PIDs to scope's control group: Permission denied
> systemd[1]: crun-555.scope: Failed with result 'resources'.
> systemd[1]: Failed to start libcrun container.
and yet crun did not show any error and proceeded to start the
container, which lead to a number of issues.
1. Since the cgroup was not created by systemd,
but the error was not detected, the container process was put
into the wrong …
=> cgroup: check systemd unit creation/removal succeeded

src/libcrun/container.c, src/libcrun/criu.c, src/libcrun/linux.c, src/libcrun/linux.h, src/libcrun/status.c, src/libcrun/status.h
With this I am able to use Podman with crun to checkpoint and restore containers.
The checkpoint and restore commands are still hidden in crun and prefixed using '_'.
One smaller problem, easy to fix, is that crun (just like runc) creates a few directories implicitly on container creation (like `/run`). I need to create these directories also during restore. This makes it impossible to currently migrate a container where `/run` is not part of the container image as CRIU fails remounting `/run/.containerenv` (for example) because `/run` does not exist.
The bigger problem I am seeing is related to CRIU's incomplete cgroup2 support. I think.
One of my test containers is using Java and after restore the JVM is running on 100% CPU usage all the time, because, I think, the JVM does not …
=> crun checkpoint/restore support (almost ready for Podman)

tests/podman/Dockerfile
tests on master are broken at the moment, so let's use v1.9 for now.
=> tests: use podman v1.9 instead of master

src/libcrun/container.c
do not write twice the error message when -d is used.
Closes: https://github.com/containers/crun/issues/335
=> container: do not write twice the error msg

src/libcrun/seccomp.c
Fixes the following errors:
> src/libcrun/seccomp.c: In function 'syscall_seccomp':
> src/libcrun/seccomp.c:55:25: error: '__NR_seccomp' undeclared (first use in this function)
>    return (int) syscall (__NR_seccomp, operation, flags, args);
>                          ^
> src/libcrun/seccomp.c:55:25: note: each undeclared identifier is reported only once for each function it appears in
> src/libcrun/seccomp.c: In function 'libcrun_apply_seccomp':
> src/libcrun/seccomp.c:142:24: error: 'SECCOMP_FILTER_FLAG_TSYNC' undeclared (first use in this function)
>                flags |= SECCOMP_FILTER_FLAG_TSYNC;
>                         ^
> src/libcrun/seccomp.c:159:26: error: 'SECCOMP_SET_MODE_FILTER' undeclared (first use in this function)
>    ret = syscall_seccomp (SECCOMP_SET_MODE_FILTER, …
=> seccomp.c: define seccomp macros when not already defined

src/libcrun/utils.c
=> utils: use calloc instead of malloc+memset

src/libcrun/criu.c
reported by gcc:
src/libcrun/criu.c:288:23: warning: comparison of integer expressions
of different signedness: 'int' and 'size_t' {aka 'long unsigned
int'} [-Wsign-compare]
288 |         for (i = 0; i < len; ++i)
=> criu: fix different signedness comparison

src/libcrun/criu.c
If restoring a container from an unmodified root file-system certain mountpoints have to be re-created during restore. This happens when using Podman to restore from an exported checkpoint.
In the case of 'podman container checkpoint -l', the checkpointed container is not destroyed and the root file-system is kept.
If restoring from an exported checkpoint using 'podman container restore --import=export.tar.gz' the root file-system is re-created and certain mountpoints will be missing. A good example is
'/run/.containerenv'. Usually no container has the mountpoint for '/run/.containerenv' so crun creates the mountpoint and bind mounts something on top of it as described in config.json when the container is created.
During restore this mountpoint has to be created just as during initial …
=> Recreate mountpoints during restore

src/libcrun/cgroup.c
if the scope already exists, do not fail with an error.
=> cgroup: use systemd scope if it already exists

src/libcrun/cgroup.c
discovered while using the latest libocispec from master
=> libcrun: fix OOM check on cgroupv2

.github/workflows/release.yaml, crun.1.md, src/libcrun/container.c, src/libcrun/utils.c, src/libcrun/utils.h
support two custom annotations "run.oci.hooks.stdout" and "run.oci.hooks.stderr" that allow to specify the output for hook processes.
When the annotations are specified, the value is used as destination file for the hooks stdout and stderr.
The file is open in append mode and it is created if it doesn't exist.
Closes: https://github.com/containers/crun/issues/353
=> container: allow hooks output to file

Makefile.am, configure.ac
For openSUSE 15.1, `seccomp.h` is located as `/usr/include/libseccomp/seccomp.h` which could be fetched by `pkg-config --libs libseccomp` and `pkg-config --cflags libseccomp`.
This patch reference from https://build.opensuse.org/package/view_file/openSUSE:Factory/lxc/configure-find-seccomp-using-pkg-config.patch?rev=45, so inject the `pkg-config` result on-the-fly.
Fixes #358
=>  [openSUSE 15.1] Missing libseccomp headers

README.md
Provide additional installation options by using Ansible with https://github.com/alvistack/ansible-role-crun from source code.
Fixes #362
=> Add Installation Guide with Ansible

Makefile.am, configure.ac
We do not use pkg-config any more for libseccomp to ensure less complex
build scenarios.
This reverts commit 3310cd26e3c40ad3c759d953d31de19468ca0d5e.
Ref https://github.com/containers/crun/pull/366
=> Revert " [openSUSE 15.1] Missing libseccomp headers"

src/libcrun/linux.c
the remount owns the fd, so dup it.
=> linux: fix double close

crun.1.md, src/libcrun/cgroup.c, src/libcrun/linux.c
add a custom annotation run.oci.systemd.force_cgroup_v1=/PATH that
allows to mount a none,name=systemd hierarchy on cgroup v2.
If specified, the container won't have any other controller mounted,
but only a named hierarchy name=systemd.  On a system using cgroup v2,
it is useful to run containers based on old versions of systemd that
lack cgroup v2 support.  It doesn't support rootless containers.
Usage with Podman:
podman run --annotation=run.oci.systemd.force_cgroup_v1=/sys/fs/cgroup \
--rm -ti centos:7 /usr/lib/systemd/systemd
=> cgroup: support mounting name=systemd on cgroup v2

src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/linux.c
if we cannot join the initial container cgroup, then attempt to join
the initial container process cgroup.
=> cgroup2: try joining initial process cgroup

src/libcrun/container.c
do not print a warning when crun is compiled without fgetpwent_r
support and it cannot detect the user home directory.
=> libcrun: skip print warning without fgetpwent_r

src/libcrun/status.c, src/libcrun/utils.c, src/libcrun/utils.h
use the libyajl library to write the JSON status file instead of
directly writing it.
=> status: use yajl to write the status file

src/libcrun/cgroup.c
Docker sets the value to 0 when the setting is not specified.
partially revert 65f93d4203442b4707981c8c4f0a82ad9032704f
Closes: https://github.com/containers/crun/issues/383
=> cgroup: ignore cpu resources if set to 0

nix/default.nix, nix/nixpkgs.json
Using `crun.overrideAttrs` may result as broken due to nixpkgs upstream changes; replace with native `stdenv.mkDerivation` with complete definition could simply avoid this happening.
Changes based on https://github.com/NixOS/nixpkgs/blob/e469b77/pkgs/applications/virtualization/crun/default.nix; also fix `crun --version` with correct version and commit, e.g.
```
crun version 0.13.1-5077
commit: 50777c63f2b44f2426b81e20bb9876a9349cdeb6
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
```
Fixes #380
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>
=> [nix] Use `stdenv.mkDerivation` instead of `crun.overrideAttrs`

src/libcrun/container.c, src/libcrun/utils.c
On non-glibc systems crun struggles to set the HOME environment
variable, which can lead to application failures, specifcally Git inside
of CI systems. This change defines fgetpwnent_r on systems that need it,
and will set HOME to / in the event that all other options failed.
=> Define fgetpwent_r if it does not exist

src/libcrun/container.c
move the check for what AppArmor label must be used before
initializing AppArmor.
Closes: https://github.com/containers/crun/issues/371
=> exec: fix exec without an AppArmor label

.lgtm.yml, src/libcrun/ebpf.c
on a container update, make sure the existing eBPF program is
completely replaced.
=> ebpf: replace the existing program on update

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, tests/test_uid_gid.py
if the config file does't specify any, make sure to drop any
additional group.
Closes: https://github.com/containers/crun/issues/394
=> exec: drop additional groups if not specified

configure.ac, src/libcrun/linux.c
To do so, we need first to attempt joining the namespace, once that is done, the mque and proc file system are mounted using fsmount and then the user namespace is created.  The reference to the  namespaces is injected into the container.
Requires Linux 5.3+.
Closes: https://github.com/containers/crun/issues/396
=> linux: handle join of a different pid/ipc namespace

README.md, src/libcrun/cgroup.c
=> crun: fix return code check for cgroupfs

configure.ac, src/libcrun/container.c, src/libcrun/ebpf.c, src/libcrun/linux.c, src/libcrun/linux.h
follow up for #400 
noteworthy: all the errors happening in the init phase are sent through the sync pipe so they can be properly handled by the caller in the initial process.
=> create: code cleanup

src/libcrun/container.c
when using post_start hooks, make sure the stdout/stderr file
descriptors point to the end of the file.
Closes: https://github.com/containers/crun/issues/410
=> container: seek stdout/stderr before running container

contrib/notify-socket-server/Makefile, contrib/notify-socket-server/notify-socket-server.c, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, tests/test_start.py
=> linux: honor mount-label for the notify socket

src/libcrun/cgroup.c, src/libcrun/container.c, src/libcrun/status.c
fix some race conditions where crun would fail if the process already
exited.
Closes: https://github.com/containers/crun/issues/422
=> status: do not fail delete if the process exited

src/libcrun/utils.c, tests/test_mounts.py, tests/tests_utils.py
while iterating a path to create the missing parent directories, there
is no need to use openat2 as it is possible to use directly O_NOFOLLOW.
The path is anyway opened with openat2 where possible later on in the
same function.
Closes: https://github.com/containers/crun/issues/426
=> linux: drop usage of openat2 for creating directory

Makefile.am, configure.ac, tests/Makefile.tests, tests/test_capabilities.py, tests/test_checkpoint_restore.py, tests/test_cwd.py, tests/test_detach.py, tests/test_devices.py, tests/test_exec.py, tests/test_hooks.py, tests/test_hostname.py, tests/test_limits.py, tests/test_mounts.py, tests/test_paths.py, tests/test_pid.py, tests/test_pid_file.py, tests/test_preserve_fds.py, tests/test_resources.py, tests/test_rlimits.py, tests/test_start.py, tests/test_tty.py, tests/test_uid_gid.py, tests/test_update.py, tests/tests_utils.py
- Makefile.am : add Makefile.tests and test_runner.sh to
EXTRA_DIST, so we'll get them in the tarball, so we
can ship them in the crun-tests rpm.
- configure.ac - fix weird error-message condition. TL;DR
is that a comma in AC_MSG_NOTICE is interpreted as "the
first arg is the message, the second is an output file"(?),
the end result being that if gperf is not found, a file
named "cannot" is created in $CWD with partial error
message output. This was a fun one to track down.
- tests/*.py : explicitly specify 'python3' in env line,
not $PYTHON. The latter leads to rpmbuild creating a
-tests rpm with 'Requires: /usr/bin/$PYTHON' (yes,
dollar-python) which leads to an uninstallable rpm.
- tests/Makefile.tests : in 'check' target, depend on $(INIT),
not explicit 'init'. In packaged crun-tests …
=> Various packaging and configure fixes

src/restore.c
When `--bundle` is not specified crun defaults to the current working directory (`.`), however, the path should be absolute and this is not the case container restore fails with:
```
Error (criu/mount.c:2527): mnt: Unable to mount ./criu-root /tmp/.criu.mntns.VvuAE8/13-0000000000/ (id=771): No such file or directory
```
=> criu: Use absolute bundle path

src/libcrun/cgroup.c
when running in unified mode, ignore any other controller if present
since it is anyway not supported.
Fix an issue where a cgroup v1 controller is mounted onto another
directory different than /sys/fs/cgroup and crun creates automatically
the directory /sys/fs/cgroup/$CONTROLLER.
=> cgroup2: ignore other controllers if found

Makefile.am
this target doesn't work any more
$ make oci-runtime-validation
RUNTIME=/home/lizj/workspace/NARI/crun/crun tests/oci-runtime-validation
/bin/bash: tests/oci-runtime-validation: No such file or directory
Makefile:2429: recipe for target 'oci-runtime-validation' failed
make: *** [oci-runtime-validation] Error 127
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
=> Makefile.am: remove deprecated target oci-runtime-validation

.github/workflows/release.yaml, nix/default.nix, nix/nixpkgs.json
Partly rollback #448
The changes of `src = ./..;` make local build with `nix build -f nix/` failed. This PR partly rollback from #448.
Also update nix pin with `make nixpkgs`, see
- https://github.com/containers/crun/pull/450
- https://github.com/containers/conmon/pull/189
- https://github.com/containers/skopeo/pull/973
- https://github.com/containers/buildah/pull/2533
- https://github.com/containers/podman/pull/7286
- https://github.com/cri-o/cri-o/pull/4065
```release-note
Update nix pin with `make `nixpkgs`
```
=> Partly rollback #448

src/create.c, src/crun.c, src/libcrun/container.c, src/libcrun/container.h, src/run.c, tests/test_start.py, tests/tests_utils.py
allow to declare the path to the config.json, instead of using
the config.json in the bundle directory.
=> crun: allow to declare path to config file

src/libcrun/container.c
fix leak of `gen` and `status` on errors.
It is not an issue for crun, but it could potentially be an issue for an application linking libcrun that incurs in these leaks multiple times.
=> libcrun: fix two potential leaks

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, src/libcrun/status.c, src/libcrun/status.h
if pidfd_send_signal is available, use it instead of kill for terminating the container.
It gives the benefit we can check whether the PID is still the container pid and not being vulnerable to TOCTOU checks for sending the signal.
Requires linux 5.3.
=> kill: use pidfd_send_signal if supported

src/list.c
Add format option to `crun list` to have an option of printing list of containers out as a json array.
=> list: add json format option

Makefile.am, cfg.mk, configure.ac, contrib/seccomp-notify-plugin-example/Makefile, contrib/seccomp-notify-plugin-example/full.c, contrib/seccomp-notify-plugin-rust/Cargo.toml, contrib/seccomp-notify-plugin-rust/src/mknod.rs, contrib/seccomp-notify-plugin-rust/src/seccompwatcher.rs, crun.1, crun.1.md, src/libcrun/container.c, src/libcrun/seccomp.c, src/libcrun/seccomp.h, src/libcrun/seccomp_notify.c, src/libcrun/seccomp_notify.h, src/libcrun/seccomp_notify_plugin.h
=> seccomp: support seccomp listener

src/libcrun/seccomp.c
This seccomp action has been added to libseccomp a while ago, so I guess we can support it in crun as well:
https://github.com/seccomp/libseccomp/commit/b2f15f3d02f302b12b9d1a37d83521e6f9e08841
=> Add support for SCMP_ACT_KILL_THREAD

src/libcrun/container.c
by the time crun attempts to read from the cgroup, systemd might have
already cleaned it up.  When using systemd, on ENOENT state reports
the container as "stopped" instead of an error.
Closes: https://github.com/containers/podman/issues/7148
=> state: fix race condition when reading cgroup

src/checkpoint.c, src/libcrun/status.c, src/restore.c
simplify parsing of /proc/PID/stat to read only the information used
by libcrun.
=> status: simplify /proc/PID/stat parsing

README.md
Hello I have made a small change to the README so those less familiar with autotools can more easily install libcrun without needing to opening issues like https://github.com/containers/crun/issues/477
=> Update README With Shared Library Installation Instructions

src/libcrun/container.c, src/libcrun/utils.c
Unless I'm missing something obvious, these has no effect other
than calling close(-1) upon return which does not make sense.
=> src/libcrun: rm unused vars

src/libcrun/container.c
Related issues:
* https://github.com/moby/moby/pull/37404
* https://github.com/moby/moby/pull/38299
* https://github.com/moby/moby/pull/36368
* https://github.com/moby/moby/pull/35399
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>
=> libcrun: update masked and readonly paths of /proc

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h
Determine the kernel capability set at run time, for
consistency with runc.
Signed-off-by: Ed Santiago <santiago@redhat.com>
=> Capabilities: get last_cap dynamically

src/libcrun/cgroup.c
=> cgroup: enable all controllers in the root

build-aux/release.sh, nix/default.nix
From https://github.com/NixOS/nixpkgs/search?q=enableSystemd, in nix style most packages are using `enableSystemd` instead of `disableSystemd`.
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>
=> nix build --file nix/ --arg enableSystemd false

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/status.c, tests/init.c, tests/test_checkpoint_restore.py
fix a potential race condition when writing the pid to the sync socket as the child process also uses the same socket.  Now the child process waits until the grand-parent received the pid.
=> linux: fix a race condition writing to the socket

src/crun.c, src/libcrun/error.c
Closes: https://github.com/containers/crun/issues/496
=> libcrun: set default verbosity to ERROR

src/libcrun/container.c, src/libcrun/utils.c, src/libcrun/utils.h
Closes: https://github.com/containers/crun/issues/504
=> container: truncate pid file before writing it

src/libcrun/container.c
when reading from the exec sync pipe, make sure it reads exactly one
byte otherwise return an error.
Closes: https://github.com/containers/crun/issues/511
=> exec: check read bytes from sync

configure.ac, crun.1, crun.1.md, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/linux.c
add a custom annotation to specify whether the container must be
executed using libkrun.
crun must be configured and compiled with `--with-libkrun`.
example usage:
```
$ podman run -v /dev/kvm:/dev/kvm  --annotation run.oci.handler=krun --rm fedora echo hello
hello
```
=> container: add support for libkrun

README.md
... and add `$` / `#` / `sudo` appropriately.
Surely there's a fine line between `shell` and `console`, but I feel the latter is more appropriate here. For one thing, lines started with `#` are no longer typeset as comments.
=> README.md: use console syntax hl for cli examples

src/libcrun/cgroup.c, src/libcrun/linux.c, src/libcrun/utils.c
make sure the container has a cgroup, otherwise return a better error message.
=> pause, resume: check for cgroup before using it

src/libcrun/linux.c
use the ENOSYS errno value when the syscall is not present.
Closes: https://github.com/containers/crun/issues/519
=> linux: use ENOSYS for unknown syscall

README.md
* Ubuntu needs `apt-get update` or else pkgconf and go-md2man will
not be available
* libtool is defined twice in the Centos install instruction
Signed-off-by: yihuaf <yihuaf@unkies.org>
=> minor updates to readme dependencies section

src/libcrun/linux.c
Reported here: https://github.com/cri-o/cri-o/pull/4293
=> linux: label the cgroup v1 tmpfs

src/libcrun/container.c, src/libcrun/seccomp_notify.c
ioctl (fd, SECCOMP_IOCTL_NOTIF_RECV, &req) returns ENOENT if the
syscall was aborted by the time the seccomp fd was signaled to be
ready.
Also, make the seccomp fd not blocking.
=> seccomp: ignore ENOENT

configure.ac, src/crun.c, src/libcrun/container.h, src/libcrun/criu.c, src/restore.c
This pull requests adds the missing pieces of crun checkpoint/restore and enables it.
Missing pieces were, from my point of view, to make Podman's checkpoint/restore tests successful. With this Podman's checkpoint restore finishes successfully:
```
...
Ran 16 of 1076 Specs in 63.152 seconds
SUCCESS! -- 16 Passed | 0 Failed | 0 Pending | 1060 Skipped
PASS
```
The changes in this PR to enable this are:
* Require at least CRIU 3.15, currently unreleased - using criu-dev branch for my tests
* Correctly reconnect console socket after restore - this requires 3.15
* Use cgroup freezer to stop all processes in the container instead of ptrace - this requires 3.15
* Activate the `checkpoint` and `restore` command which were hidden and prefixed with `_` 
(as long as CRIU >= 3.15 is not detected …
=> Enable checkpoint/restore support (finally)

.travis.yml, tests/test_checkpoint_restore.py
Now that crun supports 'checkpoint' and 'restore' instead of '_checkpoint' and '_restore', the tests also need to be adapted.
Also run the test in Travis using sudo to actually test it in CI.
=> Adapt checkpoint/restore test

src/libcrun/criu.c, tests/test_checkpoint_restore.py
Unfortunately I never tested the checkpoint/restore support with cgroup v1 system to detect that it was not working.
CRIU must be told how to mount each cgroup v1 controller/folder from which location back into the container. With v2 it is all happening automatically as it is just a single mount.
This adds cgroup v1 support to crun's checkpoint/restore implementation and also makes sure tests are running with a mounted cgroup in the container.
Fixes: #538
=> Fix checkpoint/restore with cgroup v1

src/libcrun/container.c
if the cgroup is deleted between the open("cgroup.freeze") and the
read(2), the read fails with ENODEV.  In this case, ignore the error
and report it as "stopped".
Enable the same logic also for the cgroupfs driver.
Closes: https://github.com/containers/crun/issues/537
=> container: fix another race reading cgroup freeze

src/libcrun/linux.c
ignore the error when the mount fails with ENOENT, as the controller
might have been unmounted.
Closes: https://github.com/containers/crun/issues/540
=> linux: ignore ENOENT for cgroup v1 mounts

src/libcrun/utils.c
systemd-nspawn explictly blocks openat2 by default, relying on
implementations to fall back to older, openat code. However, it does
that by setting up a seccomp rule that returns EPERM, which libcrun is
treating as an error and thus not falling back.
Add EPERM to the list of ENOSYS/EINVAL for which openat2 errors are
ignored, and the openat fallback is attempted.
Closes: https://github.com/containers/crun/issues/545
Signed-off-by: Faidon Liambotis <paravoid@debian.org>
=> libcrun: fallback to openat if openat2 returns EPERM

crun.1, crun.1.md, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/linux.c, src/libcrun/linux.h
Create an intermediate user namespace if there is a single id mapped inside of the container user namespace and the container is configured to not run as root in the user namespace.
With such configuration, crun automatically creates a new user namespace where the desired UID/GID is mapped to root in the
intermediate user namespace used to configure the container.
This enables running with an UID/GID different than root when a rootless user has no access to multiple IDs:
$ podman run --rm --user 1000:1000 --uidmap 0:0:1 fedora:33 id
uid=1000(1000) gid=1000(1000) groups=1000(1000)
One limitation in the current implementation is that some namespaces, like pidns are not owned by the final user namespace.
Idea copied from bubblewrap.
=> linux: allow arbitrary IDs with single ID userns

src/libcrun/linux.c, tests/containerd/Dockerfile
set the UID/GID used the initial configuration to the final UID/GID used in the container when root is not available in the container user namespace.
Such configuration can happen for example when a single mapping is used for rootless containers and it is mapped to the final UID/GID used in the container.
=> linux, init: allow mappings without root

Makefile.am, nix/default.nix, nix/nixpkgs.json
Regular monthly update; BTW, it is now failing as below:
```
$ nix build -f nix/
waiting for locks or build slots...
builder for '/nix/store/xv4pk3h76fzc7hzan3kkh3wizqv7mah6-gts-0.7.6.drv' failed with exit code 2; last 10 log lines:
/nix/store/cqxfi2q7d7k6y0q91wcx2cbkj4xsak63-binutils-2.31.1/bin/ld: ../src/.libs/libgts.so: undefined reference to `pthread_create'
/nix/store/cqxfi2q7d7k6y0q91wcx2cbkj4xsak63-binutils-2.31.1/bin/ld: ../src/.libs/libgts.so: undefined reference to `pthread_mutexattr_init'
/nix/store/cqxfi2q7d7k6y0q91wcx2cbkj4xsak63-binutils-2.31.1/bin/ld: ../src/.libs/libgts.so: undefined reference to `pthread_mutexattr_destroy'
/nix/store/cqxfi2q7d7k6y0q91wcx2cbkj4xsak63-binutils-2.31.1/bin/ld: ../src/.libs/libgts.so: undefined reference to `pthread_rwlock_tryrdlock'
collect2: …
```
=> Update nix pin with `make nixpkgs`

src/libcrun/container.c, src/libcrun/utils.c, src/libcrun/utils.h
otherwise the seccomp profile could block some of the syscalls involved.
=> exec: move close_fds before applying seccomp

src/libcrun/cgroup.c, src/libcrun/container.c, src/libcrun/criu.c, src/libcrun/linux.c, src/libcrun/status.c, src/libcrun/utils.c, src/libcrun/utils.h, tests/tests_libcrun_utils.c
it enables appending path components and taking care of dropping additional slashes between them.
=> libcrun: add function append_paths

src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c, src/libcrun/criu.c, src/libcrun/linux.c
moved some patches from https://github.com/containers/crun/pull/566 here
=> cgroup: move update_cgroup_resources to cgroup_enter

src/libcrun/linux.c, src/libcrun/utils.c
it causes issues with hooks that run in the container PID namespace instead of the runtime namespace.
revert 54b8ed3f54a98f869baf15167767b7a4c8622c2f
=> linux: drop optimization to avoid fork

src/libcrun/linux.c, tests/podman/run-tests.sh, tests/test_resources.py
follow-up to https://github.com/containers/crun/pull/569
if the container is joining an existing pid namespace, make sure to fork the process first as it could cause hooks to run in the target pidns.
=> linux: clone before setns(CLONE_NEWPID|CLONE_NEWTIME)

src/libcrun/cgroup.c, tests/test_resources.py
when running in a user namespace, make sure to honor the cgroup
limits.
fix a regression caused by 3e2b3f224561e1845a95183d7f34247e965ccb8c
=> cgroup: fix regression when setting limits

src/libcrun/linux.c
commit 4bbd118329fe33f20e29881609647780e2a428f8 introduced this
regression.
Closes: https://github.com/containers/crun/issues/576
=> linux: fix build without CLONE_NEWCGROUP

crun.1, crun.1.md, src/libcrun/cgroup.c
More details here: https://github.com/opencontainers/runc/pull/2786
=> cgroup: fix conversion from blkio to io

Makefile.am
Closes: https://github.com/containers/crun/issues/579
=> Makefile.am: crun depends on libocispec.la

crun.1, crun.1.md, src/libcrun/container.c, src/libcrun/utils.c, src/libcrun/utils.h
Add an annotation `run.oci.seccomp_bpf_file` to ignore the seccomp
section in the OCI configuration file and use the specified file as
the raw data to the `seccomp(SECCOMP_SET_MODE_FILTER)` syscall.
I am using this feature for some experiments
=> seccomp: custom annotation to load raw bpf

src/libcrun/container.c
If the libkrun library present in the system supports setting the
working directory, do it.
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> container: set working directory for libkrun

src/libcrun/linux.c, src/libcrun/utils.c
commit 99538d805bb62fbda6e82627d8daa0b90c97a8d0 introduced this
regression.
This issue happens only on old kernel that lack openat2.
The error happens with a command like:
$ podman run --rm -v /etc/localtime:/etc/localtime ubi8 echo "This works"
Error: open `..`: No such file or directory: OCI not found
We already have tests in place to detect this case, but they were
running on newer kernels so the code path was completely skipped.
=> utils: fix symlink lookup

src/libcrun/cgroup.c
enabling the cpu controller fails with EINVAL if there are already
realtime processes running on the system:
1516    1521  RR     99 rtkit-daemon
-bash: echo: write error: Invalid argument
=> cgroup: skip +cpu on EINVAL in cgroup root

src/libcrun/container.c, src/libcrun/container.h, src/libcrun/linux.c, tests/init.c, tests/test_start.py, tests/tests_utils.py
If $NOTIFY_SOCKET is set, then crun will create a proxy for this socket
in the crun state directory, and bind mount it into the container.
However, the bind mounting happens after switching to the user
namespace; if UID remapping means that the container does not in fact
have permission to read that socket, then the bind mount fails.
Because the container needs permission to read _every path component_
for the source of the bind mount, and the crun state directory /run/crun
is usually root-owned and mode 0700, this actually happens _always_ when
using containers without uid 0 mapped in.
This patch fixexs the issue by first running open_tree on the
/run/crun/<container>/notify directory in the original user namespace to
_create_ the bind mount, and only putting it in the container …
=> Fix permission error when using both user namespaces & NOTIFY_SOCKET

src/libcrun/linux.c
Closes: https://github.com/containers/crun/issues/594
=> linux: ignore ENOSYS on keyctl

src/libcrun/utils.c, tests/podman/run-tests.sh, tests/test_start.py
if there is no HOME env variable set and the user is not found, then
set the home directory to '/'.
=> utils: set HOME to root if the user not found

.github/workflows/release.yaml, build-aux/release.sh, nix/default-arm64.nix, nix/nixpkgs.json
We now add a second arm64 nix derivation which is integrated in the
GitHub actions CI, too.
Fixes https://github.com/containers/crun/issues/478
=> Add arm64 static binary build

configure.ac, src/create.c, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/linux.c, src/libcrun/status.c, src/libcrun/utils.c, src/libcrun/utils.h, src/run.c
a bunch of cleanups and some improvements for the mounts logic.
Noteworthy, it removes the "temporary mount" logic as it doesn't really add any benefit.
=> linux: cleanup mounts logic

NEWS, src/libcrun/linux.c
- fix build without CLONE_NEWCGROUP.
- fix conversion from blkio to io.
- add custom annotation to load raw BPF.
- set working directory for libkrun.
- fix symlink lookup on old kernels that lack openat2
- skip +cpu on EINVAL in cgroup root.  Enabling the cpu controller is
not permitted if there are already realtime processes running on the
system.
- Fix permission error when using NOTIFY_SOCKET with username spaces.
- set HOME to root if the user not found.
- simplify mount logic to not use a temporary mount.
- ignore ENOSYS from keyctl.
=> NEWS: tag 0.18

src/libcrun/ebpf.c, tests/init.c, tests/test_devices.py
Currently the call to `access(dev_name, F_OK)` fails even if the permissions for the device file are set to `rw`. It looks like the problem is in the ebpf filtering program. The check
https://github.com/containers/crun/blob/4096e14c6f5a5684709dfaa4279ac814fdaec2ba/src/libcrun/ebpf.c#L183-L184
denies the access since with `F_OK` no read or write bits are set. Changing the comparison logic to
```c
if ((request.access & device.access) != request.access)
goto next_block:
```
solves the issue. The same way it is implemented in systemd:
https://github.com/systemd/systemd/blob/da0d560905d186baababb3abdaf3f6a159897cb2/src/core/bpf-devices.c#L145
The issue is not reproducable when the permissions are set to `rwm` since in that case the ebpf checking is skipped: …
=> ebpf: handle access(2) syscall correctly

src/libcrun/seccomp.c
if a default errno value is specified, use it instead of the default EPERM.
=> seccomp: honor default errno value

README.md
The runc development version doesn't fail when pids.max < pids.current
as the cgroups are configured later in the process.
=> README.md: drop pids limit comparison

src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c, src/libcrun/utils.c
if the init process is terminated, add a best effort heuristic to
detect whether a OOM happened and inform users with a better error
message.
Closes: https://github.com/containers/crun/issues/630
=> container: improve OOM error message

Makefile.am, contrib/seccomp-receiver/Makefile, contrib/seccomp-receiver/seccomp-receiver.c, src/create.c, src/crun.c, src/delete.c, src/exec.c, src/kill.c, src/libcrun/cgroup.c, src/libcrun/container.c, src/libcrun/error.c, src/libcrun/error.h, src/libcrun/seccomp.c, src/libcrun/seccomp.h, src/libcrun/status.c, src/libcrun/utils.c, src/libcrun/utils.h, src/pause.c, src/run.c, src/start.c, src/state.c, src/unpause.c, src/update.c, tests/init.c, tests/test_seccomp.py
The OCI runtime specs[1] recently gained the support for seccomp
notifications.
[1] https://github.com/opencontainers/runtime-spec/pull/1074
=> seccomp: support notify listener

src/libcrun/linux.c, tests/test_capabilities.py
https://github.com/opencontainers/runtime-spec/pull/1094 introduced a
change where unknown capabilities must be ignored.  The runtime MUST
log a warning instead of failing with an error.
=> linux: ignore unknown capabilities

src/libcrun/linux.c, tests/test_mounts.py, tests/test_resources.py
it is useful to reset flags like nodev,noexec,nosuid if they are not
specified in the bind mount itself.
Closes: https://github.com/containers/crun/issues/639
=> linux: always remount bind mounts

.gitignore, NEWS
- join all the cgroup v1 controllers.
- raise a warning when newuidmap/newgidmap fail.
- handle eBPF access(dev_name, F_OK) call correctly.
- fix some memory leaks on errors when libcrun is used by a long
running process.
- fix the SELinux label for masked directories.
- support default seccomp errno value.
- fail if no default seccomp action specified.
- support OCI seccomp notify listener.
- improve OOM error messages.
- ignore unknown capabilities and raise a warning.
- always remount bind mounts to drop not requested mount flags.
=> NEWS: tag 0.19

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, tests/init.c, tests/test_exec.py
The code was using the process defined in the container definition to find additional_gids,
not the one passed on the command line or created by default.
Fixes #644
=> On exec, honor additional_gids from the process spec

src/libcrun/cgroup.c, src/libcrun/cgroup.h, tests/fuzzing/run-tests.sh, tests/tests_libcrun_fuzzer.c, tests/tests_libcrun_utils.c
add support for array of strings so that it can be used like:
"annotations" : {
"org.systemd.property.After" : "['firewalld.service']"
},
Reported: https://github.com/cri-o/cri-o/pull/4766#issuecomment-820828260
=> cgroup: support array of strings

src/libcrun/cgroup.c, src/libcrun/container.c, src/libcrun/criu.c, src/libcrun/linux.c
Upper-level tools (podman etc) now set cgroupns in case cgroup v2
unified is detected. Let's do the same during crun spec.
Related: https://github.com/opencontainers/runc/pull/2322
=> spec: add cgroup ns if on cgroup v2

contrib/seccomp-notify-plugin-rust/src/seccompwatcher.rs, src/libcrun/utils.c
when the patch is longer than sizeof (sockaddr_un.sun_path)
=> utils: use /proc/self/fd to open unix socket

src/libcrun/cgroup.c
even when running in rootless mode on cgroup v1, do not ignore cgroup errors if the path was set in the configuration file.
=> cgroup: report error if the cgroup path was set

src/libcrun/status.c
in addition to ENOENT, add check for ESRCH that could be returned by
some code paths in the procfs.
Closes: https://github.com/containers/crun/issues/660
=> kill: fix race condition with pidfd_open

crun.1, crun.1.md, src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c
If the `run.oci.systemd.subgroup` annotation is specified, yet another sub-cgroup is created and the container process is moved here.
/sys/fs/cgroup/$PATH/$SUBGROUP/$DELEGATED-CGROUP
The runtime doesn't apply any limit to the `$DELEGATED-CGROUP` sub-cgroup, the runtime uses only `$PATH/$SUBGROUP`.
The container payload fully manages `$DELEGATE-CGROUP`, the limits applied to `$PATH/$SUBGROUP` still applies to `$DELEGATE-CGROUP`.
Since cgroup delegation is not safe on cgroup v1, this option is supported only on cgroup v2.
=> cgroup: add custom annotation run.oci.delegate-cgroup

src/libcrun/cgroup.c
Following issue is introduced after : https://github.com/containers/crun/pull/658 due to check on a pointer which is **NULL** in few cases ( Such as `crun run` for rootless spec where cgroupsPath is not set at all )
Reason: `cgroup_path` is passed as **NULL** when `def-linux` is defined and `def->linux->cgroups_path` is not set before passing arg to `libcrun_cgroup_enter` at  https://github.com/containers/crun/blob/master/src/libcrun/container.c#L2295 and https://github.com/containers/crun/blob/master/src/libcrun/container.c#L3538
GDB trace before fix:
```bash
Program received signal SIGSEGV, Segmentation fault.
0x000055555556e2f7 in libcrun_cgroup_enter (args=args@entry=0x7fffffffd7c0, err=err@entry=0x7fffffffdbc0) at src/libcrun/cgroup.c:1860
1860	  if (rootless > 0 && cgroup_path_empty …
```
=> Fix SIGSEGV: For `run` on rootless container caused by case when spec has linux block set but cgroupsPath is not defined.

src/exec.c
Following PR adds support for **runc** like
* `exec --no-new-privs` : set the no new privileges value for the process
**Reason:** As of now crun always sets `no_new_privileges` to **TRUE** even if baseconfig has its value set to **FALSE** however it should allow users to set value when baseconfig has configured value **FALSE**.
* `exec --apparmor`: set the apparmor profile for the process.
* `exec --process-label`:  set the asm process label for the process commonly used with selinux. 
Reference: https://manpages.debian.org/testing/runc/runc-exec.8.en.html#OPTIONS
=> Exec: add support for `--apparmor`,`--process-label`,`--no-new-privs` and adhere if noNewPriviledges is `false` in spec

crun.1, crun.1.md, src/libcrun/container.c
**Reason:** Upstream Go based (https://github.com/opencontainers/runtime-spec) parser is unable to parse crun generated spec. Introduced in PR https://github.com/containers/crun/pull/636
**Logs:**
```bash
ERRO[0000] json: cannot unmarshal string into Go struct field LinuxDeviceCgroup.linux.resources.devices.allow of type bool
```
=> Fix: Change `LinuxDeviceCgroup.linux.resources.devices.allow` to `bool` in  default Spec & Update crun manual

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h
call the prestart hooks before making the mounts read-only to keep the
same behavior runc has.
Closes: https://github.com/containers/crun/issues/667
=> container: call prestart hooks before rootfs is RO

src/libcrun/utils.c
workaround seccomp profiles where close_range is not permitted.
=> utils: close_range fallbacks to close on EPERM

Makefile.am
=> Makefile.am: make sure libocispec uses main branch

src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/linux.c
Refactor libcrun-cgroup-destory to support cleaning custom controllers by picking subsystems dynamically.
+ Adds `libcrun_cgroup_destroy_subsystem`
- Removes `libcrun_get_cgroups_subsystems`
=> cgroup: Refactor libcrun-cgroup-destory to support cleaning custom controllers.

src/libcrun/seccomp.c
commit fefabffa2816ea343068ed036a86944393db189a introduced support for
seccomp flags and hardcoded the default to ALLOW|LOG.
Change the default to SECCOMP_FILTER_FLAG_SPEC_ALLOW.
Closes: https://github.com/containers/crun/issues/683
=> seccomp: drop SECCOMP_FILTER_FLAG_LOG by default

Dockerfile
Trying to build the 0.20 release with the Dockerfile fails with the following error:
```
$ podman build -t build-crun:latest -t "build-crun:0.20" -f Dockerfile .
[...]
Program mount found: YES (/usr/bin/mount)
Program umount found: YES (/usr/bin/umount)
Program loadkeys /usr/sbin/loadkeys /sbin/loadkeys found: NO
Program setfont /usr/sbin/setfont /sbin/setfont found: NO
Program nologin found: YES (/usr/sbin/nologin)
../meson.build:620:8: ERROR: Problem encountered: python3 jinja2 missing
A full log can be found at /systemd/build/meson-logs/meson-log.txt
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
cp: cannot stat 'libsystemd.a': No such file or directory
Error: error building at STEP "RUN dnf install -y git …
```
=> crun 0.20: install required python3-jinja2 package in Dockerfile

NEWS, src/libcrun/linux.c
ignore the error when resetting the SELinux label for newly created keyrings.
If an error happen the label is left configured to the container process SELinux label.
commit 52019563aa5732414c00a91b61add7f3d75464ea introduced the issue.
Closes: https://github.com/containers/crun/issues/687
=> container: ignore resetting keyring SELinux label

src/libcrun/cgroup.c
Always write the specified memory swappiness value when it is present
in the configuration file.
=> cgroup: honor memory swappiness set to 0

src/libcrun/container.c, src/libcrun/status.c, src/libcrun/status.h, src/libcrun/utils.c, src/libcrun/utils.h, src/list.c
Following PR adds support for
* Adds a new field `owner` to `status`: Shows owners of launched containers.
* Adds a new field `created` to `list`:  Shows created timestamp for container.
Example output
```bash
NAME       PID       STATUS   BUNDLE PATH              CREATED                        OWNER
container 201048    running  /home/flouthoc/container  2021-06-17T19:21:42.000628462Z flouthoc
```
=> status: add fields for `owner` and `created` timestamp

rpm/crun.spec.in
the license was changed tp GPL 2+ last year, adapt the rpm spec file.
Closes: https://github.com/containers/crun/issues/693
=> rpm: fix license

src/libcrun/cgroup.c
on cgroup v1, if the "memory" controller is not found, attempt to
lookup the "pids" controller.
Closes: https://github.com/containers/crun/issues/700
=> cgroup: lookup pids controller as well

src/libcrun/container.c
Apparently, execve(2) can return EINTR on Azure (CIFS share),
which results in sporadic failures in `crun exec` (and possibly `crun run`).
To fix, wrap `execv` in `TEMP_FAILURE_RETRY` macro.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1917662
See-also: https://github.com/opencontainers/runc/pull/3045
=> container: wrap execv in retry-on-eintr

src/create.c, src/crun.c, src/crun.h, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/linux.c, src/libcrun/linux.h, src/run.c
[under-review] `kvm/krun`: crun should silently/gracefully switch to `krun` as backend runtime when invoked as `krun`
=> `kvm/krun`: crun should silently/gracefully switch to `krun` as backend runtime when invoked as `krun`

crun.1, crun.1.md
As discussed in #704 crun is not happy when running alongside RT
Processes
This is documented on kernel: https://www.kernel.org/doc/Documentation/cgroup-v2.txt
=> Doc: cgroups v2 and RT processes unsupported

Makefile.am
otherwise libcrun consumers fail at runtime with
symbol lookup errors
Closes: https://github.com/containers/crun/issues/711
Issue: https://github.com/containers/crun/issues/340
Downstream-bug: https://bugs.gentoo.org/717750
Signed-off-by: Georgy Yakovlev <gyakovlev@gentoo.org>
=> Makefile.am: link libcrun to $(FOUND_LIBS)

src/libcrun/cgroup.c
`cgroupv1`: Allow users to configure `memory.use_hierarchy=0` via spec if parent cgroup contains `use_hierarchy=0`. 
Usually defaults to `1` if not defined in spec.
=> cgroupv1: add support for setting memory.use_hierarchy

src/libcrun/cgroup.c
chown the root cgroup to root in the container so that it is possible
to create sub-cgroups (when /sys/fs/cgroup is mounted as writeable)
also when running in a user namespace.
=> cgroup: chown cgroup to root

src/libcrun/container.c, src/libcrun/status.c
check that the owner string is set before using it.
commit 60de7677f4ea9db37ce48964e995c2b0536af886 introduced the issue.
Closes: https://github.com/containers/crun/issues/718
=> status: check for owner before using it

src/libcrun/linux.c
The code is working on the /proc/self/fd/$FD path so there is no risk
of a race condition.
=> linux: silence two false positives reported by lgtm

NEWS, src/libcrun/utils.c
make sure the buffer used by readlinkat is NUL terminated otherwise
symlinks targets copied by "tmpcopyup" could be mangled.
Closes: https://github.com/containers/crun/issues/719
=> utils: NUL terminate readlinkat buffer

src/libcrun/cgroup.c, tests/podman/Dockerfile, tests/podman/run-tests.sh
Linux 5.14 supports the file "cgroup.kill" to kill all the processes
in a cgroup.  It avoids the cost of opening "cgroup.procs" and send
the kill signal to each process listed.
=> cgroup: use cgroup.kill if available

src/libcrun/utils.c
From the man page:
EAGAIN how.resolve contains either RESOLVE_IN_ROOT or RESOLVE_BENEATH,
and the kernel could not ensure that a ".." component didn't
escape (due to a race condition or potential attack).  The caller may
choose to retry the openat2() call.
Closes: https://github.com/containers/crun/issues/725
=> utils: retry openat2 on EAGAIN

src/create.c, src/exec.c, src/libcrun/container.c, src/libcrun/container.h, src/run.c, tests/test_start.py
Following PR adds a  default configuration of seting primary process to 1 via `LISTEN_PID`  if configuration is missing.
Following behavior is similar to runc.
=> container: Set primary process to 1 via `LISTEN_PID` by default if configuration is missing

src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c
In case the container is paused, crun exec is stuck without
any diagnostics, and this is hard to debug by end user.
Add a check, and refuse to exec in a paused container/cgroup.
Before:
```console
^C^Z^C
```
(crun exec stuck, it's unclear what is going on, and there is nothing we can do from this terminal)
After:
```console
2021-09-01T18:20:30.000549846Z: the container `xx34` is paused.
```
=> runc exec: refuze paused container/cgroup

src/libcrun/criu.c, tests/test_checkpoint_restore.py, tests/test_cwd.py, tests/test_detach.py, tests/test_devices.py, tests/test_exec.py, tests/test_hooks.py, tests/test_hostname.py, tests/test_limits.py, tests/test_mounts.py, tests/test_paths.py, tests/test_pid.py, tests/test_pid_file.py, tests/test_preserve_fds.py, tests/test_resources.py, tests/test_rlimits.py, tests/test_seccomp.py, tests/test_start.py, tests/test_tty.py, tests/test_uid_gid.py, tests/test_update.py, tests/tests_utils.py
When creating a checkpoint of a container with external PID namespace
crun fails with:
Error (criu/namespaces.c:1081): Can't dump a pid namespace without the process init
This PR allows crun to set PID namespace as external  during checkpoint/restore when "path" has been specified in config.json.
This is similar to https://github.com/opencontainers/runc/pull/2525/commits/09e103b01e34a7dda321781ec7f05939c9fe4adb
=> criu: Add support for external PID namespace

tests/podman/run-tests.sh
disable a bunch of tests that are failing and do not use the OCI
runtime.
=> tests: disable unrelated failing Podman tests

src/libcrun/linux.c, src/libcrun/status.c, tests/test_start.py, tests/tests_utils.py
fix how external_descriptors are stored in the status file.  They were
previously stored as a string,e.g.:
"external_descriptors":"[\"/dev/null\",\"pipe:[5716690]\",\"pipe:[5716691]\"]"
and breaking the JSON parser.
Closes: https://github.com/containers/crun/issues/734
=> criu: fix save of external descriptors

.github/workflows/test.yaml, src/libcrun/utils.c, tests/test_capabilities.py, tests/test_exec.py, tests/tests_libcrun_utils.c
commit ee3531124a134df9cb92679001c599f9d0979749 introduced the regression.  It also caused the e2e CRI-O tests to fail.
=> linux: fix fix-test-mount-symlink-not-existing test

.github/workflows/test.yaml, src/libcrun/linux.c, src/libcrun/status.c, tests/test_start.py
revert in part commit b055575ded0281031a3c13400df0fda67719b741 that changed how external_descriptors are stored in the status file.
Closes: https://github.com/containers/crun/issues/738
=> criu: store external descriptors as JSON string

.github/workflows/release.yaml, tests/clang-check/Dockerfile
Following commit fixes regression for artifacts.
Add libprotobuf-c-dev to dependencies.
=> artifacts: add libprotobuf-c-dev for protobuf headers

configure.ac, src/libcrun/criu.c, tests/test_checkpoint_restore.py
This pull request enables restoring of containers with IPC, UTS and Time namespaces.
It requires the `criu_join_ns_add` API of libcriu, introduced in: https://github.com/checkpoint-restore/criu/pull/1617
=> criu: Enable support for restore of shared IPC, UTS and Time namespaces

src/libcrun/cgroup.c, src/libcrun/container.c, src/libcrun/utils.c, src/libcrun/utils.h, tests/clang-check/Dockerfile, tests/clang-format/Dockerfile, tests/fuzzing/Dockerfile, tests/oci-validation/Dockerfile, tests/podman/Dockerfile
move #768 forward and fix CI
Wasm modules must accept and process if any arguments are specified in OCI spec.
Example OCI spec could contain args as
```json
...
"args": {
"./module.wasm",
"arg1",
"arg2"
},
...
=> wasm: allow wasi modules to read args from config

README.md
When compile on ubuntu, I met this error: 
```
In file included from /usr/include/criu/criu.h:25,
from src/libcrun/criu.c:26:
/usr/include/criu/rpc.pb-c.h:7:10: fatal error: protobuf-c/protobuf-c.h: No such file or directory
7 | #include <protobuf-c/protobuf-c.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Add `libprotobuf-c-dev` as dependency will solve it. 
I didn't tested other OS, I guess we have similar issue.
=> Fix build error on ubuntu

configure.ac, src/libcrun/container.c
https://github.com/second-state/crunw/issues/6
=> wasm: add support for wasmedge runtime

src/crun.c, src/libcrun/container.c
* End **users** and **container managers** should be able to check if their crun
is packaged with `wasm` support and which `wasm` runtime is it using.
```console
$ crun --version
crun version 1.3.12-e58e-dirty
commit: e58ec44d60c98eff1fd79727b4a2d81dbbf3ee35
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +WASM:wasmer +YAJL
```
* wasmedge: fix error message when fails to get valid result object from VM.
=> crun: show if version is packaged and supports `wasm` with configured runtime.

crun.1, crun.1.md, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/linux.c, src/libcrun/utils.c, src/libcrun/utils.h, tests/podman/Dockerfile
when the "idmap" mount option is specified, create the mount outside of the container user namespace context and pass the mount fd to the container init process.
=> linux: new mount option "idmap"

src/checkpoint.c, src/libcrun/container.h, src/libcrun/criu.c, src/restore.c
CRIU supports checkpoint/restore of file locks. However, it requires this feature to be explicitly enabled with the file-locks option.
The file-locks option has been introduced in runc with https://github.com/opencontainers/runc/pull/55
This option is required to checkpoint/restore application containers such as MySQL.
=> Add file-locks checkpoint/restore option

tests/podman/Dockerfile
Use podman main branch, which has a fix(containers/podman/pull/12343) to use fedora
34 image.
Signed-off-by: Hironori Shiina <shiina.hironori@jp.fujitsu.com>
=> Change podman branch to fix CI

src/libcrun/linux.c
Add another flag to see if `path` is specified with cgroup `type` in a
runtime spec for determining whether a new cgroup namespace is necessary
or not.
Signed-off-by: Hironori Shiina <shiina.hironori@jp.fujitsu.com>
=> linux: Enter specified cgroup namespace

src/libcrun/utils.c
when opening the descriptors.json file, truncate the file if it is
already existing.
Closes: https://github.com/containers/crun/issues/787
=> utils: write_file truncates existing files

src/libcrun/utils.c, tests/test_mounts.py
ignore every slash found after the first one so paths like
"/test//test" are handled correctly.
Closes: https://github.com/containers/crun/issues/786
=> mounts: handle paths with multiple slashes

configure.ac, src/libcrun/container.c
If the sd_notify_barrier function is available, use it to synchronize
systemd notify notifications and make sure they were processed by
systemd.
=> linux: use sd_notify_barrier if available

src/libcrun/container.c
the chdir could fail if it is performed while running as "root in the user namespace" and the access to the working directory is controlledby an ACL to grant permission to the specified final UID:GID.
Closes: https://github.com/containers/crun/issues/793
=> container: attempt chdir twice

src/libcrun/container.c, src/libcrun/linux.c
It seems we do early `_exit` for `custom_handlers` which are not long
running in nature and could return success e.g `wasm`.
Allow `libcrun_run_linux_container` to call `_exit` so `cleanup
attributes` could be invoked which are within the scope of
`libcrun_run_linux_container`
=> container: allow `libcrun_run_linux_container` to call final `_exit()` for handlers

src/libcrun/linux.c, src/libcrun/utils.h, tests/tests_libcrun_utils.c
improve the detection of /dev being used as a target.
There is already a check for "/dev" being used as a target, but it
fails when the bind mount is specified e.g., like "/dev/".
Improve its detection to accept any path like /*dev/*.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2021203
=> linux: improve detection of /dev target

src/libcrun/ebpf.c, tests/fuzzing/run-tests.sh
and fix a potential crash when the access string is not provided.
=> CI: correctly check for the fuzzing tests result

src/libcrun/container.c, src/libcrun/utils.c, src/libcrun/utils.h
when using a handler, make sure files marked for close at execv time
are closed before we enter the handler entrypoint.
=> container, handler: close files marked with O_CLOEXEC

configure.ac, src/libcrun/container.c
Because WasmEdge has more headers after 0.9.0 release,
the origin header wasmedge.h is moved to wasmedge folder.
Signed-off-by: hydai <hydai@secondstate.io>
=> wasmedge: The wasmedge.h is moved to wasmedge/wasmedge.h

src/libcrun/custom-handler.c, src/libcrun/handlers/wasmedge.c, src/libcrun/handlers/wasmer.c
Last refactor in https://github.com/containers/crun/pull/806 dropped
support for legacy annotation run.oci.handler=wasm for users.
Following PR adds alias to handlers so more intutive selection for
handlers can be done
Closes: https://github.com/containers/crun/issues/815
=> handlers, wasm: add lost support for `run.oci.handler=wasm`

src/libcrun/cgroup-internal.h, src/libcrun/cgroup-resources.c, src/libcrun/cgroup-systemd.c, src/libcrun/cgroup.c, src/libcrun/container.c, src/update.c, tests/test_resources.py, tests/tests_utils.py
CPUWeight/CPUShares affect the cgroup priority in relation to the sibling cgroups.  Since the expectation is that it affects other
containers at the same cgroup level, it is necessary to set it on the systemd scope.
It adds the infrastructure for setting values on the systemd scope similarly to what runc does.
@mrunalp FYI
=> cgroup, systemd: set CPUShares/CPUWeight on the systemd scope

src/libcrun/custom-handler.c
Some shims and manager like **containerd** on kubernetes still expect process image to be changed
with given executable in spec and invoked by `shim` hence perform a blank `execv` to change process
image and ignore the output since we only want to care about `exec_func`
See: https://github.com/containers/crun/issues/798
If process image is not changed containerd would fail as `Error: sandbox
container idxxxxxxx is not running`
-----
Everything above can be ignored. New fix is
We need to treat `pause` containers as regular containers spawned by containerd.
=> handler: add support for running handlers on `kubernetes` with `containerd`

src/libcrun/utils.c
The check was erroneously using `path` instead of the freshly
allocated `npath`.
Since `it - path` could be any value, in some rare cases its value was
precisely `dirpath_len`, causing the error.
=> utils: fix path check

NEWS
- wasm: support for running on kubernetes with containerd.
- linux: add support for recursive mount options.  e.g. it is possible to specify "rro" to make the mount read-only recursively.
- add support for idmapped mounts through a new mount option "idmap".
- linux: improve detection of /dev target.  Previously a mount like `/dev/` was not properly detected as mounting /dev/ from the host.
- now crun exec uses CLONE_INTO_CGROUP on supported kernels when using cgroup v2.
- retry the openat2 syscall if it fails with EAGAIN.
- cgroup: set the CPUWeight/CPUShares on the systemd scope cgroup.
- on new kernels, use setns with pidfd.
- attempt the chdir again with the specified user if it failed before changing credentials.
- ebpf: fix build on 32 bits systems.
- crun --version shows the …
=> NEWS: tag 1.4

src/libcrun/linux.c
The new code from 1.4 didn't define the `OPEN_TREE_CLOEXEC` (which we have that for OPEN_TREE_CLONE).
In case of Ubuntu 18.04, compile crun 1.4 comming with following error message:
gcc -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -I /usr/src/packages/BUILD/libocispec/src -I /usr/src/packages/BUILD/libocispec/src -fvisibility=default -g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security -c -o src/libcrun/libcrun_testing_a-linux.o `test -f 'src/libcrun/linux.c' || echo './'`src/libcrun/linux.c
src/libcrun/linux.c: In function 'get_idmapped_mount':
src/libcrun/linux.c:425:77: error: 'OPEN_TREE_CLOEXEC' undeclared (first use in this function); did you mean 'OPEN_TREE_CLONE'?
AT_NO_AUTOMOUNT | AT_SYMLINK_NOFOLLOW | …
=> src/libcrun/linux.c:425:77: error: 'OPEN_TREE_CLOEXEC' undeclared (first use in this function); did you mean 'OPEN_TREE_CLONE'?

.github/workflows/test.yaml, src/crun.c, src/libcrun/cgroup-cgroupfs.c, src/libcrun/cgroup-resources.c, src/libcrun/cgroup-setup.c, src/libcrun/cgroup-systemd.c, src/libcrun/cgroup-utils.c, src/libcrun/cgroup.c, src/libcrun/container.c, src/libcrun/criu.c, src/libcrun/custom-handler.c, src/libcrun/custom-handler.h, src/libcrun/linux.c, src/libcrun/status.c, src/libcrun/utils.c, src/libcrun/utils.h, tests/tests_libcrun_utils.c
make public some symbols that are used by crun when compiled with
`--enable-shared`.
Closes: https://github.com/containers/crun/issues/821
=> src: export some symbols used by crun

.github/workflows/test.yaml
the last commit broke the build on s390x.
Attempt the shared build only when configure succeds.
=> .github: fix ci build

.github/workflows/test.yaml, tests/podman/run-tests.sh
0. tests/podman: exclude --ip6 test case
This test case was recently added by podman commit https://github.com/containers/podman/commit/c496001d03f9eac87dfd6f3.
It fails in our test environment (probably because of IPv6) and does not
test crun in any special way.
1. Use docker as bundled with Ubuntu (note that docker.io was already in
the list of packages to install).
In fact, the current code installs docker-ce and then replaces it with docker.io:
```
The following packages will be REMOVED:
containerd.io docker-ce docker-ce-cli
```
2. Do not install software-properties-common as it's already installed
(it is needed for add-apt-repository script).
3. Do not run apt-get update as apt-add-repository does that already.
=> gha: simplify deps install

src/libcrun/cgroup-systemd.c
commit ec70d28ceaab2fb8d65255abffaa12e3c95b5006 introduced the
regression.
Closes: https://github.com/containers/crun/issues/830
=> cgroups, systemd: skip setting cpu limits if shares==0

src/libcrun/error.h, src/libcrun/linux.c, src/libcrun/seccomp.c, tests/test_exec.py, tests/test_start.py, tests/tests_utils.py
so it can iterate over each namespace and attempt to join them before the user namespace if required.
=> linux: skip setns_with_pidfd with explicit paths

tests/fuzzing/run-tests.sh
This (hopefully) fixes a flake seen in https://github.com/containers/crun/pull/843.
Recent commit ff3e33b95eba65f5cea89e9070ca1677a0a953d7 removed subshell
from grep invocation, but overlooked the fact that pipefail option is
also set. As a result, we get an occasional exit code 141 (i.e. SIGPIPE)
from the script (which was prevented by having a subshell).
Since this grep is the only pipe in the script, and we're looking at the
exit code from grep, remove "-o pipefail" from it.
=> tests/fuzzing/run-tests.sh: fix flaking

src/libcrun/utils.c
it has already caused an issue in the past and it doesn't add any
value, since each component in the path is validated again later on.
Closes: https://github.com/containers/crun/issues/842
=> utils: drop check for invalid path

tests/oci-validation/run-tests.sh
Since https://github.com/opencontainers/runtime-tools/pull/741 and https://github.com/opencontainers/runtime-tools/pull/742 this is no longer needed.
This reverts commit 6d046d6c4f0e4111e74c2281606863e1c4e1c40d (PR #762).
~~Currently a draft, pending https://github.com/opencontainers/runtime-tools/pull/742 merge.~~
=> Revert "oci-validation: checkout last working commit for runtime-tools"

NEWS
- Fix check for an invalid path.  crun was performing the wrong check
to validate a path, causing spurious failures at runtime.
- Allow deleting a container while in `created` state.  It goes
against what the OCI runtime specs dictate, but it is the expected
behavior since runc allows it.
- Fix regression when joining a container that has explicit paths for
the namespaces.
- cgroup: do not set cpu limits if number of shares is set to 0.
Moby uses 0 to indicate no limits.
- Fix build issues when configured with --enable-shared.
- Fix build on systems where OPEN_TREE_CLOEXEC is not defined.
- Improve diagnostics for errors returned by dbus.
=> NEWS: tag 1.4.1

src/libcrun/container.c, src/libcrun/utils.c, src/libcrun/utils.h
if the find_executable() call fails when running with EUID=0, ignore any error beside ENOENT and attempt again the lookup once the process switched to the final UID/GID used in the container.                                                                                    
This is visible on network file systems like NFS, where CAP_DAC_OVERRIDE is not honored and the EUID=0 cannot read a file if it is owned by the UID/GID in the container.                                                                                            
It is the same mechanism we already have in place for chdir() that might fail before the setresuid() call.                                                                                                 
Closes: https://github.com/containers/crun/issues/852 …
=> container: attempt find_executable after setresuid                                                                                      

python/crun_python.c
commit 21a8dafae7f26cba1250519aaeb3e55ea445cf93 introduced the
regression.
Closes: https://github.com/containers/crun/issues/854
=> python: fix build

configure.ac, crun.1, crun.1.md, src/checkpoint.c, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/criu.c, tests/centos8-build/Dockerfile, tests/centos9-build/Dockerfile, tests/init.c, tests/test_checkpoint_restore.py
CRIU supports the concept of pre-copy migration. Instead of creating a
complete checkpoint of a process it is possible to only write the memory
of the process to disk while the process keeps on running. The first
memory only checkpoint can then be transferred to the migration
destination. During the transfer time it is possible take a second
checkpoint which will only write the memory pages to disk that have
changed since the previous checkpoint. This way it can be possible that
the second checkpoint is much smaller while the process keeps on running
which also means that the amount of data which needs to be transferred
to the migration destination might be smaller and thus the migration
downtime can be reduced. This only makes sense if the number of memory
pages which are changing is …
=> pre-dump support

src/libcrun/container.c
reproducer:
podman run --mount=type=tmpfs,target=/dev,ro=true -v /dev/null:/dev/pts -v /dev/null:/dev/shm ...
=> container: ignore EROFS when chowning std stream files

src/libcrun/linux.c, src/libcrun/utils.c
move the creation of /dev/console to create_missing_devs so that it is performed before setting /dev read-only if configured in the OCI spec file.
=> linux: create_missing_devs creates /dev/console

src/libcrun/linux.c, src/libcrun/linux.h, tests/test_start.py, tests/tests_utils.py
copy the same logic used by runc that validates sysctl before applying them.  Some sysctls require a new namespace, otherwise their value is applied to the host namespace.
=> linux: validate sysctls before applying them

src/libcrun/utils.c
if the dup() syscall fails return a valid error message.
=> utils: check for dup error

tests/cri-o/Dockerfile, tests/cri-o/run-tests.sh
* We are locking cri-o to a specific commit which has breaking vendor
dependencies instead point it to last released tag.
* Lock cri-tools to last working stable tag i.e v1.23.0
Both `cri-o` and `cri-tools` are breaking in upstream and so in CI runs.
Last spotted CI failure here: https://github.com/containers/crun/pull/841
=> test: remove locking to a specific commit in CI for `cri-o` and `cri-tools` and use last stable tag

tests/init.c
On some kernels the seccomp syscall version is not known. Add missing define for this value in the tests (already exists elsewhere in the code)
=> Fix compilation error with seccomp

src/libcrun/linux.c
According to man pages of `mount` syscall:
"If mountflags includes MS_BIND ... The filesystemtype and data arguments are ignored. ... The remaining bits (other than MS_REC, described below) in the mountflags argument are also ignored."
=> Remove ignored arguments

src/libcrun/linux.c, src/libcrun/utils.h, tests/test_mounts.py, tests/test_uid_gid.py
when creating a new user namespace, attempt to open the source for the
bind mounts in the current context, as we might lose access to the
directory as root in the user namespace.
Closes: https://github.com/containers/crun/issues/871
=> linux: open source bind mount in the host

Makefile.am, src/libcrun/cgroup-cgroupfs.c, src/libcrun/cgroup-systemd.c, src/libcrun/cgroup-utils.c, src/libcrun/cgroup.c, tests/test_delete.py
Following commit makes sure that we terminate the destroy cgroup loop if in
case we ever fail to destroy the cgroup for N number of times and relay
a error back to caller function.
Closes: https://github.com/containers/crun/issues/868
=> cgroup-destroy: terminate destroy loop and relay error back to caller

tests/test_delete.py, tests/tests_utils.py
Its a feature of crun to throw warnings when cgroup cleanup fails, and
currently cgroup delete test is testing that feature however CI will
fail on error/warning so filter out known expected warning and only fail if error
is unknown.
=> test, container-delete: ignore known `EBUSY` warning for cgroupv1 when process is `freezed`

crun.1, crun.1.md, src/libcrun/linux.c, src/libcrun/utils.h, tests/centos8-build/Dockerfile, tests/centos9-build/Dockerfile, tests/init.c, tests/test_mounts.py
allow to specify what mapping must be used for idmapped mounts.
The mapping can be specified after the `idmap` option like:
`idmap=uids=0-1-10;gids=0-100-10`.
When `uids` and `gids` are specified, then a new user namespace is
created and used for the bind mount.
Closes: https://github.com/containers/crun/issues/873
=> linux: support options to idmap

configure.ac
configure scripts need to be usable with a POSIX-compliant /bin/sh
(like e.g. 'dash', which is the default provider of /bin/sh on Debian).
This has no effect on bash compatibility and will continue to work
with bash.
Signed-off-by: Sam James <sam@gentoo.org>
=> build: fix bashism in configure.ac

src/libcrun/linux.c, tests/test_mounts.py
when opening a bind mount from the host, resolve the symlink instead
of using the symlink itself as the source.
commit bb5bc67d97379293c0f425b6c7b15c276ccbbeec  introduced this regression.
issue reproducible with:
$ ls -l /usr/libexec/podman/catatonit
lrwxrwxrwx. 1 root root 32 Nov  8 15:35 /usr/libexec/podman/catatonit -> /usr/libexec/catatonit/catatonit
$ sudo podman run --rm --init --uidmap 0:100000:1024 centos true
Error: /usr/bin/crun: executable file `/dev/init` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
=> linux: resolve symlinks in bind mounts

NEWS
- wasm, kubernetes: support wasm for kubernetes infrastructure with side-cars
- Resolve symlinks in bind mounts when creating a user namespace.
- Fix CVE-2022-27650: exec does not set inheritable capabilities.
=> NEWS: tag 1.4.4

build-aux/git-version-gen
prepend a bunch of .0 when creating a version string for the current
git working tree, so that it doesn't conflict with a future release.
e.g. now it generates "1.4.4.0.0.0.4-9421" instead of "1.4.4.4-9421"
so it will compare <= than a future release 1.4.4.4.
Closes: https://github.com/containers/crun/issues/864
=> git-version-gen: fix version comparison

README.md
The glibc-static package is required by RHEL system, if not, it will hit
error like this 'exec container process (missing dynamic library?) `/init`:
No such file or directory\n' when running tests with make check-TESTS.
=> docs: fix dependencies on RHEL/CentOS 8 section

src/exec.c
duplicate the strings before passing them to the process profile,
since it owns them.
Closes: https://github.com/containers/crun/issues/898
=> exec: fix double free

crun.1, crun.1.md, src/checkpoint.c, src/checkpoint.h, src/libcrun/container.h, src/libcrun/criu.c, src/restore.c
This is motivated by checkpoint errors of containers restored with a new ID in Podman.
Restoring a container with a new name and ID will result in a new cgroup assigned to the container. Unfortunately CRIU restores information about the original cgroup name. Now the container is running in one cgroup but partially has still old cgroup information tied to it.
This adds `--manage-cgroups-mode=ignore'` to crun which allows crun to tell CRIU to completely ignore anything concerning cgroups.
With this change it is possible to checkpoint and restore a container multiple times with changing names and IDs.
=> criu: add support for different manage cgroups modes

src/libcrun/status.c
I don't get the meaning of error message here.
I found when this line of code written, it was in a function called `libcrun_status_read_exec_fifo`, which really read from a fifo,
but now this function is writting data to `exec.fifo`. Should we update the message?
=> libcrun: fix typo

.github/workflows/test.yaml, README.md, src/libcrun/container.c, tests/test_hooks.py
if the hook doesn't specify an env block, then inherit it from the
current process.
Closes: https://github.com/containers/crun/issues/906
=> linux: hooks inherit env if not specified

tests/podman/Dockerfile
Change default log-driver in tests from `journald` to `k8s-file` since
crun tests does not directly exercises `journald` hence its easier to
maintain and run tests without `journald` setup inside container tests.
=> podman, tests: change default `log-driver` to `k8s-file` instead of `journald`

src/libcrun/cgroup-resources.c
Closes: https://github.com/containers/crun/issues/876
=> cgroup: add support for cpu.idle

src/libcrun/linux.c, tests/test_start.py
attempt to create the specified working directory if it doesn't exist
already.
We had this logic to detect typos when launching Podman containers,
but since Podman now checks that the cwd exists, we do not need
anymore to keep the old behavior but follow what runc does.
=> linux: create missing cwd

tests/clang-check/run-tests.sh, tests/cri-o/run-tests.sh, tests/fuzzing/run-tests.sh, tests/oci-validation/run-tests.sh, tests/podman/run-tests.sh
Set `/crun` as safe directory on containers running the tests.
Last regression seen here: https://github.com/containers/crun/pull/841
=> test: set `/crun` as safe directory on containers running the tests

Makefile.am, configure.ac, docs/mono-example.md, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/custom-handler.c, src/libcrun/custom-handler.h, src/libcrun/handlers/mono.c, src/libcrun/linux.c, src/libcrun/linux.h
Allows `crun` to natively run `.net` based `exe` using `mono` as under the hood `.net` runtime.
When built using `mono` following extension allows crun to run scratch based images with windows portable 
executables based on `.NET`  natively on `linux`.
Allows `crun` to run on `linux`.
```Dockerfile
FROM scratch
COPY hello.exe .
CMD ["/hello.exe"]
```
Ref:
https://dotnetfoundation.org/projects/mono
https://wiki.winehq.org/Mono
https://www.mono-project.com/
https://en.wikipedia.org/wiki/Mono_(software)
-- Draft till --
=> windows: use `mono` to run `.NET` based windows `exe` natively on linux.

src/libcrun/utils.c, tests/podman/Dockerfile
In `copy_recursive_fd_to_fd()`, copy the whole file by calling `copy_from_fd_to_fd()` with consume=1.
In `copy_from_fd_to_fd()`, pass a buffer length to `copy_file_range()`, don't bother calling `read()` and `write()` if it succeeds, and handle partial `write()`s correctly if we have to fall back to doing the copying ourselves by calling `read()` and `write()`.
Should fix https://github.com/containers/podman/issues/14243.
=> copy_recursive_fd_to_fd(): copy the whole file

docs/mono-example.md
Mono crun handler man page contains incorrect reference of `wasm` in headings.
=> mono: remove incorrect `wasm` headings from mono docs

src/libcrun/utils.c, tests/clang-format/Dockerfile, tests/clang-format/run-tests.sh, tests/init.c
1. The check was a no-op since commit a51137c91ad which neglected to add
the ENTRYPOINT in Dockerfile.
2. The above commit also forgot to install git. While at it, s/yum/dnf/.
3. Since a recent git release, any git operation working on files not
belonging to a current use complains like this:
fatal: unsafe repository ('/crun' is owned by someone else)
To workaround that, add git config --add safe.directory.
4. Differences in tests subdirectory were not caught because commit
4b184254 neglected to add tests to git diff --exit-code arguments.
Replace the list of directories to check with --ignore-submodules,
so we don't have to keep the list of directories in Makefile's
clang-format git ls-files with the one in run-tests.sh here.
=> ci: re-enable and fix clang-format

src/libcrun/container.c, src/libcrun/linux.c
Move notification for `HANDLER_CONFIGURE_AFTER_MOUNTS` just after we finalize
mounts as certain handlers need to perform mounts just after we are done
with container mounts and before we reset `rootfsfd`.
Closes: https://github.com/containers/crun/issues/945
=> krun, handler: move notifer for phase `HANDLER_CONFIGURE_AFTER_MOUNTS` just after finalizing mounts

src/libcrun/linux.c
As in linux we cannot execute device we can safely add `MS_NOEXEC` flag to the device mount. Also as it will not be executed the flag `MS_NOSUID` can be added too. Reasoning: on some platforms those flags were added either way but on some they are missing. If it doesn't make sense to exec then we should disallow it inside the mount just as a precaution.
=> linux: devices mounts should have NOEXEC and NOSUID

tests/centos9-build/Dockerfile
Add protobuf-devl to centos-9 build test.
Needed for: https://github.com/containers/crun/pull/933 and CI
=> artifacts, centos9-build: add `libprotobuf-c-devel` for protobuf headers

src/libcrun/handlers/krun.c
Since libkrun implemented library versioning via in "df698976", use
the library's soname ("libkrun.so.1") instead of just "libkrun.so" to
ensure we're pinned to a compatible ABI version.
This is also convenient because some distros, such as Fedora, only
ship the "libkrun.so" symbolic link in the "-devel" package.
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> krun: use library soname in dlopen

src/libcrun/linux.c
There are distributions which do not have `newgidmap` or `newuidmap` in
`/usr/bin` but available in `$PATH`. To support that, we now have to use
the binary names directly rather than its full path.
Refers to https://github.com/NixOS/nixpkgs/pull/178458
=> linux: use $PATH for newgidmap and newguidmap

tests/init.c
'uint64_t' was declared in file <stdint.h> which did not included.
=> fix compile error unknown type name 'uint64_t'

src/libcrun/linux.c, tests/test_devices.py
fix the creation of devices nodes in the container rootfs.
commit d583bdcef7f7297c58ce65b69ccbda908e050548 introduced the regression.
Closes: https://github.com/containers/crun/issues/917
=> linux: fix creating devices in the rootfs

crun.1, crun.1.md, src/libcrun/cgroup-resources.c
copy the same fallback runc has.
If io.bfq.weight doesn't exist, then fallback to using io.weight with
a conversion.
=> cgroup: add fallback to io.weight

python/crun_python.c, src/create.c, src/crun.c, src/libcrun/container.c, src/libcrun/container.h, src/run.c, tests/tests_libcrun_fuzzer.c
do not create a new process for each run.
Closes: https://github.com/containers/crun/issues/948
=> python: unset LIBCRUN_RUN_OPTIONS_PREFORK for run

Makefile.am, configure.ac, docs/wasm-wasi-on-kubernetes.md, src/libcrun/custom-handler.c, src/libcrun/handlers/wasmtime.c
Following PR initiates and adds support for crun to be able to build and
run wasm/wasi workload in a native manner using `wasmtime`.
Crun already supports running `wasm` workload using `wasmer` and `wasmedge`
following PR extends this feature so that end-users can switch to `wasmtime`,
following feature is proposed inorder to maintain feature parity with
other tools in the same space like `krustlet` which rely on `wasmtime` under the hood.
Ref:
* Wasmedge integration: https://github.com/containers/crun/pull/774
* Wasmer integration: https://github.com/containers/crun/pull/742
* https://github.com/krustlet/krustlet
=> wasm: add support for running containers using `wasmtime`

NEWS, nix/nixpkgs.json
- add mono based native .NET handler
- new Wasmtime backend for running WebAssembly
- add support for wasmedge 0.10 and dropping support for wasmedge 0.9.x
- dropping support for experimental `WasmEdgeProcess` from wasmedge handler
- honor process user's uid when setting the HOME environment variable
- create the current working directory if it is missing in the container
- fallback to using a tmpfs mount if umount of /sys and /proc fails
- fallback to netlink to setup lo device
- fix creating devices in the rootfs
- fallback to using io.weight if io.bfq.weight doesn't exist.
- remove tun/tap from the default allow list
- linux: devices mounts have noexec and nosuid
- fix copyup of files from the container to the tmpfs
- honor $PATH for newgidmap and newguidmap
- krun: limit the number of …
=> NEWS: tag 1.5

crun.1, crun.1.md, src/libcrun/cgroup-cgroupfs.c, src/libcrun/cgroup-internal.h, src/libcrun/cgroup-systemd.c, src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c, tests/cri-o/run-tests.sh
change the delegate cgroup semantic to be the cgroup that is created in the container payload after the cgroupns is created.
=> cgroup: change delegate cgroup after cgroupns creation

rpm/Makefile, rpm/crun.spec.in
Copr has the Makefile build option which expects a `.copr/Makefile` with
an srpm target. While we had that already, we were lacking the
`git submodule update --recursive --init`,
`./autogen.sh` and `./configure` steps causing copr builds to fail.
This commit resolves that.
Noteworthy changes to rpm/crun.spec.in include:
1. Epoch bump to 101 to clearly differentiate copr packages from
distro packages. RPM release tag includes build_timestamp for
uniqueness.
2. Source0 URL only mentions a filename which can be generated with
`make tarball-prep`, gets placed in the repo root dir.
3. krun included as a subpackage.
4. autogen.sh and configure are now run via rpm/Makefile, so there's
no need for them in the specfile.
@giuseppe @font PTAL. …
=> rpm/Makefile: autobuild rpms on podman-next copr

rpm/Makefile
After PR #975, the triggered builds on `rhcontainerbot/podman-next`
copr are failing like so:
```
git submodule update --recursive --init
git archive --prefix=crun-latest/ -o crun-latest.tar.gz HEAD
/bin/sh: line 2: git: command not found
/bin/sh: line 3: git: command not found
make: *** [/mnt/workdir-3s_ozokd/crun/.copr/Makefile:5: tarball-prep] Error 127
```
Detailed log at:
https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/srpm-builds/04689814/builder-live.log.gz
The builds seem to occur in a mock environment with no prior git binary
installed.
This PR should fix that.
@giuseppe @flouthoc @rhatdan PTAL
=> rpm/Makefile: install git-core in tarball-prep

.github/workflows/test.yaml, rpm/Makefile, rpm/crun.spec.in, tests/fedora-rawhide-mockbuild/Dockerfile, tests/fedora-rawhide-mockbuild/run-mockbuild.sh
The mock environment needs all dependencies installed before running
autogen.sh and configure.
This PR will also enable fedora-rawhide-mockbuild test in CI.
Follow-up to PR #977.
@giuseppe @flouthoc @rhatdan PTAL. This time I've tested locally on a mock fedora rawhide environment, so I'm quite certain we'll be good to after this PR. Thanks.
sudo is not present by default on mock environments, so I got rid of that from the dnf step.
=> rpm/Makefile: install all dependencies on mock environments

Makefile.am, configure.ac, rpm/Makefile, rpm/crun.spec.in, tests/fedora-rawhide-mockbuild/Dockerfile, tests/fedora-rawhide-mockbuild/run-mockbuild.sh
- `make -f .copr/Makefile srpm outdir=$(OUTDIR)` works.
See: https://docs.pagure.org/copr.copr/user_documentation.html#make-srpm
- `./autogen.sh && ./configure && make [srpm,rpm]` works locally.
- added Fedora version conditionals for libkrun support as
libkrun exists only for Fedora 37/rawhide on aarch64 and x86_64.
- `./autogen.sh` and `./configure` need to be run in .copr/Makefile for
`srpm`, `rpm` and `libocispec` targets as well as in `.copr/crun.spec` after
exploding the tarball for generating the actual rpms.
- rpm build release tag is of the form:
`$TIMESTAMP.$GIT_SHORTCOMMIT.$DIST`.
- `.copr/crun.spec.in` temporarily uses hardcoded `Version: 0.0` as copr seems to
use a strange and unexpected string for `$VERSION` and thus `@RPM_VERSION@`.
Signed-off-by: Lokesh Mandvekar …
=> rpm/Makefile: Fix copr build (follow-up on #979)

src/libcrun/handlers/wasmtime.c
Following PR introduces two changes.
libwasmtime_exec already passes `argv` which is generated from args
provided to container so use that instead of inheriting args from crun
process.
By default WASI programs do not have access to anything on the filesystem,
So for use cases where WASI program needs to access files on the current
path we must preopen those paths, hence by default always preopen `.` in
a `scratch` container.
For Example in below `Containerfile`, WASI program takes `inputfile` as
argument and writes output to `outputfile` where both files are present
in a path which starts with `.`.
```Dockerfile
FROM scratch
COPY inputfile /
COPY main.wasm /
CMD ["/main.wasm", "inputfile", "outputfile"]
```
Under the hood `wasmtime` preopens a directory, and make it available to
the …
=> wasmtime: always grant `filesystem capability` for workdir inside container 

rpm/Makefile, rpm/crun.spec.in
Limited to Fedora rpms for now as wasmtime rpms don't yet build on
RHEL 8/9.
wasmtime-c-api-devel can be installed from a separate copr:
`lsm5/wasmtime` at the time of this commit, but subject to change.
The wasmtime Copr is added as an `External Repository` to
`rhcontainerbot/podman-next` so there's no need for extra configuration
in the crun repo itself.
Also reduce the dependencies installed and configure opts used in
`.copr/Makefile` as we only care about making Copr's `make_srpm` method
happy and it doesn't affect the final rpms.
Successful copr build with wasmtime enabled at: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/playground/build/4726411/
@giuseppe @flouthoc @font PTAL
=> autobuild copr rpms with wasmtime support

tests/fedora-rawhide-mockbuild/run-mockbuild.sh
Install dependencies for `make rpm`.
@giuseppe @rhatdan PTAL
=> tests: fix fedora rawhide mockbuild

rpm/crun.spec.in
@giuseppe @rhatdan @flouthoc PTAL
/cc @font 
To test:
```
$ sudo dnf -y copr enable lsm5/wasmtime
$ sudo dnf -y copr enable rhcontainerbot/playground
$ sudo dnf -y install crun
$ cargo new hello_wasm --bin
$ cd hello_wasm
$ sudo dnf -y install rust-std-static-wasm32-wasi
OR 
$  cargo build --target wasm32-wasi
$ cp target/wasm32-wasi/debug/hello_wasm.wasm .
$ echo 'FROM scratch
COPY hello_wasm.wasm /
CMD ["/hello_wasm.wasm"]' > Containerfile
$ buildah build --annotation "module.wasm.image/variant=compat" -t mywasm-image .
$ podman run mywasm-image:latest
```
=> copr: depend on wasmtime-c-api for shared lib

crun.1, crun.1.md, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/linux.c
the workaround is not required anymore since all the needed pieces to
support running with a single user mapped with non-zero UID are
already implemented in Podman.
=> container: drop intermediate userns feature

src/libcrun/utils.c
1. I am not sure why crun config fd 0 in `libcrun_terminal_setup_size`, should it be `fd`?
2. I think we should init `mask` as a empty sigset before call sigaddset.
3. should we unblock sigchld as soon as hook finish?
=> some little bug fix maybe

src/crun.c
runc compatibility: now -v prints the version in the same mode as
--version.
Closes: https://github.com/containers/crun/issues/1003
=> crun: now -v prints the version

configure.ac, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, src/libcrun/seccomp.c, src/libcrun/utils.c, src/libcrun/utils.h
use a helper process to send the listener fd to the child process, in
this way the sendmssg syscall happens from an environment that is not
seccomp filtered.
The helper process shares the fd table with the main process, so there
is no need to send the fd around, and no syscalls are invoked between
the seccomp filter setup and the sendmssg, so that all syscalls can
use SCMP_ACT_NOTIFY without any risk of deadlocking the runtime itself.
Closes: https://github.com/containers/crun/issues/1002
=> seccomp: use helper process to send listener fd

src/crun.c
PR https://github.com/containers/crun/pull/1005 added support for `-v`
(lowercase) but dropped already working `-V` (uppercase) although less
critical but looks like a breaking change hence reintroduce `-V`
(uppercase) as argp alias to `-v` and `--version`.
See: Option `OPTION_ALIAS` here: https://www.gnu.org/software/libc/manual/html_node/Argp-Option-Flags.html
Output of `crun --help`
```console
crun --help
Usage: crun [OPTION...] COMMAND [OPTION...]
COMMANDS:
create      - create a container
delete      - remove definition for a container
exec        - exec a command in a running container
list        - list known containers
kill        - send a signal to the container init process
ps          - show the processes in the container
run         - run a container
spec        - generate a …
```
=> crun: reintroduce `-V` (uppercase) as an alias for `--version`

rpm/crun.spec.in
wasmtime-c-api-devel package has not been enabled for i386 on the
podman-next copr, hence wasmtime support should be disabled for crun on
i386.
@giuseppe @rhatdan @flouthoc PTAL
=> Copr: wasmtime support only for non-x86

.github/workflows/test.yaml, src/libcrun/handlers/wasmedge.c, tests/wasmedge-build/Dockerfile, tests/wasmedge-build/hello_wasm/Containerfile, tests/wasmedge-build/hello_wasm/hello/Cargo.toml, tests/wasmedge-build/hello_wasm/hello/src/main.rs, tests/wasmedge-build/run-tests.sh
Notice: The WasmEdge 0.11.0 is planned to be released at the end of this month. Since the test will use the installer to install the corresponding version of WasmEdge, please merge this PR after the WasmEdge 0.11.0 release. Thanks.
Since wasmedge implemented library versioning in "e5af947d", use
the library's soname ("libwasmedge.so.0") instead of "libwasmedge_c.so"
to ensure crun can pin to a compatible ABI version.
Notice: the soname is shipped in wasmedge 0.11.0, before this release
the libwasmedge_c.so is unversioned.
For details, please refer to
[WasmEdge PR#1783](https://github.com/WasmEdge/WasmEdge/pull/1783)
Signed-off-by: hydai <hydai@secondstate.io>
=> wasm: use wasmedge library soname in dlopen

src/libcrun/seccomp.c
=> seccomp: honor SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV

NEWS
- runc compatibility: -v now prints the version string.
- build: fix build with glibc 2.36.
- container: drop intermediate userns custom feature.
- cgroup: change the delegate cgroup semantic so that the cgroup is
created in the container payload after the cgroup namespace is created.
- seccomp: use helper process to send file descriptor to the listener
socket.  It enables to be notified on every syscall without hanging
the main process.
- linux: add a fallback to using kill(2) if pidfd_send_signal(2) fails
with ENOSYS.
- krun: add support for krun-sev.
- wasmtime: always grant filesystem capability for workdir inside the container.
- wasmtime: inherit arguments list from the handler instead of the current process.
- wasmedge: use released wasmedge library instead of libwasmedge_c.so. …
=> NEWS: tag 1.6

rpm/crun.spec.in
Follow up on f34ebf2.
Also disable wasmtime support for ppc64le as there are no successful wasmtime builds for it yet.
Successful build for all arches along with centos and epel https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4830805/
@giuseppe @flouthoc PTAL. Sorry my previous commit didn't actually fix i386 builds because it kept complaining about `wasmtime_opts-unknown`, so I just got rid of that macro. The current patch is a little ugly, but works.
=> Copr: Fix i386 builds

src/libcrun/cgroup-systemd.c
create a sub-cgroup under the systemd scope also when running on cgroup v1.
Closes: https://github.com/containers/crun/issues/1011
=> systemd: create sub-cgroup on v1 as well

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, tests/init.c, tests/test_domainname.py
the runtime-spec recently gained the ability to store the domainname for a container. This field functions very similarly to hostname, where if provided the field is funneled into the `setdomainname` command
Signed-off-by: Charlie Doern <cdoern@redhat.com>
=> add support for setting the domainname if provided in the spec

tests/test_domainname.py
Unexpected success must ignore `(none)` as output for systems which return `(none)` when no `domainname` is set.
Ref: https://refspecs.linuxbase.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/baselib-getdomainname.html
=> test: ack `(none)` as output of `getdomainname`

src/libcrun/linux.c, tests/test_domainname.py
Setting sysctl `kernel.domainname` directly by user is not environment agnostic, it shows either incorrect ( on non-working ) behaviour in `rootless` environment.
It was decided to make this part of `runtime-spec` so the OCI runtime can itself handle this behaviour correctly. As a result a new field `domainname` was added to `runtime-spec`. Since crun already implementes this field therefore `sysctl` configured by user conflicts with the behaviour expected by the OCI runtime.
Runtime-spec PR: https://github.com/opencontainers/runtime-spec/pull/1156
Furthermore a similar `sysctl` `kernal.hostname` is blocked by crun explicitly to prevent this conflicting behaviour. https://github.com/containers/crun/blob/main/src/libcrun/linux.c#L3203
=> linux: reject sysctl `kernel.domainname` when OCI knob `domainname` is set

python/crun_python.c
In `make_context`, the number of arguments in the format string passed to `PyArg_ParseTupleAndKeywords` was not matching with the number of entries in `kwlist`, resulting in an error when trying to pass non-mandatory arguments such as `detach`.
For example, the following program:
```python
import python_crun
context = python_crun.make_context("test", detach=True)
```
Resulted in the following error:
```
Traceback (most recent call last):
File ".../test.py", line 2, in <module>
context = python_crun.make_context("test", detach=True)
SystemError: more argument specifiers than keyword list entries (remaining format:'sb')
```
=> python: Fix argument parsing in make_context

python/crun_python.c
In `container_delete`, the type used for the `force` boolean should be `b` (a single unsigned byte) instead of `n` (the size of `size_t`). This incorrect type can cause the neighboring `id` argument to be overwritten with a NULL value, which makes the container deletion fail.
For example, assuming the `test` container exists, the following program:
```python
import python_crun
context = python_crun.make_context("test")
python_crun.delete(context, "test", True)
```
Previously resulted in the following error:
```
Traceback (most recent call last):
File ".../test.py", line 3, in <module>
python_crun.delete(context, "test", True)
RuntimeError: cannot open directory '/run/user/1000/crun/(null)': Bad address
```
=> python: Fix argument type in container_delete

Makefile.am, configure.ac, src/crun.c, src/exec.c, src/libcrun/container.c, src/libcrun/container.h, src/list.c, src/update.c
If crun is compiled with --enable-shared, then open the libcrun
dependency with dlopen.  This is useful to reduce the number of
syscalls crun performs before re-execing itself (through
cloned_binary.c), since every ELF dependency is resolved by the
dynamic loader before the program is executed.
=> crun: dlopen libcrun

src/libcrun/container.c, src/libcrun/container.h, src/libcrun/ebpf.h, src/libcrun/linux.h, src/libcrun/seccomp.h, src/libcrun/status.h, src/libcrun/utils.h
Because of the changes in https://github.com/containers/libocispec/pull/120, we will need to refer to libocispec headers in `ocispec/`.
Signed-off-by: Ronal Abraham <ronalabraham@gmail.com>
=> Refer to libocispec header files under ocispec/

crun.1, crun.1.md
Remove redundant defination for `run.oci.handler` and 
instead create sub-headings for `krun` and `wasm` handler.
=> man: cleanup `run.oci.handler` and define `krun`,`wasm`

src/libcrun/handlers/wasmedge.c, tests/wasmedge-build/Dockerfile, tests/wasmedge-build/hello_wasm/Containerfile, tests/wasmedge-build/hello_wasm/expected_output, tests/wasmedge-build/hello_wasm/hello/src/main.rs, tests/wasmedge-build/run-tests.sh
In the current implementation, the WasmEdge handler doesn't inherit the environment variables from the current process. Hence, the environment variables that are provided by the containers are all dropped. This will make some information that is passed by k8s also dropped.
This commit adds `args` and `envs` test to verify the behavior of `std::env::args()` and `std::env::vars()`.
Signed-off-by: hydai <hydai@secondstate.io>
=> wasm: inherit environment variables in the WasmEdge handler

crun.1, crun.1.md
Fix indentation for `man` render.
Error was made here: https://github.com/containers/crun/pull/1036
=> man: fix indentation for `run.oci.handler=HANDLER`

README.md, configure.ac, src/crun.c, src/libcrun/container.c, src/libcrun/seccomp.c, src/libcrun/seccomp.h, tests/alpine-build/Dockerfile, tests/centos8-build/Dockerfile, tests/centos9-build/Dockerfile, tests/containerd/Dockerfile, tests/cri-o/Dockerfile, tests/fuzzing/Dockerfile, tests/podman/Dockerfile, tests/tests_libcrun_fuzzer.c, tests/wasmedge-build/Dockerfile
store the generated seccomp bpf by the checksum of its input data.
=> container: cache the seccomp generated bpf

crun.1, crun.1.md, src/libcrun/criu.c, src/libcrun/linux.c
if specified, the runtime creates a pidfd for the container process and pass it to the UNIX socket that is listening on the specified path.
=> linux: add run.oci.pidfd_receiver=PATH annotation

src/libcrun/cgroup-cgroupfs.c, src/libcrun/cgroup-internal.h, src/libcrun/cgroup-systemd.c, src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h
on cgroupfs, grab a pidfd to the destination cgroup, if the cgroup can be already created.                                                                                                                                 
Pass the cgroup dirfd to libcrun_run_linux_container, that will attempt to use the dirfd with clone3(CLONE_INTO_CGROUP) so that the container process is created directly in the target cgroup.                                                                                                                   
If the clone3 syscall fails, then fallback to the existing mechanism based on clone.                                                                                                                                                               
It is currently supported …
=> container: use clone3 to join directly the target cgroup

tests/cri-o/run-tests.sh
Recent PR have started showing failures in CI for cri-o test where the tests itself are not related to any changes that went into crun, since its related to upstream lets skip them from crun's CI
Last PR where this was seen: https://github.com/containers/crun/pull/1048
=> crio,test: skip unrelated `seccomp notifier with *`

src/crun.c, src/libcrun/utils.c, src/libcrun/utils.h
if the crun executable file has the form crun-$HANDLER then automatically use $HANDLER as the handler to use.
e.g.
will automatically use the wasmedge handler to run the container.
=> crun: automatically pick handler from argv0

rpm/crun.spec.in, tests/fedora-rawhide-mockbuild/run-mockbuild.sh
crun will now be built with both wasmedge and wasmtime support.
wasmtime on podman-next copr now provides wasm-library and a PR has been opened on the wasmedge Fedora package to do the same.
Currently, wasmtime is recommended given the wasmedge PR hasn't merged upstream and also because the crun build on podman-next copr has already been using wasmtime for quite some time now.
@giuseppe @flouthoc @rhatdan PTAL
cc @font
successful copr build at: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/5005481/
=> copr: crun-wasm subpackage

src/libcrun/linux.c
create the parent directory for devices nodes with mode 0755 so that the device file can be accessed when the container runs as non-root.
Closes: https://github.com/containers/crun/issues/1047
=> linux: create parent dir with 0755

rpm/crun.spec.in
wasmedge is available on f36, so build crun with wasmedge support for f36 and higher.
Also fix a comment about broken wasmtime copr build on rhel envs.
@giuseppe @rhatdan @flouthoc PTAL.
=> copr: enable wasmedge support for f36 and higher

src/libcrun/custom-handler.c, src/libcrun/custom-handler.h, src/libcrun/handlers/handler-utils.c, src/libcrun/handlers/krun.c, src/libcrun/handlers/mono.c, src/libcrun/handlers/wasmedge.c, src/libcrun/handlers/wasmer.c, src/libcrun/handlers/wasmtime.c
add an alias field to the handlers so that a different name can be
specified.  It is useful with the different handlers for wasm, so that
we can use a single name instead of the specific backend to use.
=> handlers: add an alias field

src/crun.c, src/crun.h, src/libcrun/container.c, src/libcrun/container.h
when a handler is used, rewrite the current process argv so that "ps auxw" shows more useful information instead of the command line used to launch the crun process.
e.g. when using the wasmedge handler with the michaelirwin244/wasm-example image, I see:
```
$ bin/podman --runtime crun-wasmedge run --rm -d michaelirwin244/wasm-example
5024ba547a40363de5a7c90d0d5f2748e56a5af6977aa8b9f06e0899493aa2a9
$ pgrep -fa libcrun
62149 [libcrun:wasmedge] hello_world.wasm
```
=> container: rewrite argv when using a handler

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, src/libcrun/utils.c, src/libcrun/utils.h
since we do not exec the container process when using a custom handler, we need to set the selinux label and the apparmor profile for the current process.
=> handlers: set selinux/apparmor profile

rpm/crun.spec.in
wasmedge is now available in the default epel9 repositories, so we're ok
to enable it here.
Ref: https://src.fedoraproject.org/rpms/wasmedge
Epel8 is currently WIP, and will hopefully get enabled soon.
@giuseppe @flouthoc @rhatdan PTAL
=> copr: enable wasmedge on epel9

src/libcrun/error.c
--debug to a file is kind of useless because of output buffering. This change adds setlinebuf to force each line of debugging output to be flushed as it is written under the assumption that if you are debugging you probably want to see the output in a timely manner.
=> Add setlinebuf() when --debug and --log=file: are used.

src/libcrun/handlers/krun.c
copy the OCI configuration used to create the container into the container rootfs as krun_config.json.
Closes: https://github.com/containers/crun/issues/1069
=> krun: copy the OCI configuration file

src/libcrun/linux.c, src/libcrun/utils.c, src/libcrun/utils.h
fix creating the default user namespace when the GID on the host is different than the UID and there is not not already a mapping specified in the OCI configuration.
Closes: https://github.com/containers/crun/issues/1072
=> utils: fix creating default userns

src/libcrun/utils.c
This print the full directory path up to and including cur, because after each iteration we restore the slash.
I had some problems with /dev/vboxusb permissions and an error message like
crun: mkdir `009`: Permission denied: OCI permission denied
isn't too useful while
crun: mkdir `dev/vboxusb/009`: Permission denied: OCI permission denied
actually pointed me where to look.
=> utils: Improve debug message

rpm/crun.spec.in
wasmedge is now available on epel8 so that means all active Fedora and
EPEL versions are covered.
Fedora 35 has been disabled on the copr, so we can simply remove this
extra conditional.
=> copr: enable wasmedge on all active envs

NEWS, src/checkpoint.c, src/crun.c, src/libcrun/cgroup-cgroupfs.c, src/libcrun/criu.c
- criu: hardcode library name to libcriu.so.2.
- cgroup: always enable all controllers, even if the cgroup was already joined.  Regression caused by crun-1.7.
=> NEWS: tag 1.7.2

src/libcrun/linux.c
Closes https://github.com/containers/crun/issues/1088
cc @giuseppe
=> crun: write setgroups=deny when mapping a single uid/gid

src/libcrun/utils.c
commit 0efbe561afb40023872bcc2db84c701a73dc4dc9 introduced the regression.  When we change the current AppArmor profile, it is necessary to use the command "changeprofile" instead of "exec".
Closes: https://github.com/containers/crun/issues/1093
=> utils: fix applying AppArmor profile

src/libcrun/cgroup-setup.c, src/libcrun/container.c
When mounting cgroups in legacy mode, flip the subsystems for `cpu/cpuacct` and `net_cls/net_prio` the same way it's done in [do_mount_cgroup_v1](https://github.com/containers/crun/blob/1.7.2/src/libcrun/linux.c#L1345-L1348). Otherwise it is not possible to create containers on older kernels (e.g. RHEL 7.9 with kernel 3.10.x):
```
117m        Warning   FailedCreatePodSandBox    Pod    Failed create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: open `/sys/fs/cgroup/cpu/kubepods/besteffort/pod32bebd55-7cc2-11ed-ac44-12842d37de17/8df53f6b7a0e16995e0ce70fe4ea47465f3bbe41c3e107d814db59036d71dea4`: No such file or directory: unknown
```
I apologize if the change is not something `crun` aims to support but …
=> fix cgroups mounting in legacy mode

src/crun.c
Fix the following build failure without `dlfcn.h` raised since version 1.7 and https://github.com/containers/crun/commit/5837234e9840cd067edd9f6cd2ed9cae9a0e6570:
```
src/crun.c:26:10: fatal error: dlfcn.h: No such file or directory
26 | #include <dlfcn.h>
|          ^~~~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/a5f52a7ee757c92c9571261c0ed884d05caeaf2f
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> src/crun.c: fix build without dlfcn.h

tests/cri-o/run-tests.sh
Most of these tests are failing with `Status from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix
/tmp/tmp.BqHEtTMiVU/crio.sock: connect: no such file or directory` which does not looks directly realted to crun.
=> cri-o,test: skip failing test unrelated to crun

contrib/seccomp-notify-plugin-example/full.c
Found a small leak while running static check on codebase, free(args) on error to prevent memory leak.
=> contrib, seccomp-notify-plugin: free `args` on error to prevent memory leak

src/libcrun/handlers/krun.c, src/libcrun/linux.c, src/libcrun/linux.h, src/libcrun/utils.c, src/libcrun/utils.h, tests/test_devices.py
when a user namespace is created, the user loses the ability of
creating device nodes thus only bind mounting them from the host is
permitted.  Precreate the device nodes on the host so that we can
honor the permissions and the file mode bits specified in the OCI
spec, create the mount from the host and then bind mount them into the
user namespace.
Closes: https://github.com/containers/crun/pull/1099
=> linux: precreate devices on the host

src/libcrun/linux.c, tests/test_mounts.py
when it is not possible to mount a fresh sysfs, we fall back to bind mounting /sys.
If a /sys/fs/cgroup is not present, just mask the path.
Otherwise restrict the usage of the fallback to the case where /sys is mounted read-only so we can take advantage of the new mount API and use 'rro'.
=> linux: mount cgroup ro on /sys bind mount fallback

src/libcrun/container.c, src/libcrun/linux.c
it should not be needed anymore as the kernel takes care of it, in fact I could not find any way to access the process /proc from within the container, but better play safe and enable it.
=> linux: set PR_SET_DUMPABLE

src/libcrun/cgroup-resources.c, src/libcrun/cgroup-setup.c
on cgroup v1, it is possible to pass the "noprefix" option for the cpuset mount and that causes the "cpuset." prefix to be dropped from the cgroup files.
To support this case, attempt to open the file without the prefix when the cpuset.$FILE version fails with ENOENT.
Closes: https://github.com/containers/crun/issues/1115
=> cgroup: support cpuset mounted with noprefix

src/libcrun/utils.c
a couple of fixes to reduce the number of allocations needed to read files.
more details in the individual commits.
=> utils: reallocate buffer only if needed

src/libcrun/linux.c, src/libcrun/utils.c, src/libcrun/utils.h, tests/centos8-build/run-tests.sh
accessing the /proc/$PID/fd/$FD paths is a common operation so refactor this pattern into a utility function.
We avoid having to have the same pattern in multiple places with the risk of using the wrong size for the buffer.
=> utils: add utils to access /proc/$PID/fd/$FD paths

src/libcrun/utils.c
another optimization for `read_all_fd`.  If the allocated buffer is bigger than what is actually used with the file data, then shrink its size before returning it so to reduce wasted memory.
=> utils: shrink read buffer if necessary

Makefile.am
do not include the binary test executables in the dist tarball.
Closes: https://github.com/containers/crun/issues/1126
=> dist: do not include binary tests

src/libcrun/linux.c
Move the call to prctl(PR_SET_DUMPABLE) after the creation of the user namespace otherwise it is not possible to create it when running as rootless (as it cannot write to the files under /proc).
commit 58166e6e23c93e24c1989b3a8060ad1b1387563c introduced the regression.
=> linux: move PR_SET_DUMPABLE after userns creation

crun.1, crun.1.md, src/libcrun/linux.c, src/libcrun/utils.c, src/libcrun/utils.h
Currently all containers with SELinux run with the context= mount option. This option prevents confined containers from running within a container. Changing this flag to fscontext= would allow confined containers within a container.
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
=> Support passing an attribute to change the mount_context_type

src/create.c, src/crun.c, src/libcrun/container.c, src/libcrun/custom-handler.c, src/libcrun/custom-handler.h, src/libcrun/handlers/krun.c, src/libcrun/handlers/mono.c, src/libcrun/handlers/wasmedge.c, src/libcrun/handlers/wasmer.c, src/libcrun/handlers/wasmtime.c, src/libcrun/linux.c, src/libcrun/linux.h, tests/cri-o/Dockerfile
so that it can be used from krun to always add /dev/kvm.
Closes: https://github.com/containers/crun/issues/1130
=> handlers: add new hook to modify the OCI configuration

src/libcrun/cgroup-systemd.c
if the unit could not be started, attempt to reset it first, and then start it again.
Closes: https://github.com/containers/crun/issues/1138
=> cgroup: reset systemd unit if start fails

crun.1, crun.1.md
Fix a small typo (ldopen vs. dlopen) I stumbled upon in the man page.
=> crun.1.md: fix typo

src/libcrun/cgroup-systemd.c, src/libcrun/cgroup-systemd.h, src/libcrun/container.c, tests/tests_libcrun_utils.c
commit 7ea76174986bf5e19715a43cdffff1724ee27236 caused a regression on cgroup v1, and some directories that are created manually are not cleaned up on container termination causing a cgroup leak.
Fix it by deleting the entire systemd scope directory instead of deleting only the final cgroup.
Closes: https://github.com/containers/crun/issues/1144
=> cgroup: rmdir the entire systemd scope

src/libcrun/linux.c
always use the direct mapping when writing the user namespace for an idmapped mount.  This is a breaking change but it is a fairly recent feature and it is only Podman using it.
=> linux: always use direct mapping

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, tests/cri-o/run-tests.sh, tests/test_exec.py
chown the tty to the user specified to the exec session instead of using the user specified in the container configuration.
Closes: https://github.com/containers/crun/issues/1158
=> libcrun: chown tty to the exec user

crun.1, crun.1.md, src/libcrun/cgroup-systemd.c, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h
add a new feature to the container runtime that allows users to set the scheduling policy of the container process.
The new feature is implemented as a custom annotation.  To set the scheduling policy and priority, users can add a `run.oci.scheduler` annotation with a value in the format POLICY[#PRIORITY].
If no scheduling policy or priority is specified, the container process will use the current scheduling policy and priority.
=> container: add custom annotation to specify the scheduler

src/libcrun/container.c
Might be a typo? The `tmp_err` is never released and the `err` should be handled by the caller.
=> libcrun_container_create(): fix memory leak

Makefile.am, crun.1, crun.1.md, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, src/libcrun/scheduler.c, src/libcrun/scheduler.h
replace sched_setscheduler() with sched_setattr().
The sched_setattr() function allows setting multiple attributes at once, including the scheduling policy, priority, runtime, deadline, period, and other scheduling options.  This feature provides more flexibility and control over the scheduling of processes within containers and can improve resource utilization and performance in specific use cases.
=> scheduler: use sched_setattr

src/libcrun/handlers/wasmedge.c
A similar feature was added to crun `wasmtime` (
https://github.com/containers/crun/pull/985 ) where we decided to `preopen` current directory for all the instances, this PR attempts same for `wasmedge`.
There is no generic external method so users can pass this to handler as discussed here: https://github.com/containers/crun/pull/985 but there is no need shown till now so idea is to proceed `.` as a default directory which whill be pre-opened.
Closes: https://github.com/containers/crun/issues/1170
=> wasm, wasmedge: add current directory to `preopen` paths

src/libcrun/cgroup-cgroupfs.c, src/libcrun/cgroup-utils.c, src/libcrun/cgroup-utils.h, src/libcrun/linux.c
when using cgroupfs, if there was no cgroup path specified in the OCI configuration and using the absolute path failed, e.g. because we are rootless and don't have access to it, then attempt to create a sibling cgroup.
Closes: https://github.com/containers/crun/issues/1173
=> cgroup: cgroupfs attempt new sibling cgroup

src/libcrun/scheduler.c
The newly introduced `src/libcrun/scheduler.c` by https://github.com/containers/crun/pull/1166 missing `#include <linux/sched.h>` for CentOS 7, which result with missing `SCHED_DEADLINE`.
Moreover, for CentOS 7 build we also need to enable `-std=c99`, or upgrade build tools to gcc 11 with `. /opt/rh/devtoolset-11/enable` before build.
See https://stackoverflow.com/a/50085457
See https://github.com/alvistack/containers-crun/blob/alvistack/1.8.2/crun.spec
=> [1.8.2][CentOS 7] Missing `#include <linux/sched.h>`

NEWS, src/libcrun/cgroup-systemd.c
update: initialize the rt_scheduler only on cgroupv1
5bdd93081f2d5f06594a24b1535e1e95a6d7c1aa introduced the regression
=> NEWS: tag 1.8.3

src/libcrun/criu.c
load only the functions that are actually used by crun.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2183041
=> criu: drop loading unused functions

Makefile.am, crun.1, crun.1.md, src/libcrun/linux.c, tests/test_time.py, tests/tests_utils.py
and drop the custom annotation
=> src: wire the runtime spec time namespace

tests/cri-o/Dockerfile, tests/test_mounts.py
adapt the test to follow the new semantic where the mapping used is the same as the user namespace.
Also drop the custom annotation tests, since now the feature is in the OCI specs.
=> tests: fix idmap mount test

src/libcrun/criu.c
check that the current libcriu library has the criu_join_ns_add function before attempting to use it.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2184221
=> criu: check if the criu_join_ns_add function exists

tests/test_mounts.py, tests/test_seccomp.py, tests/test_start.py, tests/tests_utils.py
In the Python tests, while there some support for setting a custom init path through the INIT environmental variable, there were a few places where this was hardcoded to "./tests/init".
Abstract it away into a new test_utils function, get_init_path(), mimicking the existing get_crun_path().
=> tests: abstract tests/init to get_init_path()

tests/test_exec.py
test_exec_write_pid_file() currently fails if the PID doesn't match a 5-character number ('\d{5}'). This can fail if the resulting PID is e.g. a 4-digit one. Accept any number of digits instead.
=> tests/test_exec: don't fail on PIDs < 10000

src/libcrun/container.c
No spaces before tabs (looks unintended), no leading whitespace (I think this is consistent with the last line of the literal).
=> Improve whitespace in generated `crun spec`

.github/workflows/test.yaml, src/libcrun/linux.c, src/libcrun/status.c, tests/cri-o/run-tests.sh
it is not as safe as using pidfd, but at least on systems where pidfd is not supported we reduce the time window where we can kill the wrong process.
Closes: https://github.com/containers/crun/issues/1200
=> linux: check the PID is valid before kill(2)

.github/workflows/test.yaml
`cri-o` tests are timing out due to unknown reason, disable it till we fix it.
=> ci: temporarily disable `cri-o` tests

src/libcrun/criu.c
the external string is allocated in two different places.
=> criu: fix memory leak

src/libcrun/terminal.c
When using a utility on a board and running it via a serial console, an issue arises where the output becomes corrupted after executing a command, rendering the terminal unusable.
Analyzing the strace output reveals that the code responsible for backing up the serial connection settings from the console's file descriptor restores them to file descriptor 0 instead of the intended console's file descriptor.
This circumstance leads to the problem at hand.
The proposed fix resolves this issue by addressing the aforementioned scenario.
=> Refactor: Restore serial settings for incorrect serial

src/libcrun/cgroup-setup.c, src/libcrun/cgroup-utils.c, src/libcrun/cgroup-utils.h
fix creating a cgroup under a "domain threaded" parent.  To do so, crun doesn't attempt anymore to enable threaded mode until the root, but it will do only for parent cgroups where it is necessary.
Closes: https://github.com/containers/crun/issues/1208
=> cgroups: fix creating cgroup under "domain threaded"

src/libcrun/container.c
if libcrun_set_scheduler or libcrun_set_io_priority fail, make sure the cleanup is performed.
=> container: do proper cleanup on errors

src/libcrun/cgroup-setup.c, src/libcrun/cgroup-utils.c, src/libcrun/cgroup.c, src/libcrun/container.c, src/libcrun/criu.c, src/libcrun/custom-handler.c, src/libcrun/error.c, src/libcrun/handlers/krun.c, src/libcrun/handlers/mono.c, src/libcrun/handlers/wasmedge.c, src/libcrun/linux.c, src/libcrun/seccomp.c, src/libcrun/status.c, src/libcrun/terminal.c, src/libcrun/utils.c
we were using a mix of '%s' and `%s`.  Convert any instance of the former style to use `%s` instead.
=> src: uniform the quoting style

.gitignore, Makefile.am, configure.ac, lua/README.md, lua/luacrun.rockspec
This PR includes changes for packing the lua binding library in luarocks, a popular package manager in lua world.
What's included in this PR:
- configure: `--enable-crun` and `--enable-libcrun` to control the installation of crun executable and libcrun (both are enabled by default)
- Makefile: added target `dist-luarock` to build source rocks for luarocks
=> lua: added luarocks packing

src/libcrun/io_priority.c
container.c (https://github.com/containers/crun/blob/main/src/libcrun/container.c#L2385 ) calls `libcrun_set_io_priority` even for users who built crun without the support of `io_priority` i.e when `autoconf ` fails to detect `linux/ioprio.h` and does not set `HAVE_LINUX_IOPRIO_H` and it returns error even when user has no intention of using it.
Following PR makes function no-op for such use cases.
Alternative patch could be
```diff
diff --git a/src/libcrun/container.c b/src/libcrun/container.c
index ff621bb..c5e53c9 100644
--- a/src/libcrun/container.c
+++ b/src/libcrun/container.c
@@ -2382,9 +2382,12 @@ libcrun_container_run_internal (libcrun_container_t *container, libcrun_context_
if (UNLIKELY (ret < 0))
goto fail;
-  ret = libcrun_set_io_priority (pid, def->process, err);
-  if …
```
=> libcrun: return with no-op when `io_priority` is NULL

tests/wasmedge-build/Dockerfile, tests/wasmedge-build/run-tests.sh
* After https://github.com/containers/podman/pull/18542 , podman does not
propagates annotations while running the image hence use `--platform
wasi/wasm`
----
* `fedora:rawhide` is having issues with the default `dnf.conf` being shipped so use `fedora:latest`.
```console
Config error: Parsing file "/etc/dnf/dnf.conf" failed: Parsing
file '/etc/dnf/dnf.conf' failed: IniParser: Missing section header at
line 1
```
Similar threads: https://www.spinics.net/lists/fedora-devel/msg312899.html
=> ci, wasmedge: use `--platform=wasi/wasm`

Makefile.am, src/crun.c, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/mount_flags.c, src/libcrun/mount_flags.h, src/oci_features.c, src/oci_features.h, tests/test_oci_features.py
Fixes: https://github.com/containers/crun/issues/1177
=> Implement crun features

src/ps.c
When pids is NULL, we should not try to access it.
Closes: https://github.com/containers/crun/issues/1239
=> ps: fix segfault with pids=NULL

tests/test_exec.py, tests/test_oci_features.py, tests/test_resources.py
I'm still pursuing the goal of running the upstream test suite as part of the Debian CI process (as outlined in #1197; also see prior work in #1194 & #1196). Below you'll find a few fixes to bugs I encountered in the process. With this PR everything except one test, sd-notify-proxy[1], runs in both rootful and rootless configurations.
Let me know what you think - thanks!
1: I'm still trying to track that down and I'm already seeing a few things in the test that don't make sense to me. A retroactive review and/or suggestions on what could possibly be going wrong are more than welcome :)
=> tests: more compatibility fixes

rpm/crun.spec
@giuseppe PTAL. Missed this change in the earlier PR.
=> RPM: Set Epoch only for Copr builds

src/libcrun/cgroup-resources.c, tests/test_resources.py
Runc accepts `0` value of `swap` from config as an exception case
* See: https://github.com/opencontainers/runc/blob/main/libcontainer/cgroups/fs2/memory.go#L36
* See: https://github.com/opencontainers/runc/blob/main/libcontainer/cgroups/utils.go#L431
As per the documentation here: https://facebookmicrosites.github.io/cgroup2/docs/memory-controller.html#using-swap Setting `memory.swap.max` to `0` is treated as `swap` being disabled hence allow `crun` to do the same.
Closes: https://github.com/containers/crun/issues/1001
=> cgroup-resources,cgroupv2: allow setting `memory.swap.max` to `0`

NEWS
- crun: new command "crun features".
- linux: fix handling of idmapped mounts when the container joins  an existing PID namespace.
- linux: support io_priority from the OCI specs.
- linux: handle correctly the case where the status file is not written yet for a container.
- crun: fix segfault for "ps" when the container is not using cgroups.
- cgroup: allow setting swap to 0.
=> NEWS: tag 1.8.6

rpm/crun.spec
When `copr_username` macro is not defined, `Epoch` is not set and `%{epoch}` macro expands to an empty string, which leads to invalid `Requires` tags (because their value starts with a colon). Fix that.
=> Make the spec file parseable without copr_username defined

src/oci_features.c
the crun_make_error function is not exported.
Closes: https://github.com/containers/crun/issues/1250
=> features: use exported function libcrun_make_error

rpm/crun.spec
These dependencies were already included in the official Fedora package but were not included in rpm/crun.spec currently used by copr and soon to be used for the official Fedora package.
Fixes: #1255
=> RPM: include criu dependencies

src/libcrun/linux.c
Use the error already created in the
helper function send_success_to_sync_socket()
=> linux: do not create error twice

src/libcrun/cgroup-setup.c
It looks the number `-1` should be something else so that it can be  avoided that
_crun_make_error()_ returns `0`. Is that a correct analysis?
I don't know which number would be a good replacement.
=> cgroup: fix error return value

src/libcrun/container.c
When receiving the WINCH signal, crun was using the default signal behavior of passing it through to the child process. A child that cared about the terminal size would then call the TIOCGWINSZ ioctl, but find the size had not changed. This is due to crun not copying the terminal size for its stdin to the child's pty.
This changeset handles the WINCH signal by getting crun's terminal size, and setting the child's pty to match. The WINCH signal is not passed through, as the kernel will send it as part of handling the TIOCSWINSZ ioctl.
=> libcrun: handle SIGWINCH by resizing terminal_fd

src/libcrun/linux.c
This caused an issue when the PID 1 didn't execve yet the container process, and joining the user namespace first would cause the user to look access to the container PID 1 namespaces.
When running with enough permissions, setns() will allow to join all the namespaces in one shoot, so let's use it.
On any error, attempt the fallback mechanism to join each namespace separately.
Closes: https://github.com/containers/crun/issues/1264
=> linux: simplify setns with pidfd

src/libcrun/container.c, src/oci_features.c, tests/test_oci_features.py
Hi!
While trying to use the output of the features subcommand with [go-runc](https://github.com/containerd/go-runc/) it fails to parse it. The failure is:
```
cannot unmarshal bool into Go struct field Features.annotations of type string: unknown
```
This patch just writes a string instead of a bool, and the output is parse fine. As I pointed out in the commit msg, it is worth to notice that the spec wording also mentions that a string is expected (i.e. is not a bug in the go-bindings in the runtime-spec).
=> Fix features formatting and implement OCI runtime-spec 1.1.0

NEWS
- linux: fix a race condition when an exec was performed
immediately after the start annd the setns with the procfd failed.
- features: Fix annotations formatting.
- linux: do not write some errors twice.
- libcrun: handle SIGWINCH by resizing the terminal file descriptor.
@flouthoc PTAL
=> NEWS: tag 1.8.7

src/libcrun/linux.c
the current code for creating idmapped mounts work only with bind mounts.  Extend it to support arbitrary mounts.
=> linux: support arbitrary idmapped mounts

src/libcrun/container.c, src/libcrun/container.h, src/oci_features.c, tests/test_oci_features.py
This PR upstream added the spec for the mountExtensions feature field:
https://github.com/opencontainers/runtime-spec/pull/1219
This commit just implements that and updates the OCI max version implemented to the one currently used in the spec (an unreleased version).
It is not clear if in the future, the version of unreleased specs will be changed to something else:
https://github.com/opencontainers/runtime-spec/pull/1221
But this is what is currently accepted.
---
Besides the tests here, I've also verified this against containerd integration tests.
cc @giuseppe
=> features: Support mountExtensions

src/libcrun/utils.c
Add an extra check to check that the fd is under the path.
I assume that the path separator is `/` as crun only runs on Linux.
=> utils: tighten check in check_fd_under_path()

src/libcrun/linux.c, tests/test_mounts.py
when ridmap is specified, apply recursively idmap to the mount.
=> linux: add support for ridmap mount option

Makefile.am, configure.ac, lua/README.md, lua/luacrun.rockspec
This PR fixes the directory structure for the luarocks package .
The incorrect structure (on luarocks 3.9.4):
```
lua_modules/lib64
└── lua
└── 5.4
├── lfs.so
├── lua
│   └── 5.4
│       ├── luacrun.a
│       ├── luacrun.la
│       └── luacrun.so
├── system
│   └── core.so
└── term
└── core.so
```
This PR added a new build option `--disable-lua-path-guessing` to place the files directly under the `$LIBDIR` from luarocks.
Corrected:
```
lua_modules/lib64/
└── lua
└── 5.4
├── lfs.so
├── luacrun.a
├── luacrun.la
├── luacrun.so
├── system
│   └── core.so
└── term
└── core.so
```
=> lua: fix the directory structure for the luarocks package

src/libcrun/linux.c
I don't know if this PR is correct. I'm doing a lot of guessing here.
I'm guessing that the array `joined_fds` is used to keep track of which namespaces have already been joined:
https://github.com/containers/crun/blob/3dc4ce9e2e9a83f7a6033dcb6b908aa2c3279f24/src/libcrun/linux.c#L4906-L4908
When an element is equal to `1`, `setns()` could be skipped.
=> linux: do not join already joined namespaces

src/libcrun/linux.c
do not write to the oom_score_adj only when the oom_score_adj value is not present in the spec file.
=> linux: fix check for oom_score_adj

src/libcrun/cgroup-systemd.c
According to the OCI runtime spec (https://github.com/opencontainers/runtime-spec/blob/main/runtime.md#delete), runtime's delete is supposed to remove all the container's artefacts.
In case systemd cgroup driver is used, and the systemd unit has failed (e.g. oom-killed), systemd won't remove the unit (that is, unless the "CollectMode: inactive-or-failed" property is set).
Leaving a leftover failed unit is a violation of runtime spec; in addition, a leftover unit result in inability to start a container with the same systemd unit name (such operation will fail with "unit already exists" error).
Call reset-failed from systemd's cgroup manager `destroy_cgroup` call, so the failed unit will be removed (by systemd) after "crun delete".
This change is similar to the one in runc (see …
=> crun delete: call systemd's reset-failed

src/libcrun/signals.c, src/libcrun/signals.perf
`strtol` will return 0 and not set errno
when handling a string which is not started with digital characters.
The old str2sig function failed to report invalid signal string input
and return signal 0.
I fix this little mistake.
Signed-off-by: black-desk <me@black-desk.cn>
=> fix: correctly handle unknow signal string

configure.ac, src/libcrun/linux.c, src/libcrun/seccomp.c
See https://github.com/containers/crun/issues/1298#issuecomment-1711193085
Fixes https://github.com/containers/crun/issues/1298
=> Fix CentOS 7 Build by Checking if FSOPEN_CLOEXEC exists

src/libcrun/utils.c
commit 5d1f903f75a80daa4dfb3d84e114ec8ecbf29956 in the kernel, present in a release since Linux 6.6 doesn't allow anymore to change the mode of a symlink, so just ignore the failure.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5d1f903f75a80daa4dfb3d84e114ec8ecbf29956
Closes: https://github.com/containers/crun/issues/1308
=> utils: ignore ENOTSUP when chmod a symlink

src/libcrun/linux.c, tests/test_mounts.py
if the mount fails with EBUSY, attempt to mount it to a temporary directory under the state directory and then move it to the correct destination with MS_MOVE.
=> linux: add new fallback when mount fails with EBUSY

src/libcrun/utils.c
when creating a directory, if any component of the path is not a directory, report it as part of the error message.
Forcing O_DIRECTORY for any component that we expect to be a directory, will force the kernel to report the error earlier instead of failing at the next mkdir(2) call.
Closes: https://github.com/containers/crun/issues/1307
=> utils: improve error message for ensure_dir

src/libcrun/linux.c
523eed3f0f4b3ba59f002fae3fb95f7d570115e3 introduced the regression. If the mkdir fails, still attempt the other mechanisms to create the cgroupv2 mount.
=> linux: fix fallback mechanism in a userns

NEWS
- cgroup: reset the inherited cpu affinity after moving to cgroup.  Old kernels do that automatically, but new kernels remember the affinity that was set before the cgroup move, so we need to reset it in order to honor the cpuset configuration.
=> NEWS: tag 1.9.2

src/libcrun/linux.c
extend the condition for opening bind mounts in the parent process to the case where the crun process itself is running inside a user namespace.  In this way the source path is opened before doing the setgroups(2) syscall and potentially losing access to directories that are accessible only by group permission.
Closes: https://github.com/containers/crun/issues/1320
=> linux: open mounts before setgroups if in a userns

Makefile.am, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/intelrdt.c, src/libcrun/intelrdt.h, src/libcrun/linux.c, src/libcrun/linux.h, src/libcrun/status.c, src/libcrun/status.h, src/oci_features.c, src/update.c, tests/fuzzing/run-tests.sh, tests/tests_libcrun_fuzzer.c, tests/tests_libcrun_intelrdt.c
add support for intel RDT as specified in the OCI runtime specs.
=> Intel RDT support

src/libcrun/linux.c
On Ubuntu 22.04.3, gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0:
CC       src/libcrun/libcrun_la-linux.lo
src/libcrun/linux.c: In function 'libcrun_create_keyring':
src/libcrun/linux.c:747:12: warning: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
747 |     (void) write (labelfd, "", 0);
|            ^~~~~~~~~~~~~~~~~~~~~~
CCLD     libcrun.la
CCLD     crun
CC       src/libcrun/libcrun_testing_a-linux.o
src/libcrun/linux.c: In function 'libcrun_create_keyring':
src/libcrun/linux.c:747:12: warning: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
747 |     (void) write (labelfd, "", 0);
|            ^~~~~~~~~~~~~~~~~~~~~~
Move the 'write' to 'if' statement to do check for avoid the warning.
=> linux: Fix -Wunused-result compiler warnings when run './configure' only

crun.1, crun.1.md, src/libcrun/linux.c, src/libcrun/mount_flags.c, src/libcrun/mount_flags.h, src/libcrun/mount_flags.perf, src/libcrun/utils.c, src/libcrun/utils.h, tests/init.c, tests/test_mounts.py, tests/test_oci_features.py, tests/test_start.py
provide an option to copy the original symlink instead of dereferencing it.  This requires a new mount flag, which is handled directly by crun and not passed down to the kernel.  When "copy-symlink" is found, if the source of a mount is a symlink, then crun creates the symlink at the destination instead of attempting a mount(2).
=> linux: new mount option "copy-symlink"

NEWS
- support for Intel Resource Director Technology (RDT).
- new mount option "copy-symlink".  When provided for a mount, if the source is a symlink, then it is copied in the container instead of attempting a mount.
- linux: open mounts before setgroups if in a userns.  This solves a problem where a directory that was previously accessible to the user, become inaccessible after setgroups causing the bind mount to fail.
=> NEWS: tag 1.10

src/libcrun/linux.c, tests/init.c, tests/test_mounts.py, tests/test_start.py, tests/tests_utils.py
For tmpfs type mounts, ensure that a mode is appended to the mount data if it is not already present.  The function checks the existing directory and appends the mode based on the file permissions of the source path at the rootfs.  This helps in preserving the intended file permissions when overriding a directory with a new tmpfs file system.
Closes: https://issues.redhat.com/browse/RHEL-14469
Closes: https://github.com/containers/crun/issues/1330
=> linux: append tmpfs mode if missing for mounts

NEWS, src/libcrun/linux.c, tests/test_mounts.py
When the bind mounts are created in the parent environment, we must force a remount operation to set all the flags we need.
commit 122f8aedad237ae242b504707e9fcd2185dc3a44 introduced the regression when running inside a user namespace.
This causes a regression in the Podman CI.
Closes: https://github.com/containers/crun/issues/1335
=> linux: force remount with mounts from parent

src/libcrun/terminal.c
ptsname_r has been adopted by POSIX and is specified to return an error number on failure[1].  Thus check that the return value is != 0 rather than < 0.
[1] https://www.austingroupbugs.net/view.php?id=508
=> terminal: adopt ptsname_r POSIX specified return value

src/libcrun/utils.c
While going through the source code, #include <stdarg.h> is mentioned in multiple places within the same file.
=> Remove the redundant header file #include <stdarg.h>

src/libcrun/cgroup-resources.c
fix a crash when running on cgroup v1 and cpu resources are not set in the configuration file.
commit 5a0ede20fdd73c6de09d8c07b4ba2ea410fbb7cb introduced the regression.
Closes: https://github.com/containers/crun/issues/1338
=> cgroup: fix crash on cgroup v1 without cpu resources

.clang-format, NEWS, src/libcrun/cloned_binary.c, src/libcrun/linux.c
- fix a regression caused by 1.11.1 where the process crashes if there are no CPU limits configured on cgroup v1.
- fix error code check for the ptsname_r function.
=> NEWS: tag 1.11.2

src/libcrun/cgroup-systemd.c
configure the cpu rt and cpuset controllers before joining them.  This avoids running (even temporarily) the workload on cpus it was not supposed to run on.
=> systemd, cgroup: configure cgroups before joining them

src/libcrun/container.c
The work to support features introduced another point of dependency on
libcap that previously wasn't guarded by ifdefs
Refs: https://github.com/containers/crun/pull/1237
Signed-off-by: Robert Günzler <r@gnzler.io>
=> Fix build without libcap

src/libcrun/cgroup-systemd.c
if the connection to the user session fails, attempt to connect to the system bus.
Closes: https://github.com/containers/crun/issues/1346
=> systemd: fallback to system bus

src/libcrun/container.h
dereference the pointer only after it has been checked.
=> container: move dereference after check

Makefile.am, configure.ac, src/libcrun/custom-handler.c, src/libcrun/handlers/spin.c
This PR adds a new handler to crun. [Spin](https://developer.fermyon.com/spin/) is a framework for building and running event-driven microservice applications using WebAssembly (Wasm) components.
The spin handler expects the spin cli to be located at `/usr/local/bin/spin' and that it is a statically compiled binary with no shared library dependencies. There is a [demo repository](https://github.com/0xE282B0/spin-openshift) that was used to demonstrate running a spin application on OpenShift in the "Running Spin Wasm Apps on OpenShift" session at the OpenShift Commons Gathering NA 2023.
For testing, there are prebuilt binaries for x86_64 and aarch64 in the demo repository, as well as the [install script](https://github.com/0xE282B0/spin-openshift/blob/main/x86_64/installer.sh) that is used …
=> feat: add spin handler

README.md
The crun Nix channel information is old, and will show "Wrong channel selected!".
=> README.md: update the correct Nix channel

src/libcrun/cgroup-internal.h, src/libcrun/cgroup-setup.c, src/libcrun/cgroup-systemd.c
if we already know the cpuset, then we should preconfigure the newly created cgroup with those values, instead of using the parent's set. This prevents needless churn in the kernel as it tracks which CPUs have load balancing disabled.
=> preconfigure cpuset with required resources

NEWS
- add new WebAssembly handler: spin.
- systemd: fallback to system bus if session bus is not available.
- configure the cpu rt and cpuset controllers before joining them to avoid running temporarily the workload on the wrong cpus.
- preconfigure the cpuset with required resources instead of using the parent's set.  This prevents needless churn in the kernel as it tracks which CPUs have load balancing disabled.
- try attr/<lsm>/* before the attr/* files.  Writes to the attr/* files may fail if apparmor is not the first "major" LSM in the list of loaded LSMs (e.g. lsm=apparmor,bpf vs lsm=bpf,apparmor).
=> NEWS: tag 1.12

src/libcrun/linux.c
the error refers to a fork failure, not setsid.
=> linux: fix error string

src/libcrun/handlers/spin.c
Fix the build with "./configure CFLAGS='-Wall -Wextra -Werror' --with-spin=yes"
src/libcrun/handlers/spin.c: In function 'spin_load':
src/libcrun/handlers/spin.c:55:19: error: unused parameter 'cookie' [-Werror=unused-parameter]
55 | spin_load (void **cookie, libcrun_error_t *err)
|            ~~~~~~~^~~~~~
src/libcrun/handlers/spin.c: In function 'spin_unload':
src/libcrun/handlers/spin.c:93:20: error: unused parameter 'cookie' [-Werror=unused-parameter]
93 | spin_unload (void *cookie, libcrun_error_t *err)
|              ~~~~~~^~~~~~
src/libcrun/handlers/spin.c:93:45: error: unused parameter 'err' [-Werror=unused-parameter]
93 | spin_unload (void *cookie, libcrun_error_t *err)
|                            ~~~~~~~~~~~~~~~~~^~~
cc1: all warnings being treated as errors
=> handlers: Fix -Werror=unused-parameter build error for spin

src/libcrun/criu.c
these fds must be passed to the child process.
commit 3ad89be2dcdfbd788ab1d6298845baf43b2b2c28 was overzealous and introduced the regression.
Closes: https://github.com/containers/crun/issues/1367
=> criu: do not set CLOEXEC on fds to inherit

src/create.c, src/libcrun/container.h, src/run.c
it was initially added for compatibility with runc but it was never implemented, so let's clean it up.
Closes: https://github.com/containers/crun/issues/1369
=> ctx: drop no_subreaper bool

src/libcrun/linux.c
id mapped mount is specified in terms of `host_filesystem_id:maped_id:range` or `@host_filesystem_id:container_id:range`. When looking up the relative container_id, one should check value[1] (the id we map to) instead of value[0] (the id we map from).
---
I realized the bug when trying to do thing described in containers/podman#20960. I was doing something like `idmap=uids=@1000-0-1` hoping to let uid 0 in container capable to access files owned by uid 1000 on disk, while I got the error:
```
Error: could not find a user namespace mapping for the relative mapping "@1000-0-1"
```
that doesn't make sense.
=> fix checking of relative idmapped mount

src/libcrun/container.c
The compiling happens when the --disable-caps and --disable-seccomp was given in configure. Add HAVE_CAP and HAVE_SECCOMP flags in container.c
=> libcrun: fix compile error without libseccomp and libcap

src/libcrun/error.c
Quote from
https://www.kernel.org/doc/man-pages/online/pages/man3/vasprintf.3.html
"_If memory allocation wasn't possible, or some other error occurs, these functions will return -1, and the contents of strp are undefined._"
Is there a need to reset the pointer?
=> error: reset pointer after vasprintf failure

src/libcrun/cgroup-resources.c, tests/test_limits.py
use the value "max" also on cgroup v1 when the pids limit specified is < 0.
=> cgroup: use "max" when pids limit < 0

src/libcrun/linux.c, src/libcrun/utils.c, src/libcrun/utils.h
In case crun is confined under apparmor and no_new_privileges flag set for containers,
the only way apparmor allows a change of profile is when a profile is stacked on top of current profile to ensure no new permissions are gained
=> apparmor: stack apparmor profiles if nnp and confined

src/libcrun/container.c, tests/test_devices.py, tests/tests_utils.py
it ensures that the `mknodat` syscall is not affected by the umask of the calling process, allowing file permissions to be set as specified in the OCI configuration.
Closes: https://github.com/containers/crun/issues/1389
=> linux: force umask(0)

Makefile.am, README.md, cfg.mk, configure.ac, nix/derivation.nix, nix/overlay.nix, src/libcrun/blake3/LICENSE, src/libcrun/blake3/blake3.c, src/libcrun/blake3/blake3.h, src/libcrun/blake3/blake3_impl.h, src/libcrun/blake3/blake3_portable.c, src/libcrun/seccomp.c, tests/alpine-build/Dockerfile, tests/centos8-build/Dockerfile, tests/centos9-build/Dockerfile, tests/containerd/Dockerfile, tests/cri-o/Dockerfile, tests/fuzzing/Dockerfile, tests/podman/Dockerfile, tests/wasmedge-build/Dockerfile
alternative to https://github.com/containers/crun/pull/1393
=> Drop gcrypt dependency and use blake3

src/libcrun/cgroup-systemd.c
fix a segfault when the "resources" block is not specified and '--systemd-cgroup' is used.
Closes: https://github.com/containers/crun/issues/1402
=> cgroup, systemd: fix segfault if resources not specified

src/libcrun/ebpf.c
commit 93064574a09df639f5f66f73733f41a9b611109b was too eager to use the same fallback with a log, and that could fail for other reasons (e.g. not enough buffer space).  Add a fallback without using the log, so that on kernels older than 5.11 we have a better chance of success.
Closes: https://github.com/containers/crun/issues/1400
=> ebpf: add fallback when bpf(2) fails

src/libcrun/utils.c
makes https://github.com/containers/crun/pull/1408 and https://github.com/containers/crun/pull/1406 unnecessary
Closes: #1385
=> apparmor: Fix wrong determination whether crun is confined

src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h
there was recently a security vulnerability (CVE-2024-21626) that allowed a malicious user to chdir(2) to a /proc/*/fd entry that is outside the container rootfs.  While crun is not affected directly, harden chdir by validating that we are still inside the container rootfs.
=> linux: harden chdir

python/crun_python.c
Hi there,
I was playing around with the Python API a bit and noticed that in `make_context()`
- parameter names used dashes, making them invalid Python identifiers, and that
- a few boolean flags offered by `libcrun_context_t` were missing. (*)
My changes fix the above issues. 
*) As are a couple other non-boolean parameters but since I lack experience with both crun and the Python C API I wanted to focus on the simple cases first.
Since this is my first PR, please let me know if there's anything that's missing or there are any contribution guidelines I should follow. (I couldn't find anything in the README.)
PS: Seeing that tests for the crun CLI are written in Python, would it make sense to also add Python tests for the Python API?
=> Improve Python API

src/libcrun/container.c
there is no advantage in doing it, so just drop it.
=> crun: drop check for OCI version

rpm/crun.spec
Currently, the Fedora Packaging Guidelines don't choose sides between absolute and relative symbolic links [1], but RPM does [2,3].  Building the crun RPM with absolute symlinks leads to:
```
...
warning: absolute symlink: /usr/bin/krun -> /usr/bin/crun
...
warning: absolute symlink: /usr/bin/crun-wasm -> /usr/bin/crun
...
RPM build warnings:
absolute symlink: /usr/bin/krun -> /usr/bin/crun
absolute symlink: /usr/bin/crun-wasm -> /usr/bin/crun
...
```
Given the prevalence of chroot-like environments these days due to bind mounts in containers, relative symbolic links do look like the better alternative, and various prominent parts of the operating system already use them.  Some examples:
* /etc/localtime -> ../usr/share/zoneinfo/Europe/Prague
* /etc/mtab -> ../proc/self/mounts
* …
=> rpm: Use relative, not absolute, symbolic links

.packit.yaml
Packit posts an additional failure notification comment if the latest failure message does not match the previous notification comment.
This commit reuses the non-RHEL failure notification comment on RHEL tests. This should reduce the number of failure messages posted on a PR.
For reference, see the alternating failure messages on #1425 for RHEL and non-RHEL.
=> Packit: reuse non-RHEL failure message notification on RHEL

rpm/crun.spec
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2271814
wasmedge is enabled for all official Fedora and for all copr build jobs.
=> rpm: remove eln macro

src/libcrun/linux.c
The check for "unreachable" for better error message won't work because of the missing parentheses, i.e. it needs to be "(unreachable)" (as the comment says).
Fixes: adb912d ("linux: harden chdir()")
=> linux: fixup libcrun_safe_chdir

src/libcrun/container.c, src/libcrun/container.h, src/oci_features.c, tests/test_oci_features.py
list generated by finding all instances of `find_annotation`
(note to reviewer: I don't know if they're all unsafe and I probably will  end up omitting some, per your request)
=> features: add support for potentiallyUnsafeConfigAnnotations

src/libcrun/io_priority.c
- update libocispec to [c715dcdbab8fe592daa8a11cbabc75aa76534c80](https://github.com/containers/libocispec/commit/c715dcdbab8fe592daa8a11cbabc75aa76534c80)
- rename class to _class
=> libocispec: update

nix/default-s390x.nix, nix/derivation.nix
Building using musl until NixOS/nixpkgs#306473 is resolved.
Refers to https://github.com/cri-o/cri-o/issues/7911
=> Build s390x binaries using musl libc

src/libcrun/linux.c, src/libcrun/status.c
This fixes a regression introduced in crun 1.9.1 with https://github.com/containers/crun/commit/523eed3f0f4b3ba59f002fae3fb95f7d570115e3
When running a container with /sys/fs/cgroup already mounted (e.g. --volume=/sys:/sys) and another shared volume somewhere (e.g. --volume=/mnt:/mnt:shared), the move mount fails with EINVAL:
```
mount("/run/crun/6d75ef05e540486f21ef54743f8af97f4dff0d0d7c54d9b7852cd5302e884db8/tmpmount", "/proc/self/fd/8", NULL, MS_MOVE, NULL) = -1 EINVAL (Invalid argument)
```
This leaves tmpmount as a mountpoint behind, which then fails to cleanup:
```
openat(AT_FDCWD, "/run/crun", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 3
openat(3, "0d1342f7a7375593813287c743170bb71f30f9a64fa8bc141d3cf9b8e9aa5a89", O_RDONLY|O_DIRECTORY) = 4
unlinkat(4, "tmpmount", 0) = -1 EISDIR (Is a …
```
=> Fix cleanup of /run/crun state dir when cgroup failed to mount

.packit.yaml
This commit enables downstream syncing to centos 10 stream on every upstream release. The centos maintainer will need to run `packit propose-downstream` and `centpkg build` manually until better packit-centos integration is in place.
This commit will also allow ensure that centos stream tests are run using rpms built on centos stream envs and rhel tests are run using rpms built on rhel/epel environments.
=> Packit: Enable c10s downstream sync, rhel / centos separation in tests

NEWS
- fix a mount point leak under /run/crun, add a retry mechanism to
unmount the directory if the removal failed with EBUSY.
- linux: cgroups: fix potential mount leak when /sys/fs/cgroup is
already mounted, causing the posthooks to not run.
- release: build s390x binaries using musl libc.
- features: add support for potentiallyUnsafeConfigAnnotations.
- handlers: add option to load wasi-nn plugin for wasmedge.
- linux: fix "harden chdir()" security measure.  The previous check
was not correct.
- crun: add option --keep to the run command.  When specified the
container is not automatically deleted when it exits.
Closes: https://github.com/containers/crun/issues/1458
=> NEWS: tag 1.15

src/libcrun/linux.c, tests/init.c, tests/test_mounts.py
open the mount target with O_PATH to prevent open(2) failures with special files like FIFOs or UNIX sockets.
Closes: https://github.com/containers/crun/issues/1463
=> linux: fix mount of special files with rro

src/run.c
Commit 49f439d ("ctx: drop no_subreaper bool") did that for create but not for run. Fix it.
=> crun run --help: say --no-subreaper is ignored

src/run.c
Starting from b3e167dbcda8fe25c26285c4c9f96f2735f1054f the handler is already set in `init_libcrun_context`.
=> [crun run] Avoid setting crun_context.handler redundantly

src/libcrun/cgroup-systemd.c
fix the following warning when setting the memorylimit on the systemd unit:
systemd[4299]: crun-foo.scope: cgroup-compat: Applying MemoryLimit=10000000 as MemoryMax=
Closes: https://github.com/containers/crun/issues/1489
=> cgroup: use MemoryMax instead of MemoryLimit

src/restore.c
This pull request updates the description for the `--console-socket` option of the `restore` command for consistency with other crun commands (see https://github.com/containers/crun/commit/65aa6bbeb356e5f757ac046a43c0e21ef8a33c9d).
=> restore: update console-socket option description

nix/default-s390x.nix
Fixes #1494 
I also removed the comment to "switch back", which we probably will never do.
=> Enable systemd in s390x builds

src/libcrun/cgroup-systemd.c
This fix changes the error handling for `sd_bus_message_append` execution for two cases:
- update of cpu-quota,
- update of cpu-period.
The previous code was checking wrong variable to determine error and to return the error code downstream.
The bug has been spotted during occasional code review and was not confirmed in any real case scenario. To reproduce the bug I had to modify the source code to trick `sd_bus_message_append` to fail by providing invalid 2nd argument, e.g.
```
- sd_err = sd_bus_message_append (m, "(sv)", "CPUQuotaPerSecUSec", "t", quota);
+ sd_err = sd_bus_message_append (m, "-invalid-value-", "CPUQuotaPerSecUSec", "t", quota);
```
and then run 
```
crun --cgroup-manager=systemd  update --cpu-quota=50000 --cpu-period=100000 <container-id>
```
In this case `crun` should …
=> Fix sd-bus error handling for cpu quota and period props update.

src/libcrun/cgroup-systemd.c
Check if sd_bus_message_append() returns an error.
=> cgroup-systemd: check for sd_bus_message_append error

src/libcrun/cgroup-systemd.c
The comment does not correctly describe the code.
One way to fix it could be 
```diff
diff --git a/src/libcrun/cgroup-systemd.c b/src/libcrun/cgroup-systemd.c
index e997285..b3ea1e9 100644
--- a/src/libcrun/cgroup-systemd.c
+++ b/src/libcrun/cgroup-systemd.c
@@ -878,7 +878,7 @@ append_resources (sd_bus_message *m,
if (resources->cpu)
{
-      /* do not bother with systemd internal representation if both values are not specified */
+      /* do not bother with systemd internal representation if not both values are specified */
if (resources->cpu->quota && resources->cpu->period)
{
uint64_t quota = resources->cpu->quota;
```
To make it sound more English, I replaced `if not` with `unless`
=> cgroup-systemd: fix comment

src/libcrun/cgroup-utils.c
=> cgroup-utils: check for open error

src/libcrun/cgroup.c
The check got duplicated in this git commit ce7dedf98c0a1ba2845747950504beaedfe0bb1b
"_cgroup: move returned data to different struct_"
I guess one of the checks could be removed.
=> cgroup: remove redundant check

src/libcrun/container.c
The user should be inherited in the same way as various other fields. This allows to run exec sync with the same user as the original process without a need to specify it explicitly using the CLI or process.json.
Fixes https://github.com/containers/crun/issues/1516
=> Inherit user from original process on exec

NEWS, src/libcrun/container.c, src/libcrun/linux.c
commit 66824320e3fe9b36e94b3f54d77779da498c6b2b introduced the regression.  After that change, crun does not attempt anymore to make the rootfs directory private but starts from its parent directory, causing pivot_root to fail when the rootfs itself is a mountpoint.
Closes: https://github.com/containers/crun/issues/1514
=> linux: attempt to make rootfs private too

src/libcrun/cgroup-systemd.c
The issue with DefaultDependencies being set to 'no' instead of 'yes' was caused by the order of the code. The annotations were being processed before setting the DefaultDependencies property, which allowed crun's default behavior to override the CRI-O annotation.
Here's the test with this fix.
```sh
$ sudo crictl run test/testdata/container_sleep.json test/testdata/sandbox_config.json 
DEBU[0000] get image connection                         
DEBU[0000] get runtime connection                       
90439cccfb277148f31a7e5b1c79a2188931e88e3831733b6a0b83330832fc18
$ systemctl show crio-90439cccfb277148f31a7e5b1c79a2188931e88e3831733b6a0b83330832fc18.scope | grep "Default*"
DefaultMemoryLow=0
DefaultStartupMemoryLow=0
DefaultMemoryMin=0
DefaultDependencies=yes
```
=> src/libcrun: ensure DefaultDependencies respects CRI-O annotation

src/libcrun/container.c, src/libcrun/terminal.c, src/libcrun/terminal.h
Since https://github.com/containers/crun/pull/1214 it is a no-op and does nothing more than call set_raw.
This does change the public interface of libcrun / break backwards compatibility.
=> Remove libcrun_setup_terminal_ptmx

src/libcrun/linux.c
Follow-up to https://github.com/containers/crun/pull/1532
Addressing CI failures: https://github.com/containers/crun/actions/runs/10595280805/job/29360698730
=> [WIP] src/libcrun: fix error handling in libcrun_kill_linux

nix/derivation.nix
This should fix the wrong dlopen search path mentioned in https://github.com/cri-o/cri-o/issues/8518
=> Add autoPatchelfHook to static build

src/crun.c
We should log only after the context setup, otherwise we may use the wrong format or target.
=> Log only after crun context has been setup

src/libcrun/container.c
Because the user is assigned by reference, the process struct cleanup in `crun_command_exec` was doubly freeing the `process->user` pointer, which was previously freed by the container struct cleanup in `libcrun_container_exec_with_options`.
Fixes https://github.com/containers/crun/issues/1537
=> Fix double-free of process user in crun exec

crun.1, crun.1.md, src/crun.c, src/crun.h, src/libcrun/error.c, src/libcrun/error.h
This option was inherited before, but now we can set it explicitly to allow/disallow logging to stderr when selecting a certain log driver.
For example on exec, we would need to log log anything to stdio even when the debug logs are enabled.
Refers to https://github.com/containers/crun/issues/1525
=> Add `--log-stderr` option

src/libcrun/error.c
The ID has been dropped before this patch, but we can use it to refer a container ID or anything else identifiable.
Will be used by conmon-rs in https://github.com/containers/conmon-rs/pull/2401/files#diff-5d1350be7d73e8dfd3f43f70d9d71838500a7c04b2ee5ee19f1c4521f9df7d12R395
Refers to https://github.com/containers/crun/issues/1525
=> Allow passing an ID to journald log driver

src/libcrun/container.c
The size needs to be set as well otherwise we may break `additional_gids`.
Found in critest, like: https://github.com/cri-o/cri-o/actions/runs/10680190170/job/29601173374
```
Summarizing 3 Failures:
[FAIL] [k8s.io] Security Context SupplementalGroupsPolicy when SupplementalGroupsPolicy=Strict [It] even if the container's primary UID belongs to some groups in the image, runtime should not add SupplementalGroups to them
sigs.k8s.io/cri-tools/pkg/validate/security_context_linux.go:737
[FAIL] [k8s.io] Security Context bucket [It] runtime should support SupplementalGroups
sigs.k8s.io/cri-tools/pkg/validate/security_context_linux.go:309
[FAIL] [k8s.io] Security Context SupplementalGroupsPolicy when SupplementalGroupsPolicy=Merge (Default) [It] if the container's primary UID belongs to some …
```
=> Fix `additional_gids_size` on `process_user_dup`

src/libcrun/linux.c
Fixes: https://github.com/containers/crun/issues/1531
=> linux: fix recvfrom error handling

src/crun.c, src/libcrun/container.c, src/libcrun/error.c, src/libcrun/error.h, tests/clang-format/run-tests.sh
In any other case we log to the dedicated log driver for consistency reason. This avoids having another option like `--log-stderr`.
Needs https://github.com/containers/crun/pull/1545
Alternative to https://github.com/containers/crun/pull/1542
=> Only log to stderr if `--log` is not provided

src/libcrun/utils.c
getpwuid_r returns the error directly, not -1. In a situation with no /etc/passwd for example, ret is ENOFILE (2) and so the branch is never taken, resulting in a runaway realloc loop
Closes: https://github.com/containers/crun/issues/1536
=> fix getpwuid_r error handling

src/libcrun/container.c
This allows to pass the error (as others) through the tty and not lose it.
Fixes https://github.com/containers/crun/issues/1524
=> Report executable not found errors after tty has been setup

src/libcrun/linux.c, src/libcrun/utils.c, src/libcrun/utils.h, tests/test_devices.py
This change handles device paths with trailing slashes correctly. It address the following issue when we use `crun` as the default container runtime:
```sh
Error: container create failed: mknod `/mnt/`: No such file or directory .
```
=> src/libcrun: fix handling of device paths with trailing slashes

src/libcrun/linux.c
This fixes the warning while ignoring the return result of `chdir`:
```
src/libcrun/linux.c:5769:14: warning: ignoring return value of 'chdir' declared with attribute 'warn_unused_result' [-Wunused-result]
5769 |       (void) chdir ("/");
```
=> Fix warning around unused result on chdir("/")

src/libcrun/utils.c
ignore EPIPE when writing to the hook stdin, as the hook process could already have been terminated.
Closes: https://github.com/containers/crun/issues/1551
=> linux: ignore EPIPE for hooks

src/libcrun/error.c
it solves the following error:
$ crun --log-level foo run foo
2024-09-05T21:13:00.024172Z: unknown verbosity `foo` specified
2024-09-05T21:13:00.024273Z: unknown verbosity `foo` specified
@saschagrunert PTAL
=> error: do not write error twice to stderr

src/create.c, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/status.c, src/libcrun/utils.c
Demo:
```
> sudo ./crun --log-level=debug create ctr
2024-09-06T07:58:53.348572Z: Using debug verbosity
2024-09-06T07:58:53.348597Z: Loading container from config file: config.json
2024-09-06T07:58:53.348678Z: Using bundle: /home/sascha/git/crun
2024-09-06T07:58:53.348682Z: Creating container: ctr
2024-09-06T07:58:53.348688Z: Checking run directory: /run/crun
2024-09-06T07:58:53.348706Z: Creating exec fifo: /run/crun/ctr/exec.fifo
2024-09-06T07:58:53.348717Z: Running with prefork enabled
2024-09-06T07:58:53.348722Z: Reading config file: config.json
2024-09-06T07:58:53.348733Z: Writing config file to: /run/crun/ctr/config.json
2024-09-06T07:58:53.348745Z: Creating new keyring
2024-09-06T07:58:53.348759Z: Using cgroupfs cgroup manager
2024-09-06T07:58:53.348762Z: Using container host UID 0 …
```
=> Add debug logs for container creation

NEWS
=> NEWS: tag 1.17

.packit.yaml
Packit's propose-downstream failed[0] for crun 1.17 because packit wasn't able to create `tests/tmt` path structure in the downstream repo[1]. 
[0]: https://github.com/containers/crun/issues/1558
[1]: https://dashboard.packit.dev/jobs/propose-downstream/10800
Using `mkpath: true` will create missing path components if any.
Ref: https://packit.dev/docs/configuration#files_to_sync
Fixes: #1558
=> Packit: Create missing path components in files_to_sync

rpm/crun.spec
Sources for the changes: http://fedora.riscv.rocks:3000/rpms/crun/src/branch/main-riscv64
Latest successful riscv64 build: http://fedora.riscv.rocks/koji/buildinfo?buildID=305890
=> Disable criu support on riscv64

src/oci_features.c
When crun is compiled after configuring with `--disable-seccomp`, running `crun features` subcommand segfaults.
This happens, because crun tries to add `actions` and `operators` arrays to the printed JSON, but those arrays are actually NULLs. Their initialization is guarded by `#ifdef HAVE_SECCOMP` in `libcrun_container_get_features`.
Guarding their addition to the JSON with ifdef solves the issue. I also guarded `libseccomp.version` annotation with the same ifdef.
=> Fix segfault in `crun features`

.packit.yaml
Without this constraint, packit creates duplicate jobs when running downstream jobs. This does not affect upstream.
=> Packit: constrain koji and bodhi jobs to the fedora package

src/libcrun/cgroup-internal.h, src/libcrun/cgroup-resources.c, src/libcrun/cgroup-resources.h, src/libcrun/cgroup-systemd.c, src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c, src/libcrun/linux.c, src/libcrun/linux.h, src/libcrun/utils.c, src/libcrun/utils.h
Closes: https://github.com/containers/crun/issues/1576
=> cgroup: add support for more systemd properties

src/libcrun/cgroup-resources.c, src/libcrun/cgroup-systemd.c
follow-up for https://github.com/containers/crun/pull/1574
=> cgroup, systemd: add support for IODeviceWeight

src/libcrun/container.h, src/libcrun/criu.c, src/restore.c
By default, CRIU restores containers with the same SELinux process labels used during checkpointing. However, when restoring multiple copies of a container, this results in all containers using identical SELinux labels, which is undesirable. In addition, all containers in a Pod share the SELinux label of the infrastructure container. To restore a new container into an existing Pod, we need to specify the SELinux label to be used during restore.
This pull request adds `--lsm-profile` and `--lsm-mount-context` options for the `crun restore` command to enable this functionality, similar to runc (https://github.com/opencontainers/runc/pull/3005)
=> restore: add lsm-profile and lsm-mount-context options

rpm/crun.spec
A standalone yajl library is unwanted in RHEL, and nothing else therein depends on it; based on c10s:
https://gitlab.com/redhat/centos-stream/rpms/crun/-/merge_requests/102
=> rpm: use embedded yajl in RHEL builds

crun.1, crun.1.md
This pull request updates the man page with a description for the `--lsm-profile` and `--lsm-mount-context` options introduced in https://github.com/containers/crun/pull/1578.
=> crun.1.md: add lsm-profile and lsm-mount-context

src/libcrun/linux.c
libcrun_set_usernamespace passes uid_map/gid_map to uidgidmap_helper which tokenizes it to pass as process args. But if the helper isn't available, the fallback (when host_uid != 0) reuses this tokenized string and tries writing it to /proc/pid/gid_map which fails with EINVAL
closes https://github.com/containers/crun/issues/1585
=> linux: copy map_file before tokenizing in uidgidmap_helper

src/libcrun/cgroup-systemd.c
Closes: https://github.com/containers/crun/issues/1588
=> cgroup: ignore redundant deny dev cgroup rules

NEWS
=> NEWS: tag 1.18.1

NEWS, src/libcrun/cgroup-systemd.c
The `find_first_rule_no_default` function was modified to also check the simple case where there is only a default BLOCK ALL rule.
In addition, improve the function to skip to the first allow rule when the default BLOCK ALL rule is implicit.
Closes: https://github.com/containers/crun/issues/1597
=> cgroup, systemd: fix first rule selection for systemd

src/create.c, src/crun.c, src/crun.h, src/exec.c, src/libcrun/cgroup-setup.c, src/libcrun/ebpf.c, src/libcrun/linux.c, src/libcrun/utils.c, src/run.c, tests/init.c, tests/tests_libcrun_fuzzer.c
fix three different issues:
- https://github.com/containers/crun/issues/1602
- https://github.com/containers/crun/issues/1603
- https://github.com/containers/crun/issues/1604
=> Fix static analysis reports

src/libcrun/cloned_binary.c, src/libcrun/linux.c, src/libcrun/linux.h
if the new mount API is available, use it to grad a read-only reference to the current executable.  The advantage is that there is no need to leak a mount in the current mount namespace.
Closes: https://github.com/containers/crun/issues/1383
Closes: https://issues.redhat.com/browse/RHEL-67558
=> src: use mount API to self-clone

src/libcrun/cgroup-systemd.c
if the resources configuration on update does not contain any information on devices, do not change the current configuration.
Fixes: https://issues.redhat.com/browse/OCPBUGS-45394
=> cgroup, systemd: do not override devices on update

Makefile.am
Building crun after commit 8a0ee4b56a801c26efdcd26732090bbe86236e8c yields the following link error:
```
2024-11-28T01:45:15.2415817Z   CCLD     libcrun.la
2024-11-28T01:45:15.3802217Z   CCLD     crun
2024-11-28T01:45:15.4957602Z /home/runner/work/zebrafish/zebrafish/buildroot/output/host/lib/gcc/x86_64-buildroot-linux-gnu/13.3.0/../../../../x86_64-buildroot-linux-gnu/bin/ld: src/libcrun/crun-cloned_binary.o: in function `ensure_cloned_binary':
2024-11-28T01:45:15.4959563Z cloned_binary.c:(.text+0x87c): undefined reference to `get_bind_mount'
2024-11-28T01:45:15.4961482Z /home/runner/work/zebrafish/zebrafish/buildroot/output/host/lib/gcc/x86_64-buildroot-linux-gnu/13.3.0/../../../../x86_64-buildroot-linux-gnu/bin/ld: cloned_binary.c:(.text+0x8b7): undefined reference to …
```
=> build: Don't build cloned_binary as part of crun

src/libcrun/cgroup-systemd.c
```
src/libcrun/cgroup-systemd.c: In function 'cpuset_string_to_bitmask':
src/libcrun/cgroup-systemd.c:84:49: error: 'CHAR_BIT' undeclared (first use in this function)
84 |       if (end_range >= (long long) (mask_size * CHAR_BIT))
|                                                 ^~~~~~~~
src/libcrun/cgroup-systemd.c:39:1: note: 'CHAR_BIT' is defined in header '<limits.h>'; did you forget to '#include <limits.h>'?
38 | #  include <systemd/sd-bus.h>
+++ |+#include <limits.h>
39 |
src/libcrun/cgroup-systemd.c:84:49: note: each undeclared identifier is reported only once for each function it appears in
84 |       if (end_range >= (long long) (mask_size * CHAR_BIT))
|                                                 ^~~~~~~~
make[2]: *** [Makefile:1812: …
```
=> error: 'CHAR_BIT' undeclared. fix compile failure with musl libc

configure.ac, src/checkpoint.c, src/checkpoint.h, src/libcrun/container.h, src/libcrun/criu.c, src/restore.c
Netavark defaults to nftables but it seems that crun checkpoint doesn't allow setting firewall driver used for network locking and unlocking by criu. criu defaults to iptables and in situations where podman is installed without iptables, criu tries to use iptable utils and fails.
=> checkpoint/restore: allow passing network lock method to libcriu

NEWS
- wasm: add new handler wamr.
- criu: allow passing network lock method to libcriu.
- linux: honor exec cpu affinity mask.
- build: fix build with musl libc.
- crun: use mount API to self-clone.
- cgroup, systemd: do not override devices on update.  If the "update" request has no device block configured, do not reset the previously configuration.
- cgroup: handle case where cgroup v1 freezer is disabled.  On systems without the freezer controller, containers were mistakenly reported as paused.
- cgroup: do not stop process on exec.  The cpu mask is configured on the systemd scope, the previous workaround to stop the container until the cgroup is fully configured is no longer needed.
=> NEWS: tag 1.19

Makefile.am
static library is supposed to be archive of object files. if libtool is not used libcrun_testing.a includes raw libocispec.la file instead of its object files.
=> build: use libtool to create libcrun_testing

Makefile.am, tests/fuzzing/run-tests.sh
Creating the PR to get a feedback as it might have some side effects.
I think not compiling tests during normal build is the expected behavior however it shifts compilation to first `make check` invocation which I believe in CI is done with escalated privileges. Might have some unexpected impact if some files have different ownership/permissions.
=> build: don't compile tests during normal build

src/libcrun/linux.c
remove the workaround to mount a cgroup on top of another cgroup mpunt using a temporary mount.  This has the disadvantage to leak a mount on the host, while the alternative one, which is the only mechanism used now, does not since it uses a private tmpfs.
Fixes: https://issues.redhat.com/browse/RHEL-70694
=> linux: remove tmpmount workaround

Makefile.am, src/libcrun/container.c, src/libcrun/ring_buffer.c, src/libcrun/ring_buffer.h, src/libcrun/utils.c, src/libcrun/utils.h, tests/test_mounts.py, tests/tests_libcrun_ring_buffer.c
avoid a "crun exec" hang when the the other end of the terminal stopped reading.
That happened because `copy_fd_to_fd` tried to write everything that it has received from the source fd, so it would hang the current process.  Prevent that using non blocking file descriptors and using epoll to detect when the file descriptor is available for write.
Fixes: https://issues.redhat.com/browse/OCPBUGS-45632
=> linux: fix a hang if there are no reads from the tty

src/libcrun/utils.c
If a given user cannot be found within the container, for example, because the specific `UID` does not exist, then return an error and let the callers of the `set_home_env()` function handle the case of the missing user appropriately.
This will fix an issue where when the user cannot be found, the `HOME` environment variable is not set, which can cause some software not to work correctly.
The two current callers already correctly handled the case when the user was not found per:
- https://github.com/containers/crun/blob/bd4f77330961819150f35bc42f4a6dc44ff135e7/src/libcrun/container.c#L1199-L1207
- https://github.com/containers/crun/blob/bd4f77330961819150f35bc42f4a6dc44ff135e7/src/libcrun/container.c#L3406-L3414
The above will issue a warning and correctly set the `HOME` environment …
=> utils: return error from set_home_env() if the user was not found

src/libcrun/criu.c
commit c4f8c87a7a06fdc46e10fff129d89f8753d62380 introduced the issue.
also improve error handling from criu APIs
Closes: https://github.com/containers/crun/issues/1627
=> criu: do not set network_lock if not specified

src/libcrun/cgroup-resources.c
This reverts commit 1e3042427df0eb04add740f1618fae7d0827fa63.
Copy what runc is already doing here: https://github.com/opencontainers/runc/pull/4555
=> Revert "cgroup: remove tun/tap from the default allow list"

.packit.yaml, plans/main.fmf
The previous `adjust` conditionals ended up skipping copr repo and package upgrade steps for CentOS Stream environments.
This should be resolved by directly using `prepare` and `when` keywords for setting conditions.
=> TMT: Replace adjust with prepare conditionals

.github/workflows/test.yaml, src/libcrun/linux.c, tests/init.c, tests/test_exec.py
previously setsid was called only for interactive sessions.  Change it to be always used for the "crun exec" process.
Closes: https://github.com/containers/crun/issues/1642
=> exec: always call setsid

src/libcrun/linux.c
improve the error message when writing to the
/proc/sys/net/ipv4/ping_group_range file and the write fails with EINVAL.  When running in a user namespace, it might mean the requested groups are not mapped.
Closes: https://github.com/containers/crun/issues/1648
=> linux: improve error writing to net.ipv4.ping_group_range

lua/lua_crun.c, src/crun.c, src/libcrun/cgroup-systemd.c, src/libcrun/container.c, src/libcrun/handlers/krun.c, src/libcrun/linux.c, src/libcrun/seccomp.c, src/libcrun/status.c, src/libcrun/status.h, tests/test_start.py
check that the container name does not contain any slash so that operations in status.c won't risk to access directories/files outside of the run directory.
Beside, it is not a security issue because if a directory exists, crun refuses to use it; and if it does not exist then it is created and immediately deleted because the container creation fails.
Play safe and do not allow any slash in the container name.
Closes: https://github.com/containers/crun/issues/1646
=> status: validate container id

src/libcrun/container.c
It looks like `errno` is only set when `read()` returns  `-1`
See read() [man page](https://man7.org/linux/man-pages/man2/read.2.html)
=> container: fix error after read

src/libcrun/linux.c, src/libcrun/utils.c, src/libcrun/utils.h
=> linux, utils: remove dead code crun_ensure_file*()

src/libcrun/handlers/mono.c, src/libcrun/linux.c
It looks like those `crun_error_release()` are not needed.
=> linux, mono: remove unneeded crun_error_release()

src/libcrun/handlers/krun.c, src/libcrun/utils.c, src/libcrun/utils.h
=> utils: fix partial writes with write_file_at_with_flags

src/libcrun/utils.c
The `O_NOFOLLOW` can be added because the file type is `S_IFREG` or `S_IFDIR`
=> utils: add O_NOFOLLOW

rpm/gating.yaml
Doesn't affect upstream. The wrongly configured file blocked koji builds.
=> Downstream Fedora: fix gating config

src/libcrun/utils.c
Support filenames starting with a dot when
doing PATH lookup.
Fixes: https://github.com/containers/crun/issues/1664
=> utils: fix PATH lookup

src/libcrun/container.c, src/libcrun/error.c
What is the preferred way to write a check that indicates that a failure is not expected and that such a failure would indicate a programming errror?
One way is to write `assert()` (but such a check is only  active for an executable  that was compiled with the debug option enabled)
For example:
```
assert(err != NULL);
assert(*err != NULL);
```
This is another way:
```
if (err == NULL || *err == NULL) {
// programming error
_exit(EXIT_FAILURE);
}
```
I prefer `assert()` slightly more.
=> container, error: update error handling

README.md
Remove outdated RHEL/CentOS 8 build instructions.
Add RHEL/CentOS Stream 9 and 10.
_Replaces #1641._
=> README: add CentOS Stream 9 & 10, rm 8

Makefile.am, configure.ac, src/libcrun/cgroup-systemd.c, src/libcrun/cgroup.c, src/libcrun/cgroup.h, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/string_map.c, src/libcrun/string_map.h, src/libcrun/utils.c, src/libcrun/utils.h
Use a hash map to speed up the lookup of annotations.
If the array is small (< 8 elements), use a binary search on the sorted array
=> libcrun: use an hash map to lookup annotations

nix/derivation.nix, nix/overlay.nix, src/libcrun/criu.c
I tried to get container checkpoint with static link'ed crun via CRI-O, but it failed due not to load `libcriu.so.2`.  
I strace'ed checkpointing, I saw following lines in the log:
```
openat(AT_FDCWD, "/nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libcriu.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/2d5spnl8j5r4n1s4bj1zmra7mwx0f1n8-xgcc-13.3.0-libgcc/lib/libcriu.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "could not load `libcriu.so.2`\n", 30could not load `libcriu.so.2`
```
I think it is because `dlopen()` for `libcriu.so.2` was called despite of static link'ed binary - library path seems to be on build environment (Nix).
In static link'ed library, all of libraries should be static linked, …
=> Prevent dlopen() for CRIU in static link'ed binary

configure.ac, src/libcrun/container.c, src/libcrun/error.c, src/libcrun/utils.c, src/libcrun/utils.h, tests/podman/Dockerfile
improve the error returned when the specified path is not executable.
Return the reason why the lookup failed when the path is not a regular file, or has no executable bit set.
Closes: https://github.com/containers/crun/issues/1671
=> utils: improve error message if path not executable

src/libcrun/handlers/krun.c
I haven't tested the PR yet so I mark it as a draft.
=> krun: fix libkrun_unload

tests/test_resources.py
Commit a4dcb9c (PR #1639) changed error message to show the absolute path to cgroup.controllers when a controller is not available.
Change the test to also expect the new error message, while the old one, as the new code may still conditionally return it.
=> tests: fix test_resources_unified_invalid_controller()

src/libcrun/chroot_realpath.c
The PR is marked as a draft as of now.
I'm pretty sure it's correct but I will go through it later.
----
* Do not return non-existing paths in chroot_realpath().
Rationale: failing early is good.
* Remove dead code
=> chroot_realpath: do not return non-existing paths

src/libcrun/container.c
if there is no tty configured for the container, ignore the SIGWINCH signal instead of exiting with success.
Closes: https://github.com/containers/crun/issues/1442
=> container: ignore SIGWINCH without tty

src/libcrun/handlers/krun.c
the file must be readable by all IDs otherwise it is ignored when running with a UID != 0.
Closes: https://github.com/containers/crun/issues/1685
=> krun: make krun config file world readable

src/libcrun/handlers/krun.c
so that the command line is taken directly from the config.json file.
@slp PTAL
=> krun: stop using krun_set_exec

src/libcrun/handlers/krun.c
Newer versions of libkrun no longer link against libkrunfw (the library bundling the kernel) and, instead, they load it dynamically when creating the context.
This implies we need to call krun_create_ctx ealier, before switching namespaces, or libkrun won't be able to find libkrunfw.
=> krun: create context after loading the library

src/libcrun/container.c
That console socket client is initialized only when the user declares terminal.
Otherwise, the console socket client is not used after initialization.
=> Console socket client is initialized only when the user declares terminal

src/libcrun/container.c
if the container main process and console socket do not need a terminal, the terminal fd is not created.
=> terminal fd is not created in the container process if it is not necessary

src/libcrun/container.c
In some cases, stdin/out/err might be legitimately closed, let's not bail out early because of that.
Fixes: https://github.com/containers/crun/issues/1702
=> maybe_chown_std_streams: ignore EBADF

src/libcrun/handlers/krun.c
krun: implement support for external kernels
libkrun has recently acquired the ability to load external kernels. Use
it to enable users to bundle kernel images in their container files.
Note: in our execution model, the kernel in the microVM is not (and has
never been) considered a trusted component. This is the reason why we
put the whole VMM inside the container and avoid using vhost or any
other features that require special privileges, beyond KVM.
=> krun: implement support for external kernels

src/libcrun/cgroup-utils.c, src/libcrun/criu.c, src/libcrun/handlers/krun.c, src/libcrun/linux.c
Use existing errors. This fixes some small memory leaks.
This also fixes a negative second argument given to crun_make_error()
https://github.com/containers/crun/blob/db8977e94974dfcacc09b983aec85600d90a4944/src/libcrun/handlers/krun.c#L161-L162
=> libcrun, krun: use existing error

Makefile.am, crun.1, crun.1.md, src/crun.c, src/libcrun/container.c, src/libcrun/container.h, src/libcrun/linux.c, src/libcrun/linux.h, src/libcrun/status.c, src/mounts.c, src/mounts.h, tests/test_mounts.py, tests/tests_libcrun_fuzzer.c
add a new CLI command "crun mounts add|remove $CTR $FILE" to alter the mounts of a running container.
The "crun mounts add" command adds the mounts specified in the $FILE file to the mount namespace of the container process.  At the moment only bind mounts are supported.
Differently, "crun mounts remove" can be used to remove a set of mounts from the container mount namespace.
=> crun: add mounts command

src/libcrun/criu.c, tests/test_checkpoint_restore.py
1. Fix error message added in #1741.
2. Commit 90ef9732 ("criu: create --work-path directory", PR #1741) forgot to add the same logic upon restore. If the --work-path used during restore differs from one that was used during checkpoint, criu fails.
3. Commit 0dceab0c did not define the work_dir for one of the cases.
=> Followups to #1741

configure.ac
The configure script is checking if <error.h> is present, but not if error
is actually provided by the library (which is the case with musl).
Add a check for usable error function.
This fixes an issue (https://github.com/containers/crun/issues/1886)
=> configure.ac: check if error function is available
