- src/libcrun/status.c
do not list every file that can be found in the status directory, but
delete all that are found.
> status: do not hardcode files to delete

- README.md
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> README: add ubuntu build info

- .travis.yml
- src/libcrun/status.c
- tests/podman/Dockerfile
- tests/podman/run-tests.sh
> tests: run Podman e2e tests

- src/libcrun/container.c
> container: use kill(2) instead of custom message in the protocol

- tests/podman/Dockerfile
- tests/podman/run-tests.sh
> tests: update the version of podman

- src/libcrun/cloned_binary.c
shamelessy copy the file from runc.
> cloned_binary: sync from runc

- src/create.c
- src/crun.c
- src/crun.h
- src/delete.c
- src/exec.c
- src/kill.c
- src/libcrun/container.c
- src/libcrun/error.c
- src/libcrun/error.h
- src/list.c
- src/pause.c
- src/run.c
- src/spec.c
- src/start.c
- src/state.c
- src/unpause.c
- src/update.c
> logs: add support for json output

- .travis.yml
- Makefile.am
- python/crun_python.c
- src/exec.c
- src/libcrun/cgroup.c
- src/libcrun/cloned_binary.c
- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/status.c
- src/libcrun/utils.c
- src/start.c
- src/update.c
- tests/init.c
- tests/tests_libcrun_utils.c
> travis.yml: enable coverity

- src/crun.c
- src/libcrun/container.c
- src/libcrun/container.h
- src/libcrun/error.c
- src/libcrun/error.h
- src/libcrun/seccomp.c
- src/libcrun/utils.c
- src/libcrun/utils.h
> logging: support --log=syslog: and log=journald:

- src/libcrun/linux.c
we need to ensure the parent mount point is not using MS_SHARED,
otherwise pivot_root fails.
> linux: fix pivot_root if parent is MS_SHARED

- src/libcrun/cgroup.c
> cgroup: free as much as possible when cleaning up cgroups

- src/libcrun/linux.c
> linux: not set MS_PRIVATE on / with shared/rshared propagation

- src/libcrun/status.c
> status: ignore XDG_RUNTIME_DIR if it is empty

- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/terminal.c
> tty: set the size on the exec tty

- src/libcrun/cgroup.c
> cgroup: create the same scope name as runc

- src/libcrun/container.c
- src/libcrun/container.h
- src/list.c
Closes: https://github.com/giuseppe/crun/issues/58
> list: add STATUS to the list of containers

- src/delete.c
- src/exec.c
- src/kill.c
- src/libcrun/cgroup.c
- src/libcrun/container.c
- src/libcrun/error.c
- src/libcrun/linux.c
- src/libcrun/sig2str.h
- src/update.c
https://www.code-inspector.com/public/project/350/crun/dashboard
> fix some warnings reported by code-inspector.com

- .sonarcloud.properties
> .sonarcloud.properties: new file

- .sonarcloud.properties
- .travis.yml
- README.md
- contrib/sonarcloud/sonar-project.properties
- sonar-project.properties
- src/libcrun/utils.c
> README.md: add sonarcloud badge

- src/libcrun/linux.c
now pause/resume work on a cgroups v2 system.
> cgroupsv2: add support for freezer

- tests/podman/Dockerfile
> tests: update libpod to v1.4.4

- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/status.c
prevent reading from the notify socket to block indefinitely when the
container already exited.
> notify: do not block indefinitely

- src/libcrun/cgroup.c
- src/libcrun/container.c
- src/libcrun/utils.c
- src/libcrun/utils.h
- tests/oci-validation/oci-runtime-validation
Closes: https://github.com/containers/crun/issues/13
> container: add executable lookup

- configure.ac
- src/libcrun/linux.c
- src/libcrun/utils.c
- src/libcrun/utils.h
when tmpcopyup is specified, copy the directory below to the mounted tmpfs.
> linux: handle tmpcopyup

- src/libcrun/linux.c
> linux: fix a memleak reported by Coverity

- configure.ac
> configure.ac: tag release 0.9

- crun.1.md
- src/exec.c
Note: a test is coming, but it is not currently cooperating. I have manually tested and it works
Signed-off-by: Peter Hunt <pehunt@redhat.com>
> Add support for --preserve-fds

- .travis.yml
- src/libcrun/container.c
- src/libcrun/utils.c
- tests/oci-validation/oci-runtime-validation
> tests: fix failing oci-validation test

- .travis.yml
- README.md
- configure.ac
- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/linux.h
- src/libcrun/utils.c
- src/libcrun/utils.h
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>
> Add apparmor support

- src/crun.c
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>
> Add apparmor to version output

- src/create.c
- src/crun.c
- src/delete.c
- src/exec.c
- src/kill.c
- src/libcrun/cgroup.c
- src/libcrun/cloned_binary.c
- src/libcrun/container.c
- src/libcrun/ebpf.c
- src/libcrun/error.c
- src/libcrun/error.h
- src/libcrun/linux.c
- src/libcrun/linux.h
- src/libcrun/utils.c
- src/libcrun/utils.h
- src/list.c
- src/pause.c
- src/run.c
- src/spec.c
- src/start.c
- src/state.c
- src/unpause.c
- src/update.c
- tests/podman/run-tests.sh
- tests/tests_libcrun_utils.c
Now ./configure CFLAGS='-Wall -Wextra' builds without any warning.
> src: fix some warnings reported by gcc

- src/libcrun/cloned_binary.c
realloc() wrapper.
Signed-off-by: Jindrich Novy <jnovy@redhat.com>
> Don't hang in an attempt to reallocate memory and use safe

- src/libcrun/chroot_realpath.c
the current implementation of chroot_realpath skipped resolving
symlinks for the last path component.  A malicious image could create
files on the host.
Closes: https://github.com/containers/crun/issues/111
> chroot: follow symlinks for the last component

- .travis.yml
- Dockerfile
- README.md
- configure.ac
- contrib/static-builder-x86_64/Dockerfile
- contrib/static-builder-x86_64/build.sh
- rpm/crun.spec.template
- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/linux.h
- src/libcrun/utils.c
- src/libcrun/utils.h
- tests/podman/Dockerfile
alternative version for: https://github.com/containers/crun/pull/109
> CVE-2019-16884: container: check fs type when writing SELinux and AppArmor profiles

- src/libcrun/utils.c
- tests/test_resources.py
> tests: fix make check tests failures

- src/libcrun/cgroup.c
when running as rootless on cgroup v1, ignore errors when joining a
cgroup controller.
> rootless: fix exec on cgroup v1

- Makefile.am
- tests/test_detach.py
- tests/test_paths.py
- tests/test_preserve_fds.py
- tests/tests_utils.py
ignore the warnings printed by crun on stderr.
> tests: fix running as rootless user

- src/libcrun/cgroup.c
- src/libcrun/linux.c
- src/libcrun/utils.c
- tests/podman/Dockerfile
> tests: bump Podman version

- .travis.yml
- configure.ac
> .travis: enable build on arm64

- src/libcrun/container.c
the definition  went out of sync on a recent update from libocispec.
> hooks: use definition from libocispec

- src/libcrun/cgroup.c
do not assume the devices permissions "rwm" are always provided in the
same order.
Closes: https://github.com/containers/crun/issues/135
> cgroup: do not assume "rwm" is ordered

- .travis.yml
- src/libcrun/cgroup.c
- src/libcrun/container.c
- src/libcrun/error.c
- src/libcrun/linux.c
- src/libcrun/utils.c
- tests/alpine-build/Dockerfile
- tests/alpine-build/run-tests.sh
> travis: build on Alpine

- .gitignore
- Makefile.am
- configure.ac
- rpm/crun.spec.in
this is a minor simplification to generating the version in the rpm spec
> Use autotools to generate RPM spec

- configure.ac
- src/libcrun/status.c
> configure: tag new release 0.10.3

- src/libcrun/status.c
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
> Create /run directories if they do not exist

- Makefile.am
- README.md
- configure.ac
> README.md: add instructions for building on RHEL/CentOS 8

- crun.1.md
> doc: add section about extensions

- configure.ac
> Use "python3" instead of the default "python"

- .travis.yml
- src/libcrun/container.c
> .travis.yml: enable ppc64le and s390x

- crun.1.md
- src/libcrun/cgroup.c
> cgroups2: map reservation to memory.low

- Makefile.am
- NEWS
- build-aux/release.sh
- configure.ac
- rpm/crun.spec.in
> build: fix generating rpm from source

- README.md
> README.md: show how crun requires less resources

- src/libcrun/cgroup.c
if the cgroup was already destroyed, delete --force will continue
deleting the rest of the container files instead of failing on the
ENOENT error.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1780161
> cgroup: killall ignore ENOENT

- src/libcrun/utils.c
Reported here: https://github.com/containerd/containerd/pull/3883
> utils: redirect stdout/stderr for hooks to /dev/null

- .travis.yml
- tests/containerd/Dockerfile
- tests/containerd/run-tests.sh
> travis: add containerd tests

- .travis.yml
> travis: add test for 'make check'

- tests/podman/Dockerfile
> tests: update podman version

- src/libcrun/linux.c
- tests/test_uid_gid.py
make sure to use uint32 format specifier so that 4294967295 is
correctly printed and doesn't overflow to -1.
Closes: https://github.com/containers/crun/issues/209
> linux: fix userns mapping with size 4294967295

- src/libcrun/cgroup.c
- src/libcrun/cgroup.h
- src/libcrun/container.c
- src/ps.c
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1784407
> utils: read_pids_cgroup: read cgroup recursively

- NEWS
> release: tag 0.11

- .travis.yml
- README.md
- src/libcrun/cgroup.c
- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/status.c
- src/libcrun/utils.c
some micro optimizations to improve performance on average by 15%
> linux: masked paths use only MS_UNBINDABLE

- src/libcrun/container.c
handle new hooks createRuntime, createContainer and startContainer.
> linux: honor new hook types

- .travis.yml
- cfg.mk
- src/create.c
- src/crun.c
- src/libcrun/cgroup.c
- src/libcrun/chroot_realpath.c
- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/seccomp.c
- src/libcrun/status.c
- src/libcrun/utils.c
- src/libcrun/utils.h
- src/run.c
solves different kind of race conditions while performing the mounts.
More details are in each commit.
> linux: solve some potential race conditions when performing the mounts

- src/exec.c
- src/libcrun/cgroup.c
- src/libcrun/cgroup.h
- src/libcrun/container.c
- src/libcrun/container.h
- src/libcrun/ebpf.h
- src/libcrun/linux.c
- src/libcrun/linux.h
- src/libcrun/seccomp.c
- src/libcrun/seccomp.h
- src/libcrun/status.h
- src/libcrun/utils.h
adapt crun with the libocispec
[improvements: generate the source files base on path](https://github.com/containers/libocispec/pull/45)
Signed-off-by: lifeng68 <lifeng68@huawei.com>
> adapt crun with the libocispec

- src/libcrun/container.c
Closes: https://github.com/containers/crun/issues/230
> linux: reset all signal handlers to default

- src/libcrun/container.c
> Removed gid=5 from the devpts options to better support rootless

- src/libcrun/container.c
- src/libcrun/utils.c
> linux: close some fds when not needed

- src/libcrun/linux.c
- src/libcrun/utils.c
a couple of regressions with buildah
> fix running with buildah

- NEWS
- contrib/static-builder-x86_64/build.sh
> NEWS: update to 0.12

- NEWS
> NEWS: document 0.12.1

- src/libcrun/linux.c
when mounting cgroup v1, attempt to mount the cgroup file system
instead of doing a bind mount from the host.
It solves an issue when running in a cgroup namespace, that the root
refers to the current cgroup instead of the root on the host.
Closes: https://github.com/containers/crun/issues/258
> cgroup: attempt to mount cgroup before do the bind

- src/libcrun/seccomp.c
The current code ignores argument index and uses argument position
in the spec instead. This leads to the following situation: if seccomp
rules check only argument 1, then the generated BPF refers to argument
0 instead, causing all sorts of confusion.
> linux: use correct indices for seccomp arguments

- src/crun.c
> crun: add CRIU to the features list

- NEWS
> NEWS: tag 0.12.2

- src/libcrun/linux.c
> linux: fix recursive mount on cgroup v1

- .github/workflows/release.yaml
- autogen.sh
- build-aux/release.sh
- contrib/static-builder-x86_64/Dockerfile
- contrib/static-builder-x86_64/Makefile
create release artifacts on each PR.
> release: add github actions

- NEWS
> NEWS: tag version 0.13

- src/exec.c
- src/libcrun/container.c
> exec: a couple of fixes

- src/libcrun/cgroup.c
This is a followup to https://github.com/containers/crun/pull/316#issuecomment-610686186
Please see the individual commits for details.
> cgroup, v2: fixes setting swap and pids limits

- src/libcrun/linux.c
instead use the definition that already exists.
The time namespace was missing and not joined on exec.
> linux: don't declare namespaces for exec

- src/libcrun/cgroup.c
- src/libcrun/linux.c
- src/libcrun/utils.c
Mostly unused vars (see individual commits for details).
> Various nits (found by clang -Wall -Wextra)

- src/libcrun/linux.c
> linux: fix error when a user namespace cannot be joined

- src/libcrun/linux.c
make sure to set the uid/gid to root immediately after joining the
namespaces.  Otherwise the runtime has no privileges for chowning the
terminal file.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1829135
> exec: setuid/setgid before setting up the terminal

- src/libcrun/seccomp.c
honor the new OCI field errnoRet.
> seccomp: honor errnoRet

- src/libcrun/seccomp.c
> seccomp: honor SCMP_ACT_KILL_PROCESS

- src/libcrun/container.c
- src/libcrun/error.c
- src/libcrun/error.h
> error: introduce crun_error_wrap and start using it

- contrib/static-builder-x86_64/Dockerfile
- contrib/static-builder-x86_64/Makefile
- contrib/static-builder-x86_64/README.md
- src/libcrun/cgroup.c
- src/libcrun/error.c
- src/libcrun/linux.c
- src/libcrun/utils.c
a couple of fixes related to recent changes and one improvement.
> fix two regressions in master

- README.md
Also see:
- https://github.com/containers/conmon/pull/164
- https://github.com/containers/podman.io/pull/242
> README.md cleanup with typo

- src/libcrun/cgroup.c
change the skip condition to ignore errors if there are no block rules or if it is running rootless.
Closes: https://github.com/containers/crun/issues/382
> cgroup, devices: change skip condition

- src/libcrun/linux.c
> rootless: allow /dev/{tty,ptmx} to be present in linux.devices

- src/libcrun/container.c
- src/libcrun/linux.c
report to the parent process errors happening while setting up the
tty.
> linux: report exec errors while setting up tty

- src/libcrun/cgroup.c
- src/libcrun/cgroup.h
- src/libcrun/container.c
use the scope from the status file.
> systemd: fix cleanup for systemd cgroups

- tests/Makefile.tests
- tests/init.c
- tests/run_all_tests.sh
- tests/tests_utils.py
> tests: allow to run tests with a different binary

- Makefile.am
- configure.ac
- libcrun.lds
- python/crun_python.c
- src/checkpoint.c
- src/crun.c
- src/crun.h
- src/delete.c
- src/exec.c
- src/kill.c
- src/libcrun/cgroup.h
- src/libcrun/container.c
- src/libcrun/container.h
- src/libcrun/error.c
- src/libcrun/error.h
- src/libcrun/signals.c
- src/libcrun/signals.perf
- src/libcrun/status.h
- src/libcrun/utils.c
- src/libcrun/utils.h
- src/list.c
- src/ps.c
- src/restore.c
- src/spec.c
- src/update.c
- tests/tests_utils.py
> libcrun: do not export all symbols

- nix/default.nix
- nix/nixpkgs.json
Confirm latest master nix static binary build functioning with latest nixpkgs.
> make nixpkgs

- src/libcrun/container.c
when the container is created using create+start, make sure the
poststart hook is executed inside the "start" command instead of
"create".
The OCI runtime specs say:
The poststart hooks MUST be called after the user-specified
process is executed but before the start operation returns. For
example, this hook can notify the user that the container process
is spawned.
Determining when the user-specified process is executed is not trivial
from a different process, so it can happen before the execve is
performed but it is already a very late stage in the init container
setup.
Closes: https://github.com/containers/crun/issues/406
> linux: fix poststart hook

- src/libcrun/container.c
- tests/test_start.py
- tests/tests_utils.py
regression introduced by 7179d71afd608f5e85740b2b4b83f9b41fbe1b15
> container, run: always delete container without detach

- src/libcrun/linux.c
issue introduced by the recent refactoring.
> linux: do not wait userns creation when joining one

- src/libcrun/linux.c
- tests/init.c
- tests/test_start.py
- tests/tests_utils.py
this is what crun always creates inside of the container, make sure the environment variable has the correct value.
Closes: https://github.com/containers/crun/issues/414
> linux: force /notify suffix for notify socket

- Makefile.am
- nix/default.nix
- nix/nixpkgs.json
Switch from nix `channel:nixpkgs-unstable` to `channel:nixos-20.03` for better stability.
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>
> nix run -f channel:nixos-20.03

- src/libcrun/utils.c
- tests/test_start.py
- tests/tests_utils.py
Closes: https://github.com/containers/crun/issues/417
> linux: fix lookup for paths containing '/'

- NEWS
- src/libcrun/container.c
Closes: https://github.com/containers/crun/issues/398
> NEWS: tag 0.14

- NEWS
- tests/test_exec.py
> NEWS: tag 0.14.1

- crun.1.md
- src/create.c
- src/exec.c
- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/terminal.c
- src/libcrun/terminal.h
- src/run.c
> src: remove wrong naming

- src/libcrun/cgroup.c
try to enable as many controllers as possible for the new cgroup.
> cgroup: enable all available controllers

- python/crun_python.c
- src/checkpoint.c
- src/libcrun/error.c
- src/restore.c
I'm not sure if I should change crun_python.c. Please let me if anything is inappropriate.
> fix error handling of asprintf

- Dockerfile
Closes: https://github.com/containers/crun/issues/441
> Dockerfile: fix build

- src/libcrun/container.c
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
> Output the missing executable file from path

- build-aux/release.sh
- nix/default.nix
cherry-picked from https://github.com/containers/crun/pull/447
> build-aux: remove intermediate result directory

- src/libcrun/cgroup.c
- src/libcrun/error.c
- src/libcrun/linux.c
- src/libcrun/seccomp.c
> fix some issues reported by static analysis

- src/libcrun/utils.c
runc also checks for the pure existence of this directory to ensure that
AppArmor is fully enabled on the system.
> AppArmor: add additional check for /sys/kernel/security/apparmor

- src/create.c
- src/run.c
"create" and "run" cmd bundle option, allowing "=" and fix --help not showing a value
fixes #457
> cmd "--bundle=" option in create and run

- .clang-format
- src/libcrun/cgroup.c
- src/libcrun/container.c
- src/libcrun/ebpf.c
- src/libcrun/error.c
- src/libcrun/intprops.h
- src/libcrun/linux.c
- src/libcrun/seccomp.c
- src/libcrun/seccomp_notify.c
- src/libcrun/status.c
- src/libcrun/terminal.c
- src/libcrun/utils.c
- src/libcrun/utils.h
- src/list.c
- src/update.c
do not pass a string read from pipe as formatting argument.
> container: fix issue reported by lgtm.com

- nix/default.nix
- nix/nixpkgs.json
Also update systemd 246 as per https://github.com/NixOS/nixpkgs/pull/94354
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>
> Update nix pin with `make nixpkgs`

- NEWS
- src/libcrun/chroot_realpath.c
- src/libcrun/linux.c
- src/libcrun/status.c
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
> Fix problems found by codespell

- Makefile.am
Closes: https://github.com/containers/crun/issues/492
> Makefile.am: add libcrun.lds to EXTRA_DIST

- src/libcrun/utils.c
- tests/test_mounts.py
- tests/tests_utils.py
Closes: https://github.com/containers/crun/issues/497
> utils: resolve last component if symlink

- Makefile.am
> Makefile.am: do not delete crun.1

- src/libcrun/linux.c
do not accept anymore type="bind" for bind mounts, but require the
"bind" or "rbind" option to be present in the options.
This change is required to follow more closely the OCI runtime specs.
> linux: require [r]bind options for bind mounts

- NEWS
> NEWS: tag 0.15

- src/create.c
- src/exec.c
- src/run.c
Closes: https://github.com/containers/crun/issues/506
> crun: force argument for --preserve-fds

- crun.1
- crun.1.md
> crun.1.md: fix memory.swap.max conversion

- src/libcrun/container.c
Hi.
First, I do hope you are fine and the same for your relatives.
Normally this should fix #399.
The only difference between the JSON generated now with libyajl is that it does contain space between key/value.
For example, this one is now generated:
```
{"ociVersion":"1.0","id":"dac262a7ae3a3c83e9603b69411f130c510dc9b998d57123cbdf49a649b554fd",
```
Compared to this one with `xasprintf`:
```
{"ociVersion":"1.0", "id":"a49c99c87899c22242e4c3e99a2649224c82665652d9a941d1974e0e594a3746", ...
```
I also removed unused variable `annotations` since I add them directly to stdin JSON.
I have some question about my modifications:
1. I took a look at `yajl_gen_free` source code but I am not 100% sure that it also frees the buffer associated with generator.
On the other hand when `stdin` was declared …
> Use libyajl to generate hooks json input.

- src/libcrun/cgroup.c
- src/libcrun/utils.c
if a file could not be written on cgroup v2, detect whether the
required controller is enabled in the cgroup.  If it is not present,
give a better error message to the user.
Example:
$ podman run --rm --cpus 1 alpine echo hello
Error: the requested cgroup controller `cpu` is not available: OCI runtime error
> cgroup: improve error with unavailable errors

- src/libcrun/linux.c
when remounting read only, leave data unset as older kernel
versions (tested on 4.18) complain with EINVAL if it is set.
Newer kernels seem to ignore it.
Closes: https://github.com/containers/crun/issues/523
> linux: do not set data when remounting read-only

- NEWS
> NEWS: tag release 0.15.1

- README.md
Added instructions for building using OpenSUSE Tumbleweed
> closes containers/crun#517

- configure.ac
Fixed a few issues with configure script. See commits for details.
> configure.ac: nits

- tests/containerd/Dockerfile
- tests/containerd/run-tests.sh
- tests/podman/Dockerfile
> tests: update CI dependencies

- NEWS
> NEWS: tag 0.16

- src/libcrun/seccomp.c
- src/libcrun/seccomp_notify.c
Closes: https://github.com/containers/crun/issues/551
> build: fix build without seccomp

- src/libcrun/linux.c
- src/libcrun/seccomp.c
Closes: https://github.com/containers/crun/issues/553
> build: fix build without libcap

- crun.1
- crun.1.md
Update documentation for checkpoint/restore commands added in 0.16
> Add documentation for checkpoint and restore commands

- src/libcrun/linux.c
> linux: fix build on alpine

- src/libcrun/utils.c
Linux 5.11[1] will have a way to set the CLOEXEC bit on a range of fds
using a single syscall instead of listing /proc/self/fd and close'ing
each of them.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=582f1fb6b721facf04848d2ca57f34468da1813e
> utils: use close_range(CLOSE_RANGE_CLOEXEC) if available

- src/libcrun/cgroup.c
delegate only the files specified in /sys/kernel/cgroup/delegate
> cgroup: honor /sys/kernel/cgroup/delegate

- src/libcrun/cgroup.c
If the cgroup configuration is limiting what CPUs/memory Nodes are
available for the container, then stop the container process during
the cgroup configuration to avoid it being rescheduled on a CPU that
is not allowed.
> cgroup: stop process while setting up cgroups

- NEWS
> NEWS: tag 0.17

- src/libcrun/linux.c
if there is any mount in the container that uses [r]shared, disable
the temporary mount logic as it could affect the parent of the
specified shared mounts.
We could fine tune it to choose a different directory, or skip the
logic only when [r]shared are below the allocated tmpdir, but it is
probably not worth the effort since [r]shared mounts are meant only
for trusted and privileged containers since they can affect the host.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1924841
> linux: disable temporary mounts with [r]shared

- .clang-format
- .github/workflows/test.yaml
- src/libcrun/cgroup.c
- src/libcrun/cgroup.h
- src/libcrun/container.c
- src/libcrun/error.h
- src/libcrun/intprops.h
- src/libcrun/linux.c
- src/libcrun/seccomp.c
- src/libcrun/utils.c
> github: enable clang-format checks

- src/libcrun/linux.c
follow-up for 643d05bc61352257881c8474c559da978b3fdc3a
the initial implementation still has an issue when a mount with
[r]slave exists, and the temporary mounts logic turn it into private.
Extent the initial implementation to also account for [r]slave and at
the same time restrict it only to cases where a bind mount source is a
parent of the temporary mounts directory.
> linux: disable temporary mounts with [r]slave

- .github/workflows/test.yaml
- Makefile.am
- configure.ac
- tests/oci-validation/oci-runtime-validation
- tests/podman/Dockerfile
- tests/podman/run-tests.sh
> tests: update podman and disable pull tests

- .github/workflows/test.yaml
- tests/test_capabilities.py
- tests/test_checkpoint_restore.py
- tests/test_devices.py
- tests/test_limits.py
- tests/test_pid.py
- tests/test_resources.py
- tests/test_rlimits.py
- tests/test_start.py
- tests/test_uid_gid.py
- tests/tests_utils.py
> tests: fix make check in a user namespace

- .github/workflows/release.yaml
- .gitignore
- build-aux/release.sh
> build-aux: provide arm build without systemd

- .github/workflows/test.yaml
- Makefile.am
- README.md
- build-aux/release.sh
- src/libcrun/linux.c
- src/libcrun/seccomp_notify.c
- tests/centos8-build/Dockerfile
- tests/centos8-build/run-tests.sh
- tests/init.c
had to fix a last minute build issue before releasing 0.18.  Make sure it doesn't happen again.
> test: test build on centos8

- src/libcrun/linux.c
Signed-off-by: chris <bigcat26@gmail.com>
> fix: access violate while ret < 0

- src/checkpoint.c
- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/utils.c
- src/restore.c
- tests/init.c
Signed-off-by: chris <bigcat26@gmail.com>
> fix: cross-compiling for Android

- src/libcrun/cgroup.c
it is needed to join named hierarchies on cgroupfs.
> cgroup: read controllers from /proc/self/cgroup

- src/libcrun/linux.c
> linux: label the tmpfs for masked directories

- .github/workflows/test.yaml
- src/libcrun/container.c
- src/libcrun/criu.c
- src/libcrun/linux.c
- tests/clang-check/Dockerfile
- tests/clang-check/run-tests.sh
Adding clang compilation
Fixed some unused and not initialized errors. 
Fixed some comparison of integers with different sign
`cd crun && ./tests/clang-check/run-tests.sh . `
> github CI: add static analysis

- .github/workflows/test.yaml
- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/status.c
- src/libcrun/utils.h
- tests/fuzzing/Dockerfile
- tests/fuzzing/run-tests.sh
- tests/tests_libcrun_fuzzer.c
> github CI: add fuzzing test

- autogen.sh
Remove m4 from root and let autogen.sh generate m4.
> Let autogen.sh generate m4

- tests/clang-check/Dockerfile
> tests: add explicit python3-pip dependency

- NEWS
> NEWS: tag 0.19.1

- src/libcrun/container.c
- tests/oci-validation/oci-runtime-validation
- tests/podman/run-tests.sh
commit ae9ea9274da483c9602ed8aff145ccabc1c16c4b introduced the
regression.
> container: read the error from the init process

- src/libcrun/cgroup.c
if the rmdir for the cgroup fails with EBUSY, attempt to kill all the
procs in the cgroup first.
The issue happened when forcing the container to use an already
existing cgroup and the process fails to cleanup existing processes
there.
> cgroup: kill procs in cgroup on EBUSY

- src/libcrun/container.c
- src/libcrun/linux.c
- src/libcrun/linux.h
> container: apply SELinux label to keyring

- src/libcrun/seccomp.c
> seccomp: report correct action in error message

- src/libcrun/cgroup.c
> cgroups: fix a couple of issues that prevented running under LXC

- NEWS
> NEWS: tag 0.20

- src/libcrun/cgroup.c
- src/libcrun/criu.c
- src/libcrun/linux.c
> crun: fix some issues reported by static analysis tools

- crun.1
- crun.1.md
I've updated the man page to lead people around #696's pitfall
> Reflect #696 in crun's manpage

- README.md
> README.md: drop travis badge

- NEWS
> NEWS: release 0.21

- tests/containerd/Dockerfile
> tests: update containerd version

- src/libcrun/utils.c
refactor common code into a new function.
> utils: add new function safe_readlinkat

- src/libcrun/criu.c
some unrelated fixes for CRIU, each change is in its own commit.
> criu: some cleanups

- .github/workflows/test.yaml
- NEWS
> NEWS: tag 1.1

- NEWS
> NEWS: tag 1.3

- src/libcrun/linux.c
use the current PID when saving external descriptors so we are sure
the process is still alive by the time the std streams are read.
This is safe to do since the std streams are not modified.
Closes: https://github.com/containers/crun/issues/776
> linux: fix a race when saving external descriptors

- crun.1
- crun.1.md
- src/libcrun/linux.c
if the option is present, make the mount ro recursively using the
mount_setattr syscall.
> linux: new mount option "rro"

- Makefile.am
- crun.1
- crun.1.md
- src/libcrun/linux.c
- src/libcrun/mount_flags.c
- src/libcrun/mount_flags.h
- src/libcrun/mount_flags.perf
and while at it, also replace the 0(n) lookup code for mount arguments with a perfect hashing function.
> linux: more recursive options!

- src/libcrun/container.c
> container: make chdir error clearer

- Makefile.am
- tests/init.c
- tests/tests_libcrun_errors.c
- tests/tests_libcrun_fuzzer.c
I was working on something else and saw that the C files in tests are not formatted using clang-format.
This PR includes the C files in tests in clang-format runs.
> Also run clang-format on *.c files in tests/

- src/libcrun/cgroup-utils.c
- src/libcrun/cgroup-utils.h
- src/libcrun/linux.c
take advantage of two new features in the kernel.
> exec: use clone3 and setns() with pidfd where available

- src/libcrun/linux.c
commit a32286c5b277971ec62ad4c4ca881d4413d2b1ae introduced the
regression.
> linux: fix join cgroup v1

- .github/workflows/test.yaml
- configure.ac
- src/libcrun/cgroup-resources.c
- src/libcrun/ebpf.c
- src/libcrun/utils.c
- src/libcrun/utils.h
- tests/cri-o/Dockerfile
- tests/cri-o/run-tests.sh
> tests: add CRI-O integration tests to the CI

- src/libcrun/cgroup-resources.c
- tests/test_resources.py
add a new function to write cgroup files.
Differently than `write_file_at`, it doesn't specify O_CREAT so that
writes to files that do not exist fail with ENOENT instead of EPERM.
> cgroup: add function to write to the files

- src/libcrun/cgroup.c
> cgroup: initialize status

- .github/workflows/codeql-analysis.yml
> ci: enable codeql analysis

- python/crun_python.c
- src/crun.c
- src/kill.c
- src/libcrun/cgroup-cgroupfs.c
- src/libcrun/cgroup-resources.c
- src/libcrun/cgroup-setup.c
- src/libcrun/cgroup-systemd.c
- src/libcrun/cgroup-utils.c
- src/libcrun/cgroup.c
- src/libcrun/container.c
- src/libcrun/container.h
- src/libcrun/criu.c
- src/libcrun/custom-handler.c
- src/libcrun/linux.c
- src/libcrun/signals.c
- src/libcrun/signals.perf
- src/libcrun/status.c
- src/libcrun/utils.c
- src/libcrun/utils.h
- tests/test_start.py
- tests/tests_libcrun_fuzzer.c
- tests/tests_libcrun_utils.c
> api: unexport some functions

- src/libcrun/container.c
- tests/oci-validation/oci-runtime-validation
- tests/test_start.py
allow to delete a container if it is in created state.
Closes: https://github.com/containers/crun/issues/837
> container: allow delete while in created state

- src/libcrun/linux.c
- tests/cri-o/run-tests.sh
- tests/test_start.py
~~_This is just to test CI, as it seems to fail in my recent PRs_~~
> Fix some typos found by codespell

- src/libcrun/cgroup-setup.c
> cgroup: do not lookup string twice

- src/libcrun/container.c
- src/libcrun/error.h
- src/libcrun/utils.c
- src/libcrun/utils.h
decorate some functions with attributes to help the compiler.  More details in each commit.
> add some function attributes

- NEWS
> NEWS: tag 1.4.2

- src/libcrun/linux.c
- src/libcrun/linux.h
- tests/fuzzing/Dockerfile
- tests/fuzzing/run-tests.sh
- tests/tests_libcrun_fuzzer.c
fuzz the idmapped mounts option parser.
> tests: add fuzzing for idmapped mounts option

- cfg.mk
- src/libcrun/utils.h
Signed-off-by: Alex Fabijanic <alex@pocoproject.org>
> chore(utils): add pointer casts to avoid C++ permissive mode

- NEWS
> NEWS: tag 1.4.3

- tests/clang-check/Dockerfile
> tests, clang-check: install git

- contrib/terminal-receiver/terminal-receiver.c
Signed-off-by: Alex Fabijanic <alex@pocoproject.org>
> feat(terminal-receiver): make terminal interactive

- tests/cri-o/run-tests.sh
> tests: disable failing CRI-O tests

- tests/test_delete.py
> tests: delete multiple containers

- tests/test_exec.py
> tests: specify an additional capability to add to the process

- tests/test_exec.py
> tests: add an environment variable

- .github/workflows/test.yaml
- tests/alpine-build/run-tests.sh
- tests/containerd/run-tests.sh
> github: fix CI

- tests/init.c
- tests/test_exec.py
> tests: specify the user in the form UID[:GID]

- tests/test_exec.py
> tests: add tests for covering '--pid-file' and '--no-new-privs' options

- README.md
Update readme.md to show crun logo.
> readme: show crun logo

- src/libcrun/linux.c
honor the new mappings per mount that were added to the OCI runtime specs.
> linux: honor mount mappings

- src/libcrun/linux.c
The kernel doesn't allow though to re-mount a new sysfs or proc if
there is not another mount already visible in the current mount
namespace.
When using no-pivot, we umount /sys and /proc to prevent the container
to re-mount them.  If the umount fails, just mount a tmpfs on top of
them since it will have the same effect.
> linux: fallback to tmpfs mount if umount fails

- src/libcrun/linux.c
if for any reason it is not possible to create the AF_INET socket (e.g. it could be restricted by systemd with RestrictAddressFamilies=) then we fallback to netlink to setup the lo device.
Closes: https://github.com/containers/crun/issues/929
> linux: fallback to netlink to setup lo device

- .github/workflows/test.yaml
- configure.ac
- src/libcrun/handlers/wasmedge.c
- tests/wasmedge-build/Dockerfile
- tests/wasmedge-build/run-tests.sh
Fixes #934 
i don't have much experience with C, so correct me if something is wrong.
Signed-off-by: Lukas Hoehl <lukas.hoehl@accso.de>
> fix(wasmedge): breaking changes in wasmedge c api

- src/libcrun/linux.c
- tests/test_mounts.py
commit b02a68d449511ea78c0b7be7fcb8590b06b71072 introduced the
regression and the idmap configuration passed through the annotation
was not honored.
Tests for the feature already exist but they do not run in the CI as
they require a new enough Linux kernel that supports idmapped mounts.
> linux: fix idmap annotation

- build-aux/release.sh
> nix: allow to pass EXTRA_ARGS to the runtime

- src/libcrun/linux.c
if pidfd_send_signal fails with ENOSYS then fallback to using the kill
syscall.
Closes: https://github.com/containers/crun/issues/969
> pidfd: fallback on ENOSYS

- cfg.mk
- maint.mk
- src/libcrun/container.c
- src/libcrun/criu.c
- src/libcrun/criu.h
- src/libcrun/handlers/wasmer.c
- src/libcrun/seccomp.c
- src/libcrun/utils.c
> src: update syntax check

- src/libcrun/criu.c
Restore procedure does not work when an absolute path with symbolic link is provided as '--bundle' command parameter.
Crun fails comparing it with a path taken from FD in `utils.c::check_fd_under_path()`. On create the same path works fine.
The difference comes from the fact that `linux.c::libcrun_set_mounts()` receives the result of realpath in `container.c::container_init_setup()`, but `criu.c::prepare_restore_mounts()` receives from `criu.c::libcrun_container_restore_linux_criu()` the root path as provided in bundle.
This proposition should not harm restore procedure as in case of `realpath()` call failure, the bundle path is taken as before the change.
> crun: restore will work on realpath

- src/libcrun/handlers/krun.c
In addition of the regular library, libkrun provides a variant,
libkrun-sev, that turns the microVM into a TEE (Trusted Execution
Environment) using AMD SEV/SEV-ES/SEV-SNP.
This commit updates the krun handler to support using libkrun-sev in
addition of the regular libkrun. If the file "krun-sev.json" [1] is
found in the root of the OCI image, the handler will attempt to use
libkrun-sev and fail if it wasn't dlopen'ed. If the file isn't found,
the handler will attempt to use libkrun and work the same way as
before.
The handler supports that only one of the variants are present in the
system, and will only fail if the one that's missing is required to
run a particular container.
[1] oci2cw (https://github.com/virtee/oci2cw) allows to transform
regular OCI images into images that are …
> krun: add support for krun-sev

- src/libcrun/utils.c
when a timeout out is specified, make sure the original sigmask is
restored when the function returns.
> utils: run process with timeout restores sigmask

- tests/containerd/Dockerfile
> tests: update containerd to 1.6.8

- src/libcrun/cgroup-resources.c
if checkBeforeUpdate is set, verify that the cgroup memory limit is not lower than its current usage.
> cgroup: honor checkBeforeUpdate

- src/libcrun/container.c
attempt to chown the std streams file descriptors before joining the user namespace. The files' owner might not be mapped inside the user namespace, thus causing the chown inside the user namespace to fail.
Closes: https://github.com/containers/crun/issues/1019
> crun: chown std streams before joining the user namespace

- src/libcrun/cgroup-resources.c
change the check so that it accounts also for swap usage.
> cgroup: account for swap usage for checkBeforeUsage

- .github/dependabot.yml
This will make dependabot check all of the github actions which this project using for any updates and will submit pull requests with version bumps.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> Check for github actions updates on weekly basis

- src/libcrun/container.c
- src/libcrun/handlers/wasmtime.c
few fixes for wasmtime, more details in each commit.
> some cleanups for wasmtime

- NEWS
these items were only available in the github release notes.
> NEWS: fill data for old releases

- src/libcrun/handlers/wasmtime.c
Add support for compiling wasm binary directly from `*.wat` ( Webassembly Text Format ) if OCI image only containers webassembly text format instead of binary then compile on the fly and pretend a regular compiled binary was supplied.
```Dockerfile
FROM scratch
COPY src.wat /
CMD ["/src.wat"]
```
> wasmtime: add support for compiling `*.wat` ( Webassembly Text format) on the fly.

- src/libcrun/cgroup-utils.c
- src/libcrun/container.c
- src/libcrun/utils.c
> libcrun: fix some mem leaks

- NEWS
> NEWS: tag 1.7

- src/libcrun/seccomp.c
Closes: https://github.com/containers/crun/issues/1062
> seccomp: initialize libgcrypt

- src/libcrun/error.c
- src/libcrun/utils.c
Signed-off-by: John Muth <muth@kontain.app>
> fix timestamp format, tv_usec is microsecond not nanosecond

- configure.ac
- src/libcrun/criu.c
- src/libcrun/criu.h
- src/libcrun/intprops.h
- src/libcrun/utils.h
Closes: https://github.com/containers/crun/issues/1066
> criu: load libcriu dynamically

- NEWS
> NEWS: tag 1.7.1

- tests/podman/Dockerfile
> tests: fix podman tests

- .github/workflows/test.yaml
> github: fix cri-o CI on cgroupv2

- tests/cri-o/run-tests.sh
> tests: disable some CRI-O failing tests

- tests/cri-o/Dockerfile
> tests, cri-o: update go to 1.19

- src/libcrun/cloned_binary.c
Prep for further work; this is significantly more ergonomic and avoids double close type bugs, etc.
Signed-off-by: Colin Walters <walters@verbum.org>
> cloned_binary: use cleanup_close

- tests/centos9-build/run-tests.sh
- tests/cri-o/Dockerfile
- tests/cri-o/run-tests.sh
- tests/wasmedge-build/Dockerfile
> ci: fix a bunch of unrelated failures

- src/libcrun/cloned_binary.c
Motivated by https://lwn.net/Articles/918106/
which is aiming to extend the kernel memfd API to more cleanly
separate executable from writable memfds.
But this whole "copy self to memfd" is a big mess that is only necessary
if our *underlying binary is mutable*.  Many "image based" systems
nowadays have read-only root filesystems and were never vulnerable
to the original problem.
It turns out that crun has had logic to detect a read-only bind
mount for quite a while, but only allowed it in the case where
its own special environment variable was set (signaling that
the mount was almost certainly created by crun).
But if we just tweak and reorder this logic, then it extends
to other read-only mount cases.  I believe this is safe.
Notes:
- We could also extend this to check for the immutable …
> Don't clone self from read-only mount

- src/crun.c
> crun: fix clang format

- nix/default-arm64.nix
- nix/default.nix
- nix/nixpkgs.json
> nix: update packages

- README.md
> README.md: fix badges

- .github/workflows/release.yaml
- build-aux/release.sh
- nix/default-arm64.nix
- nix/default-ppc64le.nix
- nix/default.nix
also carry the patch from https://github.com/containers/crun/pull/993
> few cleanups for the nix builder

- NEWS
> NEWS: tag 1.8

- src/libcrun/container.c
- src/libcrun/utils.c
- src/libcrun/utils.h
This reverts commit 87b69c37b1cddba33be74125f5b9fd6b1ed425ed.
> Revert "Support passing an attribute to change the mount_context_type"

- .github/workflows/test.yaml
- src/libcrun/handlers/handler-utils.c
- src/libcrun/linux.c
> src: run codespell

- crun.1.md
> crun.1.md: fix markup

- src/libcrun/utils.c
- src/libcrun/utils.h
> minor cleanups to read_file

- tests/cri-o/run-tests.sh
> test: remove irqbalance tests

- src/libcrun/cgroup-resources.c
simplify some common patterns in the cgroup code.
More details in each commit
> Simplify code with name alias

- .gitignore
- Makefile.am
- README.md
- configure.ac
- lua/README.md
- lua/lua_crun.c
- lua/luacrun.d.tl
- lua/luacrun_spec.lua
- m4/ax_lua.m4
This PR introduces a libcrun binding for Lua.
- Create, delete and kill a container
- Get template container spec
- Fetch container status
> lua: add Lua bindings

- src/libcrun/linux.c
- tests/test_mounts.py
When making paths readonly crun should check if this it is a `sub-mount` if yes then flags must be inherited from the parent mount along with making path `readonly`
Closes: https://github.com/containers/crun/issues/950
> linux: `readonlyPaths` should inherit flags from parent mount

- tests/test_mounts.py
Fix a typo made in: https://github.com/containers/crun/pull/1168
> test_mount: fix incorrect comment

- docs/wasm-wasi-example.md
Add a tryout example which can be directly tried by the users.
> docs: add a tryout example with podman

- src/libcrun/cgroup-resources.c
Sometimes setting CPU quota period fails when a new period is lower, and a parent cgroup has CPU quota limit set.
This happens as in cgroup v1 the quota and the period can not be set together (this is fixed in v2), and since the period is being set first, new_limit = old_quota/new_period may be higher than the parent cgroup limit.
The fix is to retry setting the period after the quota, to cover all possible scenarios.
Tested via runc integration tests. Before the commit, it fails:
root@ubu2004:~/git/runc# RUNC=`pwd`/../crun/crun.before bats -f "pod cgroup" -t  tests/integration/update.bats
1..1
not ok 1 update cpu period in a pod cgroup with pod limit set
#
#
With the fix, the test passes.
Originally reported for runc in
https://github.com/opencontainers/runc/issues/3084
> cgroup: workaround cpu quota/period issue with v1

- src/libcrun/cgroup-resources.c
- tests/test_resources.py
change the type for the format string to accept a negative number.
Closes: https://issues.redhat.com/browse/OCPBUGS-11510
> cgroup: fix set quota to -1

- src/libcrun/criu.c
we cannot use the criu_check_version before calling criu_init_opts. To avoid the issue, just try to lookup the symbol in any case instead of checking the CRIU library version.  If it is not available leave criu_join_ns_add set to NULL.
commit df8ee48f722d8252bf2556b69e1a42c52dcd86d0 introduced the regression.
> criu: fix segfault if CRIU_JOIN_NS_SUPPORT is defined

- configure.ac
- src/libcrun/seccomp.c
Closes: https://github.com/containers/crun/issues/1225
> build: add check for atomic_bool

- src/libcrun/error.c
- src/libcrun/error.h
- src/libcrun/linux.c
various improvements for the error handling in libcrun
> improve error handling

- src/libcrun/cgroup-systemd.c
- src/libcrun/linux.c
A side-note: It looks like a fix is needed here too:
https://github.com/containers/crun/blob/6369207ebf9346134eaf6909feb65914822331ba/src/libcrun/linux.c#L5080-L5082
I'm not quite sure how the fix should look like so I didn't include it in this PR.
> linux + cgroup-systemd: fix error return values

- src/libcrun/handlers/wasmer.c
Modify wasmer handler to use newer WASIX API.
Closes: https://github.com/containers/crun/issues/1263
> wasmer: use latest `wasix` API

- lua/lua_crun.c
- lua/luacrun_spec.lua
* fix `luacrun_new_ctx` silently ignore non-table argument
* fix some functions assume error is not NULL if they get negative return code
* added some tests
it might fix #1288
> lua: fix random errors

- src/libcrun/cgroup-setup.c
- src/libcrun/cgroup.c
Old kernels do that automatically, but new kernels remember the affinity that was set before the cgroup move due to
https://lore.kernel.org/lkml/20220922180041.1768141-1-longman@redhat.com
This is undesirable for containers, because they inherit the systemd affinity when the should really move to the container space cpus.
alternative to https://github.com/containers/crun/pull/1305
> Reset the inherited cpu affinity after moving to cgroup

- src/libcrun/cgroup-systemd.c
when running as unprivileged user, always use the user session for the sd_bus.
Differently, for root always use the system session.
Closes: https://github.com/containers/crun/issues/1327
> cgroup: always use the user session for rootless

- src/libcrun/cgroup-internal.h
- src/libcrun/cgroup-resources.c
- src/libcrun/cgroup-setup.c
- src/libcrun/cgroup-systemd.c
- src/libcrun/cgroup-systemd.h
- tests/fuzzing/run-tests.sh
- tests/tests_libcrun_fuzzer.c
- tests/tests_libcrun_utils.c
Closes: https://issues.redhat.com/browse/OCPBUGS-20492
> cgroup, systemd: set cpu quota and cpuset configuration in the scope cgroup

- src/libcrun/utils.c
- src/list.c
Closes: https://github.com/containers/crun/issues/1373
> utils: return a valid error if access fails

- src/libcrun/status.c
I marked the PR as a draft because I have not yet built and run the code.
> status: fix double free

- src/libcrun/linux.c
Some filesystems don't support idmap mounts and just showing to the user invalid argument is not super clear.
When errno is EINVAL, let's add a text hinting that the cause could be that idmap mounts are not supported on the filesystem used.
--
I think this should help for reports like https://github.com/containers/crun/issues/1380 . It would help us understand that the fs probably doesn't support idmap mounts and the user will likely understand why it is failing too.
We can do the same in `do_mount_setattr()`, but it isn't really needed. Do you have any preferences @giuseppe ?
> Improve error msg on idmap mounts

- src/libcrun/ebpf.c
Linux commit 3ac1f01b43b6e2759cc34d3a715ba5eed04c5805, present in Linux 5.11, changed the way memory for eBPF programs is accounted. They do not use rlimit-based memory accounting anymore, buy memcg-based memory accounting.
Closes: https://github.com/containers/crun/issues/1388
> ebpf: do not require MEMLOCK for eBPF programs

- src/libcrun/cgroup-setup.c
Previously we were overwriting the value of the parent cgroup when writing cpuset. This was based off of the resources struct for the container This works well when there's just one container, but when there's multiple under the parent (like a pod with an infra container), we fail to have the right cpuset because we've already overwritten the parent.
> cpuset: don't clobber parent cgroup value

- src/libcrun/linux.c
- tests/test_mounts.py
do not assume it is a directory, but check the source type.
Closes: https://github.com/containers/crun/issues/1421
> linux: fix mount of file with recursive flags

- NEWS
Closes: https://github.com/containers/crun/issues/1426
> NEWS: tag 1.14.4

- src/libcrun/cgroup-utils.c
improve some cgroup errors including what controllers we are trying to enable.
> cgroup: make error clearer

- src/libcrun/handlers/wasmedge.c
This facilitates the direct loading of the `ggml` plugin into crun for executing AI models. The objective is to integrate the wasi-nn plugin with crun, enabling CRI-O to utilize the execution of WebAssembly (Wasm) workloads that involve running AI models.
> src/libcrun/handlers: add option to load wasi-nn plugin for wasmedge

- tests/oci-validation/Dockerfile
> tests: bump tap version

- .github/workflows/release.yaml
This saves on precious CI capacity.
> ci: Cancel in progress tests on updates

- src/libcrun/container.c
remove duplicate initialization cgroup manager in the cgroup args
> remove duplicate initialization cgroup manager in the cgroup args

- README.md
podman doesn't have that limit anymore.
> README: update podman demo

- src/libcrun/container.c
- src/libcrun/linux.c
if the rootfs has an inaccessible parent directory, attempt to use the relative directory and not the absolute path.
> improve handling of unreachable rootfs

- src/libcrun/cgroup-resources.c
- src/libcrun/cgroup-setup.c
- src/libcrun/cgroup-systemd.c
- src/libcrun/cgroup-utils.c
- src/libcrun/handlers/krun.c
- src/libcrun/linux.c
- src/libcrun/status.c
- src/libcrun/utils.c
Currently WIP (work in progress).
I haven't done any benchmarks yet. 
Fixes: https://github.com/containers/crun/issues/1478
> Add more O_PATH flags

- src/libcrun/linux.c
Fixes https://github.com/containers/crun/issues/1510
> src/libcrun: added custom error message for ESRCH case

- src/libcrun/linux.c
This patch addresses the issue where the `setns mnt: Bad file descriptor` error can occur during namespace restoration, specifically with the mount namespace (CLONE_NEWNS). The error arises when crun attempts to restore a namespace that hasn't been properly tracked, leading to an invalid file descriptor being passed to setns.
> src/libcrun: improve error handling for the mnt namespace restoration

- lua/lua_crun.c
- python/crun_python.c
- src/crun.c
- src/crun.h
- src/libcrun/container.c
- src/libcrun/error.c
- src/libcrun/error.h
Part of https://github.com/containers/crun/issues/1525
> Add `--log-level` option

- src/libcrun/container.c
but use the version generated by libocispec.
Follow-up for https://github.com/containers/crun/pull/1538
> container: remove manual dup operation

- src/libcrun/linux.c
oci add duplicate namespace detection。
original pr: https://github.com/containers/crun/pull/1564
> add duplicate namespace detection

- NEWS
> NEWS: tag 1.18

- crun.1
- crun.1.md
Adding periods to end of sentence.
> Add missing periods at the end of sentence

- src/libcrun/handlers/krun.c
Fixes: https://github.com/containers/crun/issues/1660
> krun: fix libkrun_exec return value

- src/libcrun/linux.c
Fixes: https://github.com/containers/crun/issues/1677
> linux: remove dead code

- src/libcrun/handlers/krun.c
Fixes: https://github.com/containers/crun/issues/1696
> krun: fix error message

- src/libcrun/utils.c
- tests/test_cwd.py
- tests/test_start.py
the caller checks that the return value is negative.
Closes: https://issues.redhat.com/browse/OCPBUGS-45016
> utils: set_home_env returns negative value on errors

- src/libcrun/container.c
seccomp plugins and seccomp receivers cannot be declared at the same time.
> seccomp plugins and seccomp receivers cannot be declared at the same time
